package com.focustech.focus3d.paint.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "paint_share", Class = PaintShare.class)
public class PaintShare<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_share.SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_share.PIC_FILE_SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    @Column
    private Long picFileSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_share.PRODUCT_SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    @Column
    private Long productSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_share.ADDER_SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_share.ADDER_NAME
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_share.ADD_TIME
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_share.UPDATER_SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_share.UPDATER_NAME
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_share.UPDATE_TIME
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_share.encryptSn
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_share.SN
     *
     * @return the value of paint_share.SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_share.SN
     *
     * @param sn the value for paint_share.SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_share.PIC_FILE_SN
     *
     * @return the value of paint_share.PIC_FILE_SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public Long getPicFileSn() {
        return picFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_share.PIC_FILE_SN
     *
     * @param picFileSn the value for paint_share.PIC_FILE_SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public void setPicFileSn(Long picFileSn) {
        this.picFileSn = picFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_share.PRODUCT_SN
     *
     * @return the value of paint_share.PRODUCT_SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public Long getProductSn() {
        return productSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_share.PRODUCT_SN
     *
     * @param productSn the value for paint_share.PRODUCT_SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public void setProductSn(Long productSn) {
        this.productSn = productSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_share.ADDER_SN
     *
     * @return the value of paint_share.ADDER_SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_share.ADDER_SN
     *
     * @param adderSn the value for paint_share.ADDER_SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_share.ADDER_NAME
     *
     * @return the value of paint_share.ADDER_NAME
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_share.ADDER_NAME
     *
     * @param adderName the value for paint_share.ADDER_NAME
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_share.ADD_TIME
     *
     * @return the value of paint_share.ADD_TIME
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_share.ADD_TIME
     *
     * @param addTime the value for paint_share.ADD_TIME
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_share.UPDATER_SN
     *
     * @return the value of paint_share.UPDATER_SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_share.UPDATER_SN
     *
     * @param updaterSn the value for paint_share.UPDATER_SN
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_share.UPDATER_NAME
     *
     * @return the value of paint_share.UPDATER_NAME
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_share.UPDATER_NAME
     *
     * @param updaterName the value for paint_share.UPDATER_NAME
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_share.UPDATE_TIME
     *
     * @return the value of paint_share.UPDATE_TIME
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_share.UPDATE_TIME
     *
     * @param updateTime the value for paint_share.UPDATE_TIME
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_share.encryptSn
     *
     * @return the value of paint_share.encryptSn
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_share.encryptSn
     *
     * @param encryptSn the value for paint_share.encryptSn
     *
     * @ibatorgenerated Tue Dec 20 12:19:12 CST 2016
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}