package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "biz_agent_user_role", Class = BizAgentUserRole.class)
public class BizAgentUserRole<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_role.SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_role.USER_SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    @Column
    private Long userSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_role.ROLE_SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    @Column
    private Long roleSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_role.ADDER_SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_role.ADDER_NAME
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_role.ADD_TIME
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_role.UPDATER_SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_role.UPDATER_NAME
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_role.UPDATE_TIME
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_role.SN
     *
     * @return the value of biz_agent_user_role.SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_role.SN
     *
     * @param sn the value for biz_agent_user_role.SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_role.USER_SN
     *
     * @return the value of biz_agent_user_role.USER_SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public Long getUserSn() {
        return userSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_role.USER_SN
     *
     * @param userSn the value for biz_agent_user_role.USER_SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public void setUserSn(Long userSn) {
        this.userSn = userSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_role.ROLE_SN
     *
     * @return the value of biz_agent_user_role.ROLE_SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public Long getRoleSn() {
        return roleSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_role.ROLE_SN
     *
     * @param roleSn the value for biz_agent_user_role.ROLE_SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public void setRoleSn(Long roleSn) {
        this.roleSn = roleSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_role.ADDER_SN
     *
     * @return the value of biz_agent_user_role.ADDER_SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_role.ADDER_SN
     *
     * @param adderSn the value for biz_agent_user_role.ADDER_SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_role.ADDER_NAME
     *
     * @return the value of biz_agent_user_role.ADDER_NAME
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_role.ADDER_NAME
     *
     * @param adderName the value for biz_agent_user_role.ADDER_NAME
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_role.ADD_TIME
     *
     * @return the value of biz_agent_user_role.ADD_TIME
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_role.ADD_TIME
     *
     * @param addTime the value for biz_agent_user_role.ADD_TIME
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_role.UPDATER_SN
     *
     * @return the value of biz_agent_user_role.UPDATER_SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_role.UPDATER_SN
     *
     * @param updaterSn the value for biz_agent_user_role.UPDATER_SN
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_role.UPDATER_NAME
     *
     * @return the value of biz_agent_user_role.UPDATER_NAME
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_role.UPDATER_NAME
     *
     * @param updaterName the value for biz_agent_user_role.UPDATER_NAME
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_role.UPDATE_TIME
     *
     * @return the value of biz_agent_user_role.UPDATE_TIME
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_role.UPDATE_TIME
     *
     * @param updateTime the value for biz_agent_user_role.UPDATE_TIME
     *
     * @ibatorgenerated Mon Aug 08 18:33:09 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}