package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "biz_agent_user", Class = BizAgentUser.class)
public class BizAgentUserCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public BizAgentUserCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public BizAgentUserCriteria(BizAgentUserCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public BizAgentUserCriteria(Object record, BizAgentUserCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table biz_agent_user
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andSnIsNull() {
            addCriterion("SN is null");
            return this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("SN is not null");
            return this;
        }

        public Criteria andSnEqualTo(Long value) {
            addCriterion("SN =", value, "sn");
            return this;
        }

        public Criteria andSnNotEqualTo(Long value) {
            addCriterion("SN <>", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThan(Long value) {
            addCriterion("SN >", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SN >=", value, "sn");
            return this;
        }

        public Criteria andSnLessThan(Long value) {
            addCriterion("SN <", value, "sn");
            return this;
        }

        public Criteria andSnLessThanOrEqualTo(Long value) {
            addCriterion("SN <=", value, "sn");
            return this;
        }

        public Criteria andSnIn(List values) {
            addCriterion("SN in", values, "sn");
            return this;
        }

        public Criteria andSnNotIn(List values) {
            addCriterion("SN not in", values, "sn");
            return this;
        }

        public Criteria andSnBetween(Long value1, Long value2) {
            addCriterion("SN between", value1, value2, "sn");
            return this;
        }

        public Criteria andSnNotBetween(Long value1, Long value2) {
            addCriterion("SN not between", value1, value2, "sn");
            return this;
        }

        public Criteria andPartnerIdIsNull() {
            addCriterion("PARTNER_ID is null");
            return this;
        }

        public Criteria andPartnerIdIsNotNull() {
            addCriterion("PARTNER_ID is not null");
            return this;
        }

        public Criteria andPartnerIdEqualTo(String value) {
            addCriterion("PARTNER_ID =", value, "partnerId");
            return this;
        }

        public Criteria andPartnerIdNotEqualTo(String value) {
            addCriterion("PARTNER_ID <>", value, "partnerId");
            return this;
        }

        public Criteria andPartnerIdGreaterThan(String value) {
            addCriterion("PARTNER_ID >", value, "partnerId");
            return this;
        }

        public Criteria andPartnerIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARTNER_ID >=", value, "partnerId");
            return this;
        }

        public Criteria andPartnerIdLessThan(String value) {
            addCriterion("PARTNER_ID <", value, "partnerId");
            return this;
        }

        public Criteria andPartnerIdLessThanOrEqualTo(String value) {
            addCriterion("PARTNER_ID <=", value, "partnerId");
            return this;
        }

        public Criteria andPartnerIdLike(String value) {
            addCriterion("PARTNER_ID like", value, "partnerId");
            return this;
        }

        public Criteria andPartnerIdNotLike(String value) {
            addCriterion("PARTNER_ID not like", value, "partnerId");
            return this;
        }

        public Criteria andPartnerIdIn(List values) {
            addCriterion("PARTNER_ID in", values, "partnerId");
            return this;
        }

        public Criteria andPartnerIdNotIn(List values) {
            addCriterion("PARTNER_ID not in", values, "partnerId");
            return this;
        }

        public Criteria andPartnerIdBetween(String value1, String value2) {
            addCriterion("PARTNER_ID between", value1, value2, "partnerId");
            return this;
        }

        public Criteria andPartnerIdNotBetween(String value1, String value2) {
            addCriterion("PARTNER_ID not between", value1, value2, "partnerId");
            return this;
        }

        public Criteria andMobilePhoneIsNull() {
            addCriterion("MOBILE_PHONE is null");
            return this;
        }

        public Criteria andMobilePhoneIsNotNull() {
            addCriterion("MOBILE_PHONE is not null");
            return this;
        }

        public Criteria andMobilePhoneEqualTo(String value) {
            addCriterion("MOBILE_PHONE =", value, "mobilePhone");
            return this;
        }

        public Criteria andMobilePhoneNotEqualTo(String value) {
            addCriterion("MOBILE_PHONE <>", value, "mobilePhone");
            return this;
        }

        public Criteria andMobilePhoneGreaterThan(String value) {
            addCriterion("MOBILE_PHONE >", value, "mobilePhone");
            return this;
        }

        public Criteria andMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE_PHONE >=", value, "mobilePhone");
            return this;
        }

        public Criteria andMobilePhoneLessThan(String value) {
            addCriterion("MOBILE_PHONE <", value, "mobilePhone");
            return this;
        }

        public Criteria andMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("MOBILE_PHONE <=", value, "mobilePhone");
            return this;
        }

        public Criteria andMobilePhoneLike(String value) {
            addCriterion("MOBILE_PHONE like", value, "mobilePhone");
            return this;
        }

        public Criteria andMobilePhoneNotLike(String value) {
            addCriterion("MOBILE_PHONE not like", value, "mobilePhone");
            return this;
        }

        public Criteria andMobilePhoneIn(List values) {
            addCriterion("MOBILE_PHONE in", values, "mobilePhone");
            return this;
        }

        public Criteria andMobilePhoneNotIn(List values) {
            addCriterion("MOBILE_PHONE not in", values, "mobilePhone");
            return this;
        }

        public Criteria andMobilePhoneBetween(String value1, String value2) {
            addCriterion("MOBILE_PHONE between", value1, value2, "mobilePhone");
            return this;
        }

        public Criteria andMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("MOBILE_PHONE not between", value1, value2, "mobilePhone");
            return this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("USER_NAME is null");
            return this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("USER_NAME is not null");
            return this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("USER_NAME =", value, "userName");
            return this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "userName");
            return this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "userName");
            return this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "userName");
            return this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("USER_NAME <", value, "userName");
            return this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "userName");
            return this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("USER_NAME like", value, "userName");
            return this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("USER_NAME not like", value, "userName");
            return this;
        }

        public Criteria andUserNameIn(List values) {
            addCriterion("USER_NAME in", values, "userName");
            return this;
        }

        public Criteria andUserNameNotIn(List values) {
            addCriterion("USER_NAME not in", values, "userName");
            return this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "userName");
            return this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "userName");
            return this;
        }

        public Criteria andAgentGradeIsNull() {
            addCriterion("AGENT_GRADE is null");
            return this;
        }

        public Criteria andAgentGradeIsNotNull() {
            addCriterion("AGENT_GRADE is not null");
            return this;
        }

        public Criteria andAgentGradeEqualTo(Integer value) {
            addCriterion("AGENT_GRADE =", value, "agentGrade");
            return this;
        }

        public Criteria andAgentGradeNotEqualTo(Integer value) {
            addCriterion("AGENT_GRADE <>", value, "agentGrade");
            return this;
        }

        public Criteria andAgentGradeGreaterThan(Integer value) {
            addCriterion("AGENT_GRADE >", value, "agentGrade");
            return this;
        }

        public Criteria andAgentGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("AGENT_GRADE >=", value, "agentGrade");
            return this;
        }

        public Criteria andAgentGradeLessThan(Integer value) {
            addCriterion("AGENT_GRADE <", value, "agentGrade");
            return this;
        }

        public Criteria andAgentGradeLessThanOrEqualTo(Integer value) {
            addCriterion("AGENT_GRADE <=", value, "agentGrade");
            return this;
        }

        public Criteria andAgentGradeIn(List values) {
            addCriterion("AGENT_GRADE in", values, "agentGrade");
            return this;
        }

        public Criteria andAgentGradeNotIn(List values) {
            addCriterion("AGENT_GRADE not in", values, "agentGrade");
            return this;
        }

        public Criteria andAgentGradeBetween(Integer value1, Integer value2) {
            addCriterion("AGENT_GRADE between", value1, value2, "agentGrade");
            return this;
        }

        public Criteria andAgentGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("AGENT_GRADE not between", value1, value2, "agentGrade");
            return this;
        }

        public Criteria andTotalSalesIsNull() {
            addCriterion("TOTAL_SALES is null");
            return this;
        }

        public Criteria andTotalSalesIsNotNull() {
            addCriterion("TOTAL_SALES is not null");
            return this;
        }

        public Criteria andTotalSalesEqualTo(Integer value) {
            addCriterion("TOTAL_SALES =", value, "totalSales");
            return this;
        }

        public Criteria andTotalSalesNotEqualTo(Integer value) {
            addCriterion("TOTAL_SALES <>", value, "totalSales");
            return this;
        }

        public Criteria andTotalSalesGreaterThan(Integer value) {
            addCriterion("TOTAL_SALES >", value, "totalSales");
            return this;
        }

        public Criteria andTotalSalesGreaterThanOrEqualTo(Integer value) {
            addCriterion("TOTAL_SALES >=", value, "totalSales");
            return this;
        }

        public Criteria andTotalSalesLessThan(Integer value) {
            addCriterion("TOTAL_SALES <", value, "totalSales");
            return this;
        }

        public Criteria andTotalSalesLessThanOrEqualTo(Integer value) {
            addCriterion("TOTAL_SALES <=", value, "totalSales");
            return this;
        }

        public Criteria andTotalSalesIn(List values) {
            addCriterion("TOTAL_SALES in", values, "totalSales");
            return this;
        }

        public Criteria andTotalSalesNotIn(List values) {
            addCriterion("TOTAL_SALES not in", values, "totalSales");
            return this;
        }

        public Criteria andTotalSalesBetween(Integer value1, Integer value2) {
            addCriterion("TOTAL_SALES between", value1, value2, "totalSales");
            return this;
        }

        public Criteria andTotalSalesNotBetween(Integer value1, Integer value2) {
            addCriterion("TOTAL_SALES not between", value1, value2, "totalSales");
            return this;
        }

        public Criteria andTaskProgressIsNull() {
            addCriterion("TASK_PROGRESS is null");
            return this;
        }

        public Criteria andTaskProgressIsNotNull() {
            addCriterion("TASK_PROGRESS is not null");
            return this;
        }

        public Criteria andTaskProgressEqualTo(BigDecimal value) {
            addCriterion("TASK_PROGRESS =", value, "taskProgress");
            return this;
        }

        public Criteria andTaskProgressNotEqualTo(BigDecimal value) {
            addCriterion("TASK_PROGRESS <>", value, "taskProgress");
            return this;
        }

        public Criteria andTaskProgressGreaterThan(BigDecimal value) {
            addCriterion("TASK_PROGRESS >", value, "taskProgress");
            return this;
        }

        public Criteria andTaskProgressGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TASK_PROGRESS >=", value, "taskProgress");
            return this;
        }

        public Criteria andTaskProgressLessThan(BigDecimal value) {
            addCriterion("TASK_PROGRESS <", value, "taskProgress");
            return this;
        }

        public Criteria andTaskProgressLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TASK_PROGRESS <=", value, "taskProgress");
            return this;
        }

        public Criteria andTaskProgressIn(List values) {
            addCriterion("TASK_PROGRESS in", values, "taskProgress");
            return this;
        }

        public Criteria andTaskProgressNotIn(List values) {
            addCriterion("TASK_PROGRESS not in", values, "taskProgress");
            return this;
        }

        public Criteria andTaskProgressBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TASK_PROGRESS between", value1, value2, "taskProgress");
            return this;
        }

        public Criteria andTaskProgressNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TASK_PROGRESS not between", value1, value2, "taskProgress");
            return this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("PROVINCE is null");
            return this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("PROVINCE is not null");
            return this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("PROVINCE =", value, "province");
            return this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("PROVINCE <>", value, "province");
            return this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("PROVINCE >", value, "province");
            return this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("PROVINCE >=", value, "province");
            return this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("PROVINCE <", value, "province");
            return this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("PROVINCE <=", value, "province");
            return this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("PROVINCE like", value, "province");
            return this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("PROVINCE not like", value, "province");
            return this;
        }

        public Criteria andProvinceIn(List values) {
            addCriterion("PROVINCE in", values, "province");
            return this;
        }

        public Criteria andProvinceNotIn(List values) {
            addCriterion("PROVINCE not in", values, "province");
            return this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("PROVINCE between", value1, value2, "province");
            return this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("PROVINCE not between", value1, value2, "province");
            return this;
        }

        public Criteria andCityIsNull() {
            addCriterion("CITY is null");
            return this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("CITY is not null");
            return this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("CITY =", value, "city");
            return this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("CITY <>", value, "city");
            return this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("CITY >", value, "city");
            return this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("CITY >=", value, "city");
            return this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("CITY <", value, "city");
            return this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("CITY <=", value, "city");
            return this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("CITY like", value, "city");
            return this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("CITY not like", value, "city");
            return this;
        }

        public Criteria andCityIn(List values) {
            addCriterion("CITY in", values, "city");
            return this;
        }

        public Criteria andCityNotIn(List values) {
            addCriterion("CITY not in", values, "city");
            return this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("CITY between", value1, value2, "city");
            return this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("CITY not between", value1, value2, "city");
            return this;
        }

        public Criteria andStreetIsNull() {
            addCriterion("STREET is null");
            return this;
        }

        public Criteria andStreetIsNotNull() {
            addCriterion("STREET is not null");
            return this;
        }

        public Criteria andStreetEqualTo(String value) {
            addCriterion("STREET =", value, "street");
            return this;
        }

        public Criteria andStreetNotEqualTo(String value) {
            addCriterion("STREET <>", value, "street");
            return this;
        }

        public Criteria andStreetGreaterThan(String value) {
            addCriterion("STREET >", value, "street");
            return this;
        }

        public Criteria andStreetGreaterThanOrEqualTo(String value) {
            addCriterion("STREET >=", value, "street");
            return this;
        }

        public Criteria andStreetLessThan(String value) {
            addCriterion("STREET <", value, "street");
            return this;
        }

        public Criteria andStreetLessThanOrEqualTo(String value) {
            addCriterion("STREET <=", value, "street");
            return this;
        }

        public Criteria andStreetLike(String value) {
            addCriterion("STREET like", value, "street");
            return this;
        }

        public Criteria andStreetNotLike(String value) {
            addCriterion("STREET not like", value, "street");
            return this;
        }

        public Criteria andStreetIn(List values) {
            addCriterion("STREET in", values, "street");
            return this;
        }

        public Criteria andStreetNotIn(List values) {
            addCriterion("STREET not in", values, "street");
            return this;
        }

        public Criteria andStreetBetween(String value1, String value2) {
            addCriterion("STREET between", value1, value2, "street");
            return this;
        }

        public Criteria andStreetNotBetween(String value1, String value2) {
            addCriterion("STREET not between", value1, value2, "street");
            return this;
        }

        public Criteria andIdCardFileSnIsNull() {
            addCriterion("ID_CARD_FILE_SN is null");
            return this;
        }

        public Criteria andIdCardFileSnIsNotNull() {
            addCriterion("ID_CARD_FILE_SN is not null");
            return this;
        }

        public Criteria andIdCardFileSnEqualTo(Long value) {
            addCriterion("ID_CARD_FILE_SN =", value, "idCardFileSn");
            return this;
        }

        public Criteria andIdCardFileSnNotEqualTo(Long value) {
            addCriterion("ID_CARD_FILE_SN <>", value, "idCardFileSn");
            return this;
        }

        public Criteria andIdCardFileSnGreaterThan(Long value) {
            addCriterion("ID_CARD_FILE_SN >", value, "idCardFileSn");
            return this;
        }

        public Criteria andIdCardFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ID_CARD_FILE_SN >=", value, "idCardFileSn");
            return this;
        }

        public Criteria andIdCardFileSnLessThan(Long value) {
            addCriterion("ID_CARD_FILE_SN <", value, "idCardFileSn");
            return this;
        }

        public Criteria andIdCardFileSnLessThanOrEqualTo(Long value) {
            addCriterion("ID_CARD_FILE_SN <=", value, "idCardFileSn");
            return this;
        }

        public Criteria andIdCardFileSnIn(List values) {
            addCriterion("ID_CARD_FILE_SN in", values, "idCardFileSn");
            return this;
        }

        public Criteria andIdCardFileSnNotIn(List values) {
            addCriterion("ID_CARD_FILE_SN not in", values, "idCardFileSn");
            return this;
        }

        public Criteria andIdCardFileSnBetween(Long value1, Long value2) {
            addCriterion("ID_CARD_FILE_SN between", value1, value2, "idCardFileSn");
            return this;
        }

        public Criteria andIdCardFileSnNotBetween(Long value1, Long value2) {
            addCriterion("ID_CARD_FILE_SN not between", value1, value2, "idCardFileSn");
            return this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("COMPANY_NAME is null");
            return this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("COMPANY_NAME is not null");
            return this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("COMPANY_NAME =", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("COMPANY_NAME <>", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("COMPANY_NAME >", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME >=", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("COMPANY_NAME <", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME <=", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("COMPANY_NAME like", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("COMPANY_NAME not like", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameIn(List values) {
            addCriterion("COMPANY_NAME in", values, "companyName");
            return this;
        }

        public Criteria andCompanyNameNotIn(List values) {
            addCriterion("COMPANY_NAME not in", values, "companyName");
            return this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME between", value1, value2, "companyName");
            return this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME not between", value1, value2, "companyName");
            return this;
        }

        public Criteria andKbisFileSnIsNull() {
            addCriterion("KBIS_FILE_SN is null");
            return this;
        }

        public Criteria andKbisFileSnIsNotNull() {
            addCriterion("KBIS_FILE_SN is not null");
            return this;
        }

        public Criteria andKbisFileSnEqualTo(Long value) {
            addCriterion("KBIS_FILE_SN =", value, "kbisFileSn");
            return this;
        }

        public Criteria andKbisFileSnNotEqualTo(Long value) {
            addCriterion("KBIS_FILE_SN <>", value, "kbisFileSn");
            return this;
        }

        public Criteria andKbisFileSnGreaterThan(Long value) {
            addCriterion("KBIS_FILE_SN >", value, "kbisFileSn");
            return this;
        }

        public Criteria andKbisFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("KBIS_FILE_SN >=", value, "kbisFileSn");
            return this;
        }

        public Criteria andKbisFileSnLessThan(Long value) {
            addCriterion("KBIS_FILE_SN <", value, "kbisFileSn");
            return this;
        }

        public Criteria andKbisFileSnLessThanOrEqualTo(Long value) {
            addCriterion("KBIS_FILE_SN <=", value, "kbisFileSn");
            return this;
        }

        public Criteria andKbisFileSnIn(List values) {
            addCriterion("KBIS_FILE_SN in", values, "kbisFileSn");
            return this;
        }

        public Criteria andKbisFileSnNotIn(List values) {
            addCriterion("KBIS_FILE_SN not in", values, "kbisFileSn");
            return this;
        }

        public Criteria andKbisFileSnBetween(Long value1, Long value2) {
            addCriterion("KBIS_FILE_SN between", value1, value2, "kbisFileSn");
            return this;
        }

        public Criteria andKbisFileSnNotBetween(Long value1, Long value2) {
            addCriterion("KBIS_FILE_SN not between", value1, value2, "kbisFileSn");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("STATUS in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("STATUS not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(List values) {
            addCriterion("REMARK in", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List values) {
            addCriterion("REMARK not in", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return this;
        }

        public Criteria andAdderSnIsNull() {
            addCriterion("ADDER_SN is null");
            return this;
        }

        public Criteria andAdderSnIsNotNull() {
            addCriterion("ADDER_SN is not null");
            return this;
        }

        public Criteria andAdderSnEqualTo(Long value) {
            addCriterion("ADDER_SN =", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotEqualTo(Long value) {
            addCriterion("ADDER_SN <>", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThan(Long value) {
            addCriterion("ADDER_SN >", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN >=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThan(Long value) {
            addCriterion("ADDER_SN <", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN <=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnIn(List values) {
            addCriterion("ADDER_SN in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotIn(List values) {
            addCriterion("ADDER_SN not in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN not between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderNameIsNull() {
            addCriterion("ADDER_NAME is null");
            return this;
        }

        public Criteria andAdderNameIsNotNull() {
            addCriterion("ADDER_NAME is not null");
            return this;
        }

        public Criteria andAdderNameEqualTo(String value) {
            addCriterion("ADDER_NAME =", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotEqualTo(String value) {
            addCriterion("ADDER_NAME <>", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThan(String value) {
            addCriterion("ADDER_NAME >", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME >=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThan(String value) {
            addCriterion("ADDER_NAME <", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME <=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLike(String value) {
            addCriterion("ADDER_NAME like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotLike(String value) {
            addCriterion("ADDER_NAME not like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameIn(List values) {
            addCriterion("ADDER_NAME in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameNotIn(List values) {
            addCriterion("ADDER_NAME not in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameBetween(String value1, String value2) {
            addCriterion("ADDER_NAME between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAdderNameNotBetween(String value1, String value2) {
            addCriterion("ADDER_NAME not between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeIn(List values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeNotIn(List values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return this;
        }

        public Criteria andUpdaterSnIsNull() {
            addCriterion("UPDATER_SN is null");
            return this;
        }

        public Criteria andUpdaterSnIsNotNull() {
            addCriterion("UPDATER_SN is not null");
            return this;
        }

        public Criteria andUpdaterSnEqualTo(Long value) {
            addCriterion("UPDATER_SN =", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotEqualTo(Long value) {
            addCriterion("UPDATER_SN <>", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThan(Long value) {
            addCriterion("UPDATER_SN >", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN >=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThan(Long value) {
            addCriterion("UPDATER_SN <", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN <=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnIn(List values) {
            addCriterion("UPDATER_SN in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotIn(List values) {
            addCriterion("UPDATER_SN not in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN not between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterNameIsNull() {
            addCriterion("UPDATER_NAME is null");
            return this;
        }

        public Criteria andUpdaterNameIsNotNull() {
            addCriterion("UPDATER_NAME is not null");
            return this;
        }

        public Criteria andUpdaterNameEqualTo(String value) {
            addCriterion("UPDATER_NAME =", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotEqualTo(String value) {
            addCriterion("UPDATER_NAME <>", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThan(String value) {
            addCriterion("UPDATER_NAME >", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME >=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThan(String value) {
            addCriterion("UPDATER_NAME <", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME <=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLike(String value) {
            addCriterion("UPDATER_NAME like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotLike(String value) {
            addCriterion("UPDATER_NAME not like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameIn(List values) {
            addCriterion("UPDATER_NAME in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotIn(List values) {
            addCriterion("UPDATER_NAME not in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME not between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andValidStartDateIsNull() {
            addCriterion("VALID_START_DATE is null");
            return this;
        }

        public Criteria andValidStartDateIsNotNull() {
            addCriterion("VALID_START_DATE is not null");
            return this;
        }

        public Criteria andValidStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("VALID_START_DATE =", value, "validStartDate");
            return this;
        }

        public Criteria andValidStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("VALID_START_DATE <>", value, "validStartDate");
            return this;
        }

        public Criteria andValidStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("VALID_START_DATE >", value, "validStartDate");
            return this;
        }

        public Criteria andValidStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("VALID_START_DATE >=", value, "validStartDate");
            return this;
        }

        public Criteria andValidStartDateLessThan(Date value) {
            addCriterionForJDBCDate("VALID_START_DATE <", value, "validStartDate");
            return this;
        }

        public Criteria andValidStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("VALID_START_DATE <=", value, "validStartDate");
            return this;
        }

        public Criteria andValidStartDateIn(List values) {
            addCriterionForJDBCDate("VALID_START_DATE in", values, "validStartDate");
            return this;
        }

        public Criteria andValidStartDateNotIn(List values) {
            addCriterionForJDBCDate("VALID_START_DATE not in", values, "validStartDate");
            return this;
        }

        public Criteria andValidStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("VALID_START_DATE between", value1, value2, "validStartDate");
            return this;
        }

        public Criteria andValidStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("VALID_START_DATE not between", value1, value2, "validStartDate");
            return this;
        }

        public Criteria andValidEndDateIsNull() {
            addCriterion("VALID_END_DATE is null");
            return this;
        }

        public Criteria andValidEndDateIsNotNull() {
            addCriterion("VALID_END_DATE is not null");
            return this;
        }

        public Criteria andValidEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("VALID_END_DATE =", value, "validEndDate");
            return this;
        }

        public Criteria andValidEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("VALID_END_DATE <>", value, "validEndDate");
            return this;
        }

        public Criteria andValidEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("VALID_END_DATE >", value, "validEndDate");
            return this;
        }

        public Criteria andValidEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("VALID_END_DATE >=", value, "validEndDate");
            return this;
        }

        public Criteria andValidEndDateLessThan(Date value) {
            addCriterionForJDBCDate("VALID_END_DATE <", value, "validEndDate");
            return this;
        }

        public Criteria andValidEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("VALID_END_DATE <=", value, "validEndDate");
            return this;
        }

        public Criteria andValidEndDateIn(List values) {
            addCriterionForJDBCDate("VALID_END_DATE in", values, "validEndDate");
            return this;
        }

        public Criteria andValidEndDateNotIn(List values) {
            addCriterionForJDBCDate("VALID_END_DATE not in", values, "validEndDate");
            return this;
        }

        public Criteria andValidEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("VALID_END_DATE between", value1, value2, "validEndDate");
            return this;
        }

        public Criteria andValidEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("VALID_END_DATE not between", value1, value2, "validEndDate");
            return this;
        }

        public Criteria andContractFileSnIsNull() {
            addCriterion("CONTRACT_FILE_SN is null");
            return this;
        }

        public Criteria andContractFileSnIsNotNull() {
            addCriterion("CONTRACT_FILE_SN is not null");
            return this;
        }

        public Criteria andContractFileSnEqualTo(Long value) {
            addCriterion("CONTRACT_FILE_SN =", value, "contractFileSn");
            return this;
        }

        public Criteria andContractFileSnNotEqualTo(Long value) {
            addCriterion("CONTRACT_FILE_SN <>", value, "contractFileSn");
            return this;
        }

        public Criteria andContractFileSnGreaterThan(Long value) {
            addCriterion("CONTRACT_FILE_SN >", value, "contractFileSn");
            return this;
        }

        public Criteria andContractFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("CONTRACT_FILE_SN >=", value, "contractFileSn");
            return this;
        }

        public Criteria andContractFileSnLessThan(Long value) {
            addCriterion("CONTRACT_FILE_SN <", value, "contractFileSn");
            return this;
        }

        public Criteria andContractFileSnLessThanOrEqualTo(Long value) {
            addCriterion("CONTRACT_FILE_SN <=", value, "contractFileSn");
            return this;
        }

        public Criteria andContractFileSnIn(List values) {
            addCriterion("CONTRACT_FILE_SN in", values, "contractFileSn");
            return this;
        }

        public Criteria andContractFileSnNotIn(List values) {
            addCriterion("CONTRACT_FILE_SN not in", values, "contractFileSn");
            return this;
        }

        public Criteria andContractFileSnBetween(Long value1, Long value2) {
            addCriterion("CONTRACT_FILE_SN between", value1, value2, "contractFileSn");
            return this;
        }

        public Criteria andContractFileSnNotBetween(Long value1, Long value2) {
            addCriterion("CONTRACT_FILE_SN not between", value1, value2, "contractFileSn");
            return this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("ID_CARD is null");
            return this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("ID_CARD is not null");
            return this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("ID_CARD =", value, "idCard");
            return this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("ID_CARD <>", value, "idCard");
            return this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("ID_CARD >", value, "idCard");
            return this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("ID_CARD >=", value, "idCard");
            return this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("ID_CARD <", value, "idCard");
            return this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("ID_CARD <=", value, "idCard");
            return this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("ID_CARD like", value, "idCard");
            return this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("ID_CARD not like", value, "idCard");
            return this;
        }

        public Criteria andIdCardIn(List values) {
            addCriterion("ID_CARD in", values, "idCard");
            return this;
        }

        public Criteria andIdCardNotIn(List values) {
            addCriterion("ID_CARD not in", values, "idCard");
            return this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("ID_CARD between", value1, value2, "idCard");
            return this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("ID_CARD not between", value1, value2, "idCard");
            return this;
        }

        public Criteria andWxIdIsNull() {
            addCriterion("WX_ID is null");
            return this;
        }

        public Criteria andWxIdIsNotNull() {
            addCriterion("WX_ID is not null");
            return this;
        }

        public Criteria andWxIdEqualTo(String value) {
            addCriterion("WX_ID =", value, "wxId");
            return this;
        }

        public Criteria andWxIdNotEqualTo(String value) {
            addCriterion("WX_ID <>", value, "wxId");
            return this;
        }

        public Criteria andWxIdGreaterThan(String value) {
            addCriterion("WX_ID >", value, "wxId");
            return this;
        }

        public Criteria andWxIdGreaterThanOrEqualTo(String value) {
            addCriterion("WX_ID >=", value, "wxId");
            return this;
        }

        public Criteria andWxIdLessThan(String value) {
            addCriterion("WX_ID <", value, "wxId");
            return this;
        }

        public Criteria andWxIdLessThanOrEqualTo(String value) {
            addCriterion("WX_ID <=", value, "wxId");
            return this;
        }

        public Criteria andWxIdLike(String value) {
            addCriterion("WX_ID like", value, "wxId");
            return this;
        }

        public Criteria andWxIdNotLike(String value) {
            addCriterion("WX_ID not like", value, "wxId");
            return this;
        }

        public Criteria andWxIdIn(List values) {
            addCriterion("WX_ID in", values, "wxId");
            return this;
        }

        public Criteria andWxIdNotIn(List values) {
            addCriterion("WX_ID not in", values, "wxId");
            return this;
        }

        public Criteria andWxIdBetween(String value1, String value2) {
            addCriterion("WX_ID between", value1, value2, "wxId");
            return this;
        }

        public Criteria andWxIdNotBetween(String value1, String value2) {
            addCriterion("WX_ID not between", value1, value2, "wxId");
            return this;
        }

        public Criteria andPartnerTypeIsNull() {
            addCriterion("PARTNER_TYPE is null");
            return this;
        }

        public Criteria andPartnerTypeIsNotNull() {
            addCriterion("PARTNER_TYPE is not null");
            return this;
        }

        public Criteria andPartnerTypeEqualTo(Integer value) {
            addCriterion("PARTNER_TYPE =", value, "partnerType");
            return this;
        }

        public Criteria andPartnerTypeNotEqualTo(Integer value) {
            addCriterion("PARTNER_TYPE <>", value, "partnerType");
            return this;
        }

        public Criteria andPartnerTypeGreaterThan(Integer value) {
            addCriterion("PARTNER_TYPE >", value, "partnerType");
            return this;
        }

        public Criteria andPartnerTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PARTNER_TYPE >=", value, "partnerType");
            return this;
        }

        public Criteria andPartnerTypeLessThan(Integer value) {
            addCriterion("PARTNER_TYPE <", value, "partnerType");
            return this;
        }

        public Criteria andPartnerTypeLessThanOrEqualTo(Integer value) {
            addCriterion("PARTNER_TYPE <=", value, "partnerType");
            return this;
        }

        public Criteria andPartnerTypeIn(List values) {
            addCriterion("PARTNER_TYPE in", values, "partnerType");
            return this;
        }

        public Criteria andPartnerTypeNotIn(List values) {
            addCriterion("PARTNER_TYPE not in", values, "partnerType");
            return this;
        }

        public Criteria andPartnerTypeBetween(Integer value1, Integer value2) {
            addCriterion("PARTNER_TYPE between", value1, value2, "partnerType");
            return this;
        }

        public Criteria andPartnerTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("PARTNER_TYPE not between", value1, value2, "partnerType");
            return this;
        }

        public Criteria andRegChannelTypeIsNull() {
            addCriterion("REG_CHANNEL_TYPE is null");
            return this;
        }

        public Criteria andRegChannelTypeIsNotNull() {
            addCriterion("REG_CHANNEL_TYPE is not null");
            return this;
        }

        public Criteria andRegChannelTypeEqualTo(Integer value) {
            addCriterion("REG_CHANNEL_TYPE =", value, "regChannelType");
            return this;
        }

        public Criteria andRegChannelTypeNotEqualTo(Integer value) {
            addCriterion("REG_CHANNEL_TYPE <>", value, "regChannelType");
            return this;
        }

        public Criteria andRegChannelTypeGreaterThan(Integer value) {
            addCriterion("REG_CHANNEL_TYPE >", value, "regChannelType");
            return this;
        }

        public Criteria andRegChannelTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("REG_CHANNEL_TYPE >=", value, "regChannelType");
            return this;
        }

        public Criteria andRegChannelTypeLessThan(Integer value) {
            addCriterion("REG_CHANNEL_TYPE <", value, "regChannelType");
            return this;
        }

        public Criteria andRegChannelTypeLessThanOrEqualTo(Integer value) {
            addCriterion("REG_CHANNEL_TYPE <=", value, "regChannelType");
            return this;
        }

        public Criteria andRegChannelTypeIn(List values) {
            addCriterion("REG_CHANNEL_TYPE in", values, "regChannelType");
            return this;
        }

        public Criteria andRegChannelTypeNotIn(List values) {
            addCriterion("REG_CHANNEL_TYPE not in", values, "regChannelType");
            return this;
        }

        public Criteria andRegChannelTypeBetween(Integer value1, Integer value2) {
            addCriterion("REG_CHANNEL_TYPE between", value1, value2, "regChannelType");
            return this;
        }

        public Criteria andRegChannelTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("REG_CHANNEL_TYPE not between", value1, value2, "regChannelType");
            return this;
        }

        public Criteria andParentSnIsNull() {
            addCriterion("PARENT_SN is null");
            return this;
        }

        public Criteria andParentSnIsNotNull() {
            addCriterion("PARENT_SN is not null");
            return this;
        }

        public Criteria andParentSnEqualTo(Long value) {
            addCriterion("PARENT_SN =", value, "parentSn");
            return this;
        }

        public Criteria andParentSnNotEqualTo(Long value) {
            addCriterion("PARENT_SN <>", value, "parentSn");
            return this;
        }

        public Criteria andParentSnGreaterThan(Long value) {
            addCriterion("PARENT_SN >", value, "parentSn");
            return this;
        }

        public Criteria andParentSnGreaterThanOrEqualTo(Long value) {
            addCriterion("PARENT_SN >=", value, "parentSn");
            return this;
        }

        public Criteria andParentSnLessThan(Long value) {
            addCriterion("PARENT_SN <", value, "parentSn");
            return this;
        }

        public Criteria andParentSnLessThanOrEqualTo(Long value) {
            addCriterion("PARENT_SN <=", value, "parentSn");
            return this;
        }

        public Criteria andParentSnIn(List values) {
            addCriterion("PARENT_SN in", values, "parentSn");
            return this;
        }

        public Criteria andParentSnNotIn(List values) {
            addCriterion("PARENT_SN not in", values, "parentSn");
            return this;
        }

        public Criteria andParentSnBetween(Long value1, Long value2) {
            addCriterion("PARENT_SN between", value1, value2, "parentSn");
            return this;
        }

        public Criteria andParentSnNotBetween(Long value1, Long value2) {
            addCriterion("PARENT_SN not between", value1, value2, "parentSn");
            return this;
        }

        public Criteria andPayZfbIdIsNull() {
            addCriterion("PAY_ZFB_ID is null");
            return this;
        }

        public Criteria andPayZfbIdIsNotNull() {
            addCriterion("PAY_ZFB_ID is not null");
            return this;
        }

        public Criteria andPayZfbIdEqualTo(String value) {
            addCriterion("PAY_ZFB_ID =", value, "payZfbId");
            return this;
        }

        public Criteria andPayZfbIdNotEqualTo(String value) {
            addCriterion("PAY_ZFB_ID <>", value, "payZfbId");
            return this;
        }

        public Criteria andPayZfbIdGreaterThan(String value) {
            addCriterion("PAY_ZFB_ID >", value, "payZfbId");
            return this;
        }

        public Criteria andPayZfbIdGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_ZFB_ID >=", value, "payZfbId");
            return this;
        }

        public Criteria andPayZfbIdLessThan(String value) {
            addCriterion("PAY_ZFB_ID <", value, "payZfbId");
            return this;
        }

        public Criteria andPayZfbIdLessThanOrEqualTo(String value) {
            addCriterion("PAY_ZFB_ID <=", value, "payZfbId");
            return this;
        }

        public Criteria andPayZfbIdLike(String value) {
            addCriterion("PAY_ZFB_ID like", value, "payZfbId");
            return this;
        }

        public Criteria andPayZfbIdNotLike(String value) {
            addCriterion("PAY_ZFB_ID not like", value, "payZfbId");
            return this;
        }

        public Criteria andPayZfbIdIn(List values) {
            addCriterion("PAY_ZFB_ID in", values, "payZfbId");
            return this;
        }

        public Criteria andPayZfbIdNotIn(List values) {
            addCriterion("PAY_ZFB_ID not in", values, "payZfbId");
            return this;
        }

        public Criteria andPayZfbIdBetween(String value1, String value2) {
            addCriterion("PAY_ZFB_ID between", value1, value2, "payZfbId");
            return this;
        }

        public Criteria andPayZfbIdNotBetween(String value1, String value2) {
            addCriterion("PAY_ZFB_ID not between", value1, value2, "payZfbId");
            return this;
        }

        public Criteria andPayYlIdIsNull() {
            addCriterion("PAY_yL_ID is null");
            return this;
        }

        public Criteria andPayYlIdIsNotNull() {
            addCriterion("PAY_yL_ID is not null");
            return this;
        }

        public Criteria andPayYlIdEqualTo(String value) {
            addCriterion("PAY_yL_ID =", value, "payYlId");
            return this;
        }

        public Criteria andPayYlIdNotEqualTo(String value) {
            addCriterion("PAY_yL_ID <>", value, "payYlId");
            return this;
        }

        public Criteria andPayYlIdGreaterThan(String value) {
            addCriterion("PAY_yL_ID >", value, "payYlId");
            return this;
        }

        public Criteria andPayYlIdGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_yL_ID >=", value, "payYlId");
            return this;
        }

        public Criteria andPayYlIdLessThan(String value) {
            addCriterion("PAY_yL_ID <", value, "payYlId");
            return this;
        }

        public Criteria andPayYlIdLessThanOrEqualTo(String value) {
            addCriterion("PAY_yL_ID <=", value, "payYlId");
            return this;
        }

        public Criteria andPayYlIdLike(String value) {
            addCriterion("PAY_yL_ID like", value, "payYlId");
            return this;
        }

        public Criteria andPayYlIdNotLike(String value) {
            addCriterion("PAY_yL_ID not like", value, "payYlId");
            return this;
        }

        public Criteria andPayYlIdIn(List values) {
            addCriterion("PAY_yL_ID in", values, "payYlId");
            return this;
        }

        public Criteria andPayYlIdNotIn(List values) {
            addCriterion("PAY_yL_ID not in", values, "payYlId");
            return this;
        }

        public Criteria andPayYlIdBetween(String value1, String value2) {
            addCriterion("PAY_yL_ID between", value1, value2, "payYlId");
            return this;
        }

        public Criteria andPayYlIdNotBetween(String value1, String value2) {
            addCriterion("PAY_yL_ID not between", value1, value2, "payYlId");
            return this;
        }

        public Criteria andPayWxIdIsNull() {
            addCriterion("PAY_WX_ID is null");
            return this;
        }

        public Criteria andPayWxIdIsNotNull() {
            addCriterion("PAY_WX_ID is not null");
            return this;
        }

        public Criteria andPayWxIdEqualTo(String value) {
            addCriterion("PAY_WX_ID =", value, "payWxId");
            return this;
        }

        public Criteria andPayWxIdNotEqualTo(String value) {
            addCriterion("PAY_WX_ID <>", value, "payWxId");
            return this;
        }

        public Criteria andPayWxIdGreaterThan(String value) {
            addCriterion("PAY_WX_ID >", value, "payWxId");
            return this;
        }

        public Criteria andPayWxIdGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_WX_ID >=", value, "payWxId");
            return this;
        }

        public Criteria andPayWxIdLessThan(String value) {
            addCriterion("PAY_WX_ID <", value, "payWxId");
            return this;
        }

        public Criteria andPayWxIdLessThanOrEqualTo(String value) {
            addCriterion("PAY_WX_ID <=", value, "payWxId");
            return this;
        }

        public Criteria andPayWxIdLike(String value) {
            addCriterion("PAY_WX_ID like", value, "payWxId");
            return this;
        }

        public Criteria andPayWxIdNotLike(String value) {
            addCriterion("PAY_WX_ID not like", value, "payWxId");
            return this;
        }

        public Criteria andPayWxIdIn(List values) {
            addCriterion("PAY_WX_ID in", values, "payWxId");
            return this;
        }

        public Criteria andPayWxIdNotIn(List values) {
            addCriterion("PAY_WX_ID not in", values, "payWxId");
            return this;
        }

        public Criteria andPayWxIdBetween(String value1, String value2) {
            addCriterion("PAY_WX_ID between", value1, value2, "payWxId");
            return this;
        }

        public Criteria andPayWxIdNotBetween(String value1, String value2) {
            addCriterion("PAY_WX_ID not between", value1, value2, "payWxId");
            return this;
        }
    }
}