package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "biz_agent_user_product", Class = BizAgentUserProduct.class)
public class BizAgentUserProduct<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_product.SN
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_product.USER_ID
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    @Column
    private Long userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_product.PRODUCT_ID
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    @Column
    private Long productId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_product.ADDER_SN
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_product.ADDER_NAME
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_product.ADD_TIME
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_product.UPDATER_SN
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_product.UPDATER_NAME
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user_product.UPDATE_TIME
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_product.SN
     *
     * @return the value of biz_agent_user_product.SN
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_product.SN
     *
     * @param sn the value for biz_agent_user_product.SN
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_product.USER_ID
     *
     * @return the value of biz_agent_user_product.USER_ID
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_product.USER_ID
     *
     * @param userId the value for biz_agent_user_product.USER_ID
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_product.PRODUCT_ID
     *
     * @return the value of biz_agent_user_product.PRODUCT_ID
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_product.PRODUCT_ID
     *
     * @param productId the value for biz_agent_user_product.PRODUCT_ID
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_product.ADDER_SN
     *
     * @return the value of biz_agent_user_product.ADDER_SN
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_product.ADDER_SN
     *
     * @param adderSn the value for biz_agent_user_product.ADDER_SN
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_product.ADDER_NAME
     *
     * @return the value of biz_agent_user_product.ADDER_NAME
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_product.ADDER_NAME
     *
     * @param adderName the value for biz_agent_user_product.ADDER_NAME
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_product.ADD_TIME
     *
     * @return the value of biz_agent_user_product.ADD_TIME
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_product.ADD_TIME
     *
     * @param addTime the value for biz_agent_user_product.ADD_TIME
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_product.UPDATER_SN
     *
     * @return the value of biz_agent_user_product.UPDATER_SN
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_product.UPDATER_SN
     *
     * @param updaterSn the value for biz_agent_user_product.UPDATER_SN
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_product.UPDATER_NAME
     *
     * @return the value of biz_agent_user_product.UPDATER_NAME
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_product.UPDATER_NAME
     *
     * @param updaterName the value for biz_agent_user_product.UPDATER_NAME
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user_product.UPDATE_TIME
     *
     * @return the value of biz_agent_user_product.UPDATE_TIME
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user_product.UPDATE_TIME
     *
     * @param updateTime the value for biz_agent_user_product.UPDATE_TIME
     *
     * @ibatorgenerated Mon May 23 20:11:09 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}