package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "biz_agent_resource", Class = BizAgentResource.class)
public class BizAgentResourceCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    public BizAgentResourceCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    public BizAgentResourceCriteria(BizAgentResourceCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    public BizAgentResourceCriteria(Object record, BizAgentResourceCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table biz_agent_resource
     *
     * @ibatorgenerated Mon Aug 08 17:32:24 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSnIsNull() {
            addCriterion("SN is null");
            return this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("SN is not null");
            return this;
        }

        public Criteria andSnEqualTo(Long value) {
            addCriterion("SN =", value, "sn");
            return this;
        }

        public Criteria andSnNotEqualTo(Long value) {
            addCriterion("SN <>", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThan(Long value) {
            addCriterion("SN >", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SN >=", value, "sn");
            return this;
        }

        public Criteria andSnLessThan(Long value) {
            addCriterion("SN <", value, "sn");
            return this;
        }

        public Criteria andSnLessThanOrEqualTo(Long value) {
            addCriterion("SN <=", value, "sn");
            return this;
        }

        public Criteria andSnIn(List values) {
            addCriterion("SN in", values, "sn");
            return this;
        }

        public Criteria andSnNotIn(List values) {
            addCriterion("SN not in", values, "sn");
            return this;
        }

        public Criteria andSnBetween(Long value1, Long value2) {
            addCriterion("SN between", value1, value2, "sn");
            return this;
        }

        public Criteria andSnNotBetween(Long value1, Long value2) {
            addCriterion("SN not between", value1, value2, "sn");
            return this;
        }

        public Criteria andResourceNameIsNull() {
            addCriterion("RESOURCE_NAME is null");
            return this;
        }

        public Criteria andResourceNameIsNotNull() {
            addCriterion("RESOURCE_NAME is not null");
            return this;
        }

        public Criteria andResourceNameEqualTo(String value) {
            addCriterion("RESOURCE_NAME =", value, "resourceName");
            return this;
        }

        public Criteria andResourceNameNotEqualTo(String value) {
            addCriterion("RESOURCE_NAME <>", value, "resourceName");
            return this;
        }

        public Criteria andResourceNameGreaterThan(String value) {
            addCriterion("RESOURCE_NAME >", value, "resourceName");
            return this;
        }

        public Criteria andResourceNameGreaterThanOrEqualTo(String value) {
            addCriterion("RESOURCE_NAME >=", value, "resourceName");
            return this;
        }

        public Criteria andResourceNameLessThan(String value) {
            addCriterion("RESOURCE_NAME <", value, "resourceName");
            return this;
        }

        public Criteria andResourceNameLessThanOrEqualTo(String value) {
            addCriterion("RESOURCE_NAME <=", value, "resourceName");
            return this;
        }

        public Criteria andResourceNameLike(String value) {
            addCriterion("RESOURCE_NAME like", value, "resourceName");
            return this;
        }

        public Criteria andResourceNameNotLike(String value) {
            addCriterion("RESOURCE_NAME not like", value, "resourceName");
            return this;
        }

        public Criteria andResourceNameIn(List values) {
            addCriterion("RESOURCE_NAME in", values, "resourceName");
            return this;
        }

        public Criteria andResourceNameNotIn(List values) {
            addCriterion("RESOURCE_NAME not in", values, "resourceName");
            return this;
        }

        public Criteria andResourceNameBetween(String value1, String value2) {
            addCriterion("RESOURCE_NAME between", value1, value2, "resourceName");
            return this;
        }

        public Criteria andResourceNameNotBetween(String value1, String value2) {
            addCriterion("RESOURCE_NAME not between", value1, value2, "resourceName");
            return this;
        }

        public Criteria andResourceParentIdIsNull() {
            addCriterion("RESOURCE_PARENT_ID is null");
            return this;
        }

        public Criteria andResourceParentIdIsNotNull() {
            addCriterion("RESOURCE_PARENT_ID is not null");
            return this;
        }

        public Criteria andResourceParentIdEqualTo(Long value) {
            addCriterion("RESOURCE_PARENT_ID =", value, "resourceParentId");
            return this;
        }

        public Criteria andResourceParentIdNotEqualTo(Long value) {
            addCriterion("RESOURCE_PARENT_ID <>", value, "resourceParentId");
            return this;
        }

        public Criteria andResourceParentIdGreaterThan(Long value) {
            addCriterion("RESOURCE_PARENT_ID >", value, "resourceParentId");
            return this;
        }

        public Criteria andResourceParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("RESOURCE_PARENT_ID >=", value, "resourceParentId");
            return this;
        }

        public Criteria andResourceParentIdLessThan(Long value) {
            addCriterion("RESOURCE_PARENT_ID <", value, "resourceParentId");
            return this;
        }

        public Criteria andResourceParentIdLessThanOrEqualTo(Long value) {
            addCriterion("RESOURCE_PARENT_ID <=", value, "resourceParentId");
            return this;
        }

        public Criteria andResourceParentIdIn(List values) {
            addCriterion("RESOURCE_PARENT_ID in", values, "resourceParentId");
            return this;
        }

        public Criteria andResourceParentIdNotIn(List values) {
            addCriterion("RESOURCE_PARENT_ID not in", values, "resourceParentId");
            return this;
        }

        public Criteria andResourceParentIdBetween(Long value1, Long value2) {
            addCriterion("RESOURCE_PARENT_ID between", value1, value2, "resourceParentId");
            return this;
        }

        public Criteria andResourceParentIdNotBetween(Long value1, Long value2) {
            addCriterion("RESOURCE_PARENT_ID not between", value1, value2, "resourceParentId");
            return this;
        }

        public Criteria andResourceTypeIsNull() {
            addCriterion("RESOURCE_TYPE is null");
            return this;
        }

        public Criteria andResourceTypeIsNotNull() {
            addCriterion("RESOURCE_TYPE is not null");
            return this;
        }

        public Criteria andResourceTypeEqualTo(Integer value) {
            addCriterion("RESOURCE_TYPE =", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeNotEqualTo(Integer value) {
            addCriterion("RESOURCE_TYPE <>", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeGreaterThan(Integer value) {
            addCriterion("RESOURCE_TYPE >", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("RESOURCE_TYPE >=", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeLessThan(Integer value) {
            addCriterion("RESOURCE_TYPE <", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeLessThanOrEqualTo(Integer value) {
            addCriterion("RESOURCE_TYPE <=", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeIn(List values) {
            addCriterion("RESOURCE_TYPE in", values, "resourceType");
            return this;
        }

        public Criteria andResourceTypeNotIn(List values) {
            addCriterion("RESOURCE_TYPE not in", values, "resourceType");
            return this;
        }

        public Criteria andResourceTypeBetween(Integer value1, Integer value2) {
            addCriterion("RESOURCE_TYPE between", value1, value2, "resourceType");
            return this;
        }

        public Criteria andResourceTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("RESOURCE_TYPE not between", value1, value2, "resourceType");
            return this;
        }

        public Criteria andResourceInterfaceIsNull() {
            addCriterion("RESOURCE_INTERFACE is null");
            return this;
        }

        public Criteria andResourceInterfaceIsNotNull() {
            addCriterion("RESOURCE_INTERFACE is not null");
            return this;
        }

        public Criteria andResourceInterfaceEqualTo(String value) {
            addCriterion("RESOURCE_INTERFACE =", value, "resourceInterface");
            return this;
        }

        public Criteria andResourceInterfaceNotEqualTo(String value) {
            addCriterion("RESOURCE_INTERFACE <>", value, "resourceInterface");
            return this;
        }

        public Criteria andResourceInterfaceGreaterThan(String value) {
            addCriterion("RESOURCE_INTERFACE >", value, "resourceInterface");
            return this;
        }

        public Criteria andResourceInterfaceGreaterThanOrEqualTo(String value) {
            addCriterion("RESOURCE_INTERFACE >=", value, "resourceInterface");
            return this;
        }

        public Criteria andResourceInterfaceLessThan(String value) {
            addCriterion("RESOURCE_INTERFACE <", value, "resourceInterface");
            return this;
        }

        public Criteria andResourceInterfaceLessThanOrEqualTo(String value) {
            addCriterion("RESOURCE_INTERFACE <=", value, "resourceInterface");
            return this;
        }

        public Criteria andResourceInterfaceLike(String value) {
            addCriterion("RESOURCE_INTERFACE like", value, "resourceInterface");
            return this;
        }

        public Criteria andResourceInterfaceNotLike(String value) {
            addCriterion("RESOURCE_INTERFACE not like", value, "resourceInterface");
            return this;
        }

        public Criteria andResourceInterfaceIn(List values) {
            addCriterion("RESOURCE_INTERFACE in", values, "resourceInterface");
            return this;
        }

        public Criteria andResourceInterfaceNotIn(List values) {
            addCriterion("RESOURCE_INTERFACE not in", values, "resourceInterface");
            return this;
        }

        public Criteria andResourceInterfaceBetween(String value1, String value2) {
            addCriterion("RESOURCE_INTERFACE between", value1, value2, "resourceInterface");
            return this;
        }

        public Criteria andResourceInterfaceNotBetween(String value1, String value2) {
            addCriterion("RESOURCE_INTERFACE not between", value1, value2, "resourceInterface");
            return this;
        }

        public Criteria andResourceDisplayIsNull() {
            addCriterion("RESOURCE_DISPLAY is null");
            return this;
        }

        public Criteria andResourceDisplayIsNotNull() {
            addCriterion("RESOURCE_DISPLAY is not null");
            return this;
        }

        public Criteria andResourceDisplayEqualTo(String value) {
            addCriterion("RESOURCE_DISPLAY =", value, "resourceDisplay");
            return this;
        }

        public Criteria andResourceDisplayNotEqualTo(String value) {
            addCriterion("RESOURCE_DISPLAY <>", value, "resourceDisplay");
            return this;
        }

        public Criteria andResourceDisplayGreaterThan(String value) {
            addCriterion("RESOURCE_DISPLAY >", value, "resourceDisplay");
            return this;
        }

        public Criteria andResourceDisplayGreaterThanOrEqualTo(String value) {
            addCriterion("RESOURCE_DISPLAY >=", value, "resourceDisplay");
            return this;
        }

        public Criteria andResourceDisplayLessThan(String value) {
            addCriterion("RESOURCE_DISPLAY <", value, "resourceDisplay");
            return this;
        }

        public Criteria andResourceDisplayLessThanOrEqualTo(String value) {
            addCriterion("RESOURCE_DISPLAY <=", value, "resourceDisplay");
            return this;
        }

        public Criteria andResourceDisplayLike(String value) {
            addCriterion("RESOURCE_DISPLAY like", value, "resourceDisplay");
            return this;
        }

        public Criteria andResourceDisplayNotLike(String value) {
            addCriterion("RESOURCE_DISPLAY not like", value, "resourceDisplay");
            return this;
        }

        public Criteria andResourceDisplayIn(List values) {
            addCriterion("RESOURCE_DISPLAY in", values, "resourceDisplay");
            return this;
        }

        public Criteria andResourceDisplayNotIn(List values) {
            addCriterion("RESOURCE_DISPLAY not in", values, "resourceDisplay");
            return this;
        }

        public Criteria andResourceDisplayBetween(String value1, String value2) {
            addCriterion("RESOURCE_DISPLAY between", value1, value2, "resourceDisplay");
            return this;
        }

        public Criteria andResourceDisplayNotBetween(String value1, String value2) {
            addCriterion("RESOURCE_DISPLAY not between", value1, value2, "resourceDisplay");
            return this;
        }

        public Criteria andActiveIsNull() {
            addCriterion("ACTIVE is null");
            return this;
        }

        public Criteria andActiveIsNotNull() {
            addCriterion("ACTIVE is not null");
            return this;
        }

        public Criteria andActiveEqualTo(Integer value) {
            addCriterion("ACTIVE =", value, "active");
            return this;
        }

        public Criteria andActiveNotEqualTo(Integer value) {
            addCriterion("ACTIVE <>", value, "active");
            return this;
        }

        public Criteria andActiveGreaterThan(Integer value) {
            addCriterion("ACTIVE >", value, "active");
            return this;
        }

        public Criteria andActiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACTIVE >=", value, "active");
            return this;
        }

        public Criteria andActiveLessThan(Integer value) {
            addCriterion("ACTIVE <", value, "active");
            return this;
        }

        public Criteria andActiveLessThanOrEqualTo(Integer value) {
            addCriterion("ACTIVE <=", value, "active");
            return this;
        }

        public Criteria andActiveIn(List values) {
            addCriterion("ACTIVE in", values, "active");
            return this;
        }

        public Criteria andActiveNotIn(List values) {
            addCriterion("ACTIVE not in", values, "active");
            return this;
        }

        public Criteria andActiveBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVE between", value1, value2, "active");
            return this;
        }

        public Criteria andActiveNotBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVE not between", value1, value2, "active");
            return this;
        }

        public Criteria andResourceOrderIsNull() {
            addCriterion("RESOURCE_ORDER is null");
            return this;
        }

        public Criteria andResourceOrderIsNotNull() {
            addCriterion("RESOURCE_ORDER is not null");
            return this;
        }

        public Criteria andResourceOrderEqualTo(Integer value) {
            addCriterion("RESOURCE_ORDER =", value, "resourceOrder");
            return this;
        }

        public Criteria andResourceOrderNotEqualTo(Integer value) {
            addCriterion("RESOURCE_ORDER <>", value, "resourceOrder");
            return this;
        }

        public Criteria andResourceOrderGreaterThan(Integer value) {
            addCriterion("RESOURCE_ORDER >", value, "resourceOrder");
            return this;
        }

        public Criteria andResourceOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("RESOURCE_ORDER >=", value, "resourceOrder");
            return this;
        }

        public Criteria andResourceOrderLessThan(Integer value) {
            addCriterion("RESOURCE_ORDER <", value, "resourceOrder");
            return this;
        }

        public Criteria andResourceOrderLessThanOrEqualTo(Integer value) {
            addCriterion("RESOURCE_ORDER <=", value, "resourceOrder");
            return this;
        }

        public Criteria andResourceOrderIn(List values) {
            addCriterion("RESOURCE_ORDER in", values, "resourceOrder");
            return this;
        }

        public Criteria andResourceOrderNotIn(List values) {
            addCriterion("RESOURCE_ORDER not in", values, "resourceOrder");
            return this;
        }

        public Criteria andResourceOrderBetween(Integer value1, Integer value2) {
            addCriterion("RESOURCE_ORDER between", value1, value2, "resourceOrder");
            return this;
        }

        public Criteria andResourceOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("RESOURCE_ORDER not between", value1, value2, "resourceOrder");
            return this;
        }

        public Criteria andAttachmentIsNull() {
            addCriterion("ATTACHMENT is null");
            return this;
        }

        public Criteria andAttachmentIsNotNull() {
            addCriterion("ATTACHMENT is not null");
            return this;
        }

        public Criteria andAttachmentEqualTo(String value) {
            addCriterion("ATTACHMENT =", value, "attachment");
            return this;
        }

        public Criteria andAttachmentNotEqualTo(String value) {
            addCriterion("ATTACHMENT <>", value, "attachment");
            return this;
        }

        public Criteria andAttachmentGreaterThan(String value) {
            addCriterion("ATTACHMENT >", value, "attachment");
            return this;
        }

        public Criteria andAttachmentGreaterThanOrEqualTo(String value) {
            addCriterion("ATTACHMENT >=", value, "attachment");
            return this;
        }

        public Criteria andAttachmentLessThan(String value) {
            addCriterion("ATTACHMENT <", value, "attachment");
            return this;
        }

        public Criteria andAttachmentLessThanOrEqualTo(String value) {
            addCriterion("ATTACHMENT <=", value, "attachment");
            return this;
        }

        public Criteria andAttachmentLike(String value) {
            addCriterion("ATTACHMENT like", value, "attachment");
            return this;
        }

        public Criteria andAttachmentNotLike(String value) {
            addCriterion("ATTACHMENT not like", value, "attachment");
            return this;
        }

        public Criteria andAttachmentIn(List values) {
            addCriterion("ATTACHMENT in", values, "attachment");
            return this;
        }

        public Criteria andAttachmentNotIn(List values) {
            addCriterion("ATTACHMENT not in", values, "attachment");
            return this;
        }

        public Criteria andAttachmentBetween(String value1, String value2) {
            addCriterion("ATTACHMENT between", value1, value2, "attachment");
            return this;
        }

        public Criteria andAttachmentNotBetween(String value1, String value2) {
            addCriterion("ATTACHMENT not between", value1, value2, "attachment");
            return this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return this;
        }

        public Criteria andDescriptionIn(List values) {
            addCriterion("DESCRIPTION in", values, "description");
            return this;
        }

        public Criteria andDescriptionNotIn(List values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return this;
        }

        public Criteria andAdderSnIsNull() {
            addCriterion("ADDER_SN is null");
            return this;
        }

        public Criteria andAdderSnIsNotNull() {
            addCriterion("ADDER_SN is not null");
            return this;
        }

        public Criteria andAdderSnEqualTo(Long value) {
            addCriterion("ADDER_SN =", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotEqualTo(Long value) {
            addCriterion("ADDER_SN <>", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThan(Long value) {
            addCriterion("ADDER_SN >", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN >=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThan(Long value) {
            addCriterion("ADDER_SN <", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN <=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnIn(List values) {
            addCriterion("ADDER_SN in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotIn(List values) {
            addCriterion("ADDER_SN not in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN not between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderNameIsNull() {
            addCriterion("ADDER_NAME is null");
            return this;
        }

        public Criteria andAdderNameIsNotNull() {
            addCriterion("ADDER_NAME is not null");
            return this;
        }

        public Criteria andAdderNameEqualTo(String value) {
            addCriterion("ADDER_NAME =", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotEqualTo(String value) {
            addCriterion("ADDER_NAME <>", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThan(String value) {
            addCriterion("ADDER_NAME >", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME >=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThan(String value) {
            addCriterion("ADDER_NAME <", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME <=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLike(String value) {
            addCriterion("ADDER_NAME like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotLike(String value) {
            addCriterion("ADDER_NAME not like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameIn(List values) {
            addCriterion("ADDER_NAME in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameNotIn(List values) {
            addCriterion("ADDER_NAME not in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameBetween(String value1, String value2) {
            addCriterion("ADDER_NAME between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAdderNameNotBetween(String value1, String value2) {
            addCriterion("ADDER_NAME not between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeIn(List values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeNotIn(List values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return this;
        }

        public Criteria andUpdaterSnIsNull() {
            addCriterion("UPDATER_SN is null");
            return this;
        }

        public Criteria andUpdaterSnIsNotNull() {
            addCriterion("UPDATER_SN is not null");
            return this;
        }

        public Criteria andUpdaterSnEqualTo(Long value) {
            addCriterion("UPDATER_SN =", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotEqualTo(Long value) {
            addCriterion("UPDATER_SN <>", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThan(Long value) {
            addCriterion("UPDATER_SN >", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN >=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThan(Long value) {
            addCriterion("UPDATER_SN <", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN <=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnIn(List values) {
            addCriterion("UPDATER_SN in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotIn(List values) {
            addCriterion("UPDATER_SN not in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN not between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterNameIsNull() {
            addCriterion("UPDATER_NAME is null");
            return this;
        }

        public Criteria andUpdaterNameIsNotNull() {
            addCriterion("UPDATER_NAME is not null");
            return this;
        }

        public Criteria andUpdaterNameEqualTo(String value) {
            addCriterion("UPDATER_NAME =", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotEqualTo(String value) {
            addCriterion("UPDATER_NAME <>", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThan(String value) {
            addCriterion("UPDATER_NAME >", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME >=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThan(String value) {
            addCriterion("UPDATER_NAME <", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME <=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLike(String value) {
            addCriterion("UPDATER_NAME like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotLike(String value) {
            addCriterion("UPDATER_NAME not like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameIn(List values) {
            addCriterion("UPDATER_NAME in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotIn(List values) {
            addCriterion("UPDATER_NAME not in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME not between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }
    }
}