package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "biz_agent_login", Class = BizAgentLogin.class)
public class BizAgentLogin<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.SN
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.LOGIN_NAME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @Column
    private String loginName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.PASSWORD
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @Column
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.STATUS
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @Column
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.USER_ID
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @Column
    private Long userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.LOGIN_TIMES
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @Column
    private Integer loginTimes;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.REMARK
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @Column
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.LAST_LOGIN_TIME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @Column
    private Date lastLoginTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.ADDER_SN
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.ADDER_NAME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.ADD_TIME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.UPDATER_SN
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.UPDATER_NAME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_login.UPDATE_TIME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.SN
     *
     * @return the value of biz_agent_login.SN
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.SN
     *
     * @param sn the value for biz_agent_login.SN
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.LOGIN_NAME
     *
     * @return the value of biz_agent_login.LOGIN_NAME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.LOGIN_NAME
     *
     * @param loginName the value for biz_agent_login.LOGIN_NAME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.PASSWORD
     *
     * @return the value of biz_agent_login.PASSWORD
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.PASSWORD
     *
     * @param password the value for biz_agent_login.PASSWORD
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.STATUS
     *
     * @return the value of biz_agent_login.STATUS
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.STATUS
     *
     * @param status the value for biz_agent_login.STATUS
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.USER_ID
     *
     * @return the value of biz_agent_login.USER_ID
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.USER_ID
     *
     * @param userId the value for biz_agent_login.USER_ID
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.LOGIN_TIMES
     *
     * @return the value of biz_agent_login.LOGIN_TIMES
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public Integer getLoginTimes() {
        return loginTimes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.LOGIN_TIMES
     *
     * @param loginTimes the value for biz_agent_login.LOGIN_TIMES
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setLoginTimes(Integer loginTimes) {
        this.loginTimes = loginTimes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.REMARK
     *
     * @return the value of biz_agent_login.REMARK
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.REMARK
     *
     * @param remark the value for biz_agent_login.REMARK
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.LAST_LOGIN_TIME
     *
     * @return the value of biz_agent_login.LAST_LOGIN_TIME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for biz_agent_login.LAST_LOGIN_TIME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.ADDER_SN
     *
     * @return the value of biz_agent_login.ADDER_SN
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.ADDER_SN
     *
     * @param adderSn the value for biz_agent_login.ADDER_SN
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.ADDER_NAME
     *
     * @return the value of biz_agent_login.ADDER_NAME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.ADDER_NAME
     *
     * @param adderName the value for biz_agent_login.ADDER_NAME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.ADD_TIME
     *
     * @return the value of biz_agent_login.ADD_TIME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.ADD_TIME
     *
     * @param addTime the value for biz_agent_login.ADD_TIME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.UPDATER_SN
     *
     * @return the value of biz_agent_login.UPDATER_SN
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.UPDATER_SN
     *
     * @param updaterSn the value for biz_agent_login.UPDATER_SN
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.UPDATER_NAME
     *
     * @return the value of biz_agent_login.UPDATER_NAME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.UPDATER_NAME
     *
     * @param updaterName the value for biz_agent_login.UPDATER_NAME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_login.UPDATE_TIME
     *
     * @return the value of biz_agent_login.UPDATE_TIME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_login.UPDATE_TIME
     *
     * @param updateTime the value for biz_agent_login.UPDATE_TIME
     *
     * @ibatorgenerated Thu May 19 11:11:31 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}