package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "biz_agent_role", Class = BizAgentRole.class)
public class BizAgentRole<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_role.SN
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_role.ROLE_NAME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    @Column
    private String roleName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_role.ACTIVE
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    @Column
    private Integer active;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_role.DESCRIPTION
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    @Column
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_role.ADDER_SN
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_role.ADDER_NAME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_role.ADD_TIME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_role.UPDATER_SN
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_role.UPDATER_NAME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_role.UPDATE_TIME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_role.PARENT_SN
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    @Column
    private Long parentSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_role.SN
     *
     * @return the value of biz_agent_role.SN
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_role.SN
     *
     * @param sn the value for biz_agent_role.SN
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_role.ROLE_NAME
     *
     * @return the value of biz_agent_role.ROLE_NAME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_role.ROLE_NAME
     *
     * @param roleName the value for biz_agent_role.ROLE_NAME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_role.ACTIVE
     *
     * @return the value of biz_agent_role.ACTIVE
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_role.ACTIVE
     *
     * @param active the value for biz_agent_role.ACTIVE
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_role.DESCRIPTION
     *
     * @return the value of biz_agent_role.DESCRIPTION
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_role.DESCRIPTION
     *
     * @param description the value for biz_agent_role.DESCRIPTION
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_role.ADDER_SN
     *
     * @return the value of biz_agent_role.ADDER_SN
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_role.ADDER_SN
     *
     * @param adderSn the value for biz_agent_role.ADDER_SN
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_role.ADDER_NAME
     *
     * @return the value of biz_agent_role.ADDER_NAME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_role.ADDER_NAME
     *
     * @param adderName the value for biz_agent_role.ADDER_NAME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_role.ADD_TIME
     *
     * @return the value of biz_agent_role.ADD_TIME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_role.ADD_TIME
     *
     * @param addTime the value for biz_agent_role.ADD_TIME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_role.UPDATER_SN
     *
     * @return the value of biz_agent_role.UPDATER_SN
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_role.UPDATER_SN
     *
     * @param updaterSn the value for biz_agent_role.UPDATER_SN
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_role.UPDATER_NAME
     *
     * @return the value of biz_agent_role.UPDATER_NAME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_role.UPDATER_NAME
     *
     * @param updaterName the value for biz_agent_role.UPDATER_NAME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_role.UPDATE_TIME
     *
     * @return the value of biz_agent_role.UPDATE_TIME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_role.UPDATE_TIME
     *
     * @param updateTime the value for biz_agent_role.UPDATE_TIME
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_role.PARENT_SN
     *
     * @return the value of biz_agent_role.PARENT_SN
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public Long getParentSn() {
        return parentSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_role.PARENT_SN
     *
     * @param parentSn the value for biz_agent_role.PARENT_SN
     *
     * @ibatorgenerated Tue Aug 09 14:55:38 CST 2016
     */
    public void setParentSn(Long parentSn) {
        this.parentSn = parentSn;
    }
}