package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.math.BigDecimal;
import java.util.Date;

@Xss
@SqlMap(Name = "biz_agent_user", Class = BizAgentUser.class)
public class BizAgentUser<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.PARTNER_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String partnerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.MOBILE_PHONE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String mobilePhone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.USER_NAME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String userName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.AGENT_GRADE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Integer agentGrade;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.TOTAL_SALES
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Integer totalSales;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.TASK_PROGRESS
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private BigDecimal taskProgress;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.PROVINCE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String province;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.CITY
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String city;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.STREET
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String street;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.ID_CARD_FILE_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Long idCardFileSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.COMPANY_NAME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String companyName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.KBIS_FILE_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Long kbisFileSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.STATUS
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.REMARK
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.VALID_START_DATE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Date validStartDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.VALID_END_DATE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Date validEndDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.CONTRACT_FILE_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Long contractFileSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.ID_CARD
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String idCard;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.WX_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String wxId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.PARTNER_TYPE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Integer partnerType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.REG_CHANNEL_TYPE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Integer regChannelType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.PARENT_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private Long parentSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.PAY_ZFB_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String payZfbId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.PAY_yL_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String payYlId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_user.PAY_WX_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    @Column
    private String payWxId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.SN
     *
     * @return the value of biz_agent_user.SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.SN
     *
     * @param sn the value for biz_agent_user.SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.PARTNER_ID
     *
     * @return the value of biz_agent_user.PARTNER_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.PARTNER_ID
     *
     * @param partnerId the value for biz_agent_user.PARTNER_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.MOBILE_PHONE
     *
     * @return the value of biz_agent_user.MOBILE_PHONE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.MOBILE_PHONE
     *
     * @param mobilePhone the value for biz_agent_user.MOBILE_PHONE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.USER_NAME
     *
     * @return the value of biz_agent_user.USER_NAME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.USER_NAME
     *
     * @param userName the value for biz_agent_user.USER_NAME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.AGENT_GRADE
     *
     * @return the value of biz_agent_user.AGENT_GRADE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Integer getAgentGrade() {
        return agentGrade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.AGENT_GRADE
     *
     * @param agentGrade the value for biz_agent_user.AGENT_GRADE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setAgentGrade(Integer agentGrade) {
        this.agentGrade = agentGrade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.TOTAL_SALES
     *
     * @return the value of biz_agent_user.TOTAL_SALES
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Integer getTotalSales() {
        return totalSales;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.TOTAL_SALES
     *
     * @param totalSales the value for biz_agent_user.TOTAL_SALES
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setTotalSales(Integer totalSales) {
        this.totalSales = totalSales;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.TASK_PROGRESS
     *
     * @return the value of biz_agent_user.TASK_PROGRESS
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public BigDecimal getTaskProgress() {
        return taskProgress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.TASK_PROGRESS
     *
     * @param taskProgress the value for biz_agent_user.TASK_PROGRESS
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setTaskProgress(BigDecimal taskProgress) {
        this.taskProgress = taskProgress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.PROVINCE
     *
     * @return the value of biz_agent_user.PROVINCE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.PROVINCE
     *
     * @param province the value for biz_agent_user.PROVINCE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.CITY
     *
     * @return the value of biz_agent_user.CITY
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.CITY
     *
     * @param city the value for biz_agent_user.CITY
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.STREET
     *
     * @return the value of biz_agent_user.STREET
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.STREET
     *
     * @param street the value for biz_agent_user.STREET
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.ID_CARD_FILE_SN
     *
     * @return the value of biz_agent_user.ID_CARD_FILE_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Long getIdCardFileSn() {
        return idCardFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.ID_CARD_FILE_SN
     *
     * @param idCardFileSn the value for biz_agent_user.ID_CARD_FILE_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setIdCardFileSn(Long idCardFileSn) {
        this.idCardFileSn = idCardFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.COMPANY_NAME
     *
     * @return the value of biz_agent_user.COMPANY_NAME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.COMPANY_NAME
     *
     * @param companyName the value for biz_agent_user.COMPANY_NAME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.KBIS_FILE_SN
     *
     * @return the value of biz_agent_user.KBIS_FILE_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Long getKbisFileSn() {
        return kbisFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.KBIS_FILE_SN
     *
     * @param kbisFileSn the value for biz_agent_user.KBIS_FILE_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setKbisFileSn(Long kbisFileSn) {
        this.kbisFileSn = kbisFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.STATUS
     *
     * @return the value of biz_agent_user.STATUS
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.STATUS
     *
     * @param status the value for biz_agent_user.STATUS
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.REMARK
     *
     * @return the value of biz_agent_user.REMARK
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.REMARK
     *
     * @param remark the value for biz_agent_user.REMARK
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.ADDER_SN
     *
     * @return the value of biz_agent_user.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.ADDER_SN
     *
     * @param adderSn the value for biz_agent_user.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.ADDER_NAME
     *
     * @return the value of biz_agent_user.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.ADDER_NAME
     *
     * @param adderName the value for biz_agent_user.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.ADD_TIME
     *
     * @return the value of biz_agent_user.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.ADD_TIME
     *
     * @param addTime the value for biz_agent_user.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.UPDATER_SN
     *
     * @return the value of biz_agent_user.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.UPDATER_SN
     *
     * @param updaterSn the value for biz_agent_user.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.UPDATER_NAME
     *
     * @return the value of biz_agent_user.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.UPDATER_NAME
     *
     * @param updaterName the value for biz_agent_user.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.UPDATE_TIME
     *
     * @return the value of biz_agent_user.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.UPDATE_TIME
     *
     * @param updateTime the value for biz_agent_user.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.VALID_START_DATE
     *
     * @return the value of biz_agent_user.VALID_START_DATE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Date getValidStartDate() {
        return validStartDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.VALID_START_DATE
     *
     * @param validStartDate the value for biz_agent_user.VALID_START_DATE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setValidStartDate(Date validStartDate) {
        this.validStartDate = validStartDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.VALID_END_DATE
     *
     * @return the value of biz_agent_user.VALID_END_DATE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Date getValidEndDate() {
        return validEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.VALID_END_DATE
     *
     * @param validEndDate the value for biz_agent_user.VALID_END_DATE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setValidEndDate(Date validEndDate) {
        this.validEndDate = validEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.CONTRACT_FILE_SN
     *
     * @return the value of biz_agent_user.CONTRACT_FILE_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Long getContractFileSn() {
        return contractFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.CONTRACT_FILE_SN
     *
     * @param contractFileSn the value for biz_agent_user.CONTRACT_FILE_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setContractFileSn(Long contractFileSn) {
        this.contractFileSn = contractFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.ID_CARD
     *
     * @return the value of biz_agent_user.ID_CARD
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.ID_CARD
     *
     * @param idCard the value for biz_agent_user.ID_CARD
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.WX_ID
     *
     * @return the value of biz_agent_user.WX_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getWxId() {
        return wxId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.WX_ID
     *
     * @param wxId the value for biz_agent_user.WX_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setWxId(String wxId) {
        this.wxId = wxId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.PARTNER_TYPE
     *
     * @return the value of biz_agent_user.PARTNER_TYPE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Integer getPartnerType() {
        return partnerType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.PARTNER_TYPE
     *
     * @param partnerType the value for biz_agent_user.PARTNER_TYPE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setPartnerType(Integer partnerType) {
        this.partnerType = partnerType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.REG_CHANNEL_TYPE
     *
     * @return the value of biz_agent_user.REG_CHANNEL_TYPE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Integer getRegChannelType() {
        return regChannelType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.REG_CHANNEL_TYPE
     *
     * @param regChannelType the value for biz_agent_user.REG_CHANNEL_TYPE
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setRegChannelType(Integer regChannelType) {
        this.regChannelType = regChannelType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.PARENT_SN
     *
     * @return the value of biz_agent_user.PARENT_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public Long getParentSn() {
        return parentSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.PARENT_SN
     *
     * @param parentSn the value for biz_agent_user.PARENT_SN
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setParentSn(Long parentSn) {
        this.parentSn = parentSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.PAY_ZFB_ID
     *
     * @return the value of biz_agent_user.PAY_ZFB_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getPayZfbId() {
        return payZfbId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.PAY_ZFB_ID
     *
     * @param payZfbId the value for biz_agent_user.PAY_ZFB_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setPayZfbId(String payZfbId) {
        this.payZfbId = payZfbId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.PAY_yL_ID
     *
     * @return the value of biz_agent_user.PAY_yL_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getPayYlId() {
        return payYlId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.PAY_yL_ID
     *
     * @param payYlId the value for biz_agent_user.PAY_yL_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setPayYlId(String payYlId) {
        this.payYlId = payYlId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_user.PAY_WX_ID
     *
     * @return the value of biz_agent_user.PAY_WX_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public String getPayWxId() {
        return payWxId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_user.PAY_WX_ID
     *
     * @param payWxId the value for biz_agent_user.PAY_WX_ID
     *
     * @ibatorgenerated Thu Aug 11 09:55:33 CST 2016
     */
    public void setPayWxId(String payWxId) {
        this.payWxId = payWxId;
    }
}