package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "core_category", Class = CoreCategory.class)
public class CoreCategory<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.REC_ID
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @PrimaryKey
    @Column
    private Integer recId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private Long catCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.PARENT_CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private Long parentCatCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.CAT_LEVEL
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private Integer catLevel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.CAT_NAME_EN
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private String catNameEn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.CAT_NAME_CN
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private String catNameCn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.CAT_TYPE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private String catType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.LINK_CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private Long linkCatCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.OLD_CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private String oldCatCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.LAST_UPDATE_TIME
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private Date lastUpdateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.LAST_UPDATER_NO
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private Integer lastUpdaterNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.LAST_UPDATER_NAME
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private String lastUpdaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.CAT_STATUS
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private String catStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.AIM_CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private Long aimCatCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.CAT_PROPERTY
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private String catProperty;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.CAT_DESCRIPTION
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private String catDescription;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column core_category.REP_TIME
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    @Column
    private Date repTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.REC_ID
     *
     * @return the value of core_category.REC_ID
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.REC_ID
     *
     * @param recId the value for core_category.REC_ID
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.CAT_CODE
     *
     * @return the value of core_category.CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public Long getCatCode() {
        return catCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.CAT_CODE
     *
     * @param catCode the value for core_category.CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setCatCode(Long catCode) {
        this.catCode = catCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.PARENT_CAT_CODE
     *
     * @return the value of core_category.PARENT_CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public Long getParentCatCode() {
        return parentCatCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.PARENT_CAT_CODE
     *
     * @param parentCatCode the value for core_category.PARENT_CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setParentCatCode(Long parentCatCode) {
        this.parentCatCode = parentCatCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.CAT_LEVEL
     *
     * @return the value of core_category.CAT_LEVEL
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public Integer getCatLevel() {
        return catLevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.CAT_LEVEL
     *
     * @param catLevel the value for core_category.CAT_LEVEL
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setCatLevel(Integer catLevel) {
        this.catLevel = catLevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.CAT_NAME_EN
     *
     * @return the value of core_category.CAT_NAME_EN
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public String getCatNameEn() {
        return catNameEn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.CAT_NAME_EN
     *
     * @param catNameEn the value for core_category.CAT_NAME_EN
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setCatNameEn(String catNameEn) {
        this.catNameEn = catNameEn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.CAT_NAME_CN
     *
     * @return the value of core_category.CAT_NAME_CN
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public String getCatNameCn() {
        return catNameCn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.CAT_NAME_CN
     *
     * @param catNameCn the value for core_category.CAT_NAME_CN
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setCatNameCn(String catNameCn) {
        this.catNameCn = catNameCn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.CAT_TYPE
     *
     * @return the value of core_category.CAT_TYPE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public String getCatType() {
        return catType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.CAT_TYPE
     *
     * @param catType the value for core_category.CAT_TYPE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setCatType(String catType) {
        this.catType = catType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.LINK_CAT_CODE
     *
     * @return the value of core_category.LINK_CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public Long getLinkCatCode() {
        return linkCatCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.LINK_CAT_CODE
     *
     * @param linkCatCode the value for core_category.LINK_CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setLinkCatCode(Long linkCatCode) {
        this.linkCatCode = linkCatCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.OLD_CAT_CODE
     *
     * @return the value of core_category.OLD_CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public String getOldCatCode() {
        return oldCatCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.OLD_CAT_CODE
     *
     * @param oldCatCode the value for core_category.OLD_CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setOldCatCode(String oldCatCode) {
        this.oldCatCode = oldCatCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.LAST_UPDATE_TIME
     *
     * @return the value of core_category.LAST_UPDATE_TIME
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for core_category.LAST_UPDATE_TIME
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.LAST_UPDATER_NO
     *
     * @return the value of core_category.LAST_UPDATER_NO
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public Integer getLastUpdaterNo() {
        return lastUpdaterNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.LAST_UPDATER_NO
     *
     * @param lastUpdaterNo the value for core_category.LAST_UPDATER_NO
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setLastUpdaterNo(Integer lastUpdaterNo) {
        this.lastUpdaterNo = lastUpdaterNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.LAST_UPDATER_NAME
     *
     * @return the value of core_category.LAST_UPDATER_NAME
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public String getLastUpdaterName() {
        return lastUpdaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.LAST_UPDATER_NAME
     *
     * @param lastUpdaterName the value for core_category.LAST_UPDATER_NAME
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setLastUpdaterName(String lastUpdaterName) {
        this.lastUpdaterName = lastUpdaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.CAT_STATUS
     *
     * @return the value of core_category.CAT_STATUS
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public String getCatStatus() {
        return catStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.CAT_STATUS
     *
     * @param catStatus the value for core_category.CAT_STATUS
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setCatStatus(String catStatus) {
        this.catStatus = catStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.AIM_CAT_CODE
     *
     * @return the value of core_category.AIM_CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public Long getAimCatCode() {
        return aimCatCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.AIM_CAT_CODE
     *
     * @param aimCatCode the value for core_category.AIM_CAT_CODE
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setAimCatCode(Long aimCatCode) {
        this.aimCatCode = aimCatCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.CAT_PROPERTY
     *
     * @return the value of core_category.CAT_PROPERTY
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public String getCatProperty() {
        return catProperty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.CAT_PROPERTY
     *
     * @param catProperty the value for core_category.CAT_PROPERTY
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setCatProperty(String catProperty) {
        this.catProperty = catProperty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.CAT_DESCRIPTION
     *
     * @return the value of core_category.CAT_DESCRIPTION
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public String getCatDescription() {
        return catDescription;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.CAT_DESCRIPTION
     *
     * @param catDescription the value for core_category.CAT_DESCRIPTION
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setCatDescription(String catDescription) {
        this.catDescription = catDescription;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column core_category.REP_TIME
     *
     * @return the value of core_category.REP_TIME
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public Date getRepTime() {
        return repTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column core_category.REP_TIME
     *
     * @param repTime the value for core_category.REP_TIME
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setRepTime(Date repTime) {
        this.repTime = repTime;
    }
}