package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "core_category", Class = CoreCategory.class)
public class CoreCategoryCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public CoreCategoryCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public CoreCategoryCriteria(CoreCategoryCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public CoreCategoryCriteria(Object record, CoreCategoryCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table core_category
     *
     * @ibatorgenerated Sun Sep 25 11:32:43 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andRecIdIsNull() {
            addCriterion("REC_ID is null");
            return this;
        }

        public Criteria andRecIdIsNotNull() {
            addCriterion("REC_ID is not null");
            return this;
        }

        public Criteria andRecIdEqualTo(Integer value) {
            addCriterion("REC_ID =", value, "recId");
            return this;
        }

        public Criteria andRecIdNotEqualTo(Integer value) {
            addCriterion("REC_ID <>", value, "recId");
            return this;
        }

        public Criteria andRecIdGreaterThan(Integer value) {
            addCriterion("REC_ID >", value, "recId");
            return this;
        }

        public Criteria andRecIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("REC_ID >=", value, "recId");
            return this;
        }

        public Criteria andRecIdLessThan(Integer value) {
            addCriterion("REC_ID <", value, "recId");
            return this;
        }

        public Criteria andRecIdLessThanOrEqualTo(Integer value) {
            addCriterion("REC_ID <=", value, "recId");
            return this;
        }

        public Criteria andRecIdIn(List values) {
            addCriterion("REC_ID in", values, "recId");
            return this;
        }

        public Criteria andRecIdNotIn(List values) {
            addCriterion("REC_ID not in", values, "recId");
            return this;
        }

        public Criteria andRecIdBetween(Integer value1, Integer value2) {
            addCriterion("REC_ID between", value1, value2, "recId");
            return this;
        }

        public Criteria andRecIdNotBetween(Integer value1, Integer value2) {
            addCriterion("REC_ID not between", value1, value2, "recId");
            return this;
        }

        public Criteria andCatCodeIsNull() {
            addCriterion("CAT_CODE is null");
            return this;
        }

        public Criteria andCatCodeIsNotNull() {
            addCriterion("CAT_CODE is not null");
            return this;
        }

        public Criteria andCatCodeEqualTo(Long value) {
            addCriterion("CAT_CODE =", value, "catCode");
            return this;
        }

        public Criteria andCatCodeNotEqualTo(Long value) {
            addCriterion("CAT_CODE <>", value, "catCode");
            return this;
        }

        public Criteria andCatCodeGreaterThan(Long value) {
            addCriterion("CAT_CODE >", value, "catCode");
            return this;
        }

        public Criteria andCatCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("CAT_CODE >=", value, "catCode");
            return this;
        }

        public Criteria andCatCodeLessThan(Long value) {
            addCriterion("CAT_CODE <", value, "catCode");
            return this;
        }

        public Criteria andCatCodeLessThanOrEqualTo(Long value) {
            addCriterion("CAT_CODE <=", value, "catCode");
            return this;
        }

        public Criteria andCatCodeIn(List values) {
            addCriterion("CAT_CODE in", values, "catCode");
            return this;
        }

        public Criteria andCatCodeNotIn(List values) {
            addCriterion("CAT_CODE not in", values, "catCode");
            return this;
        }

        public Criteria andCatCodeBetween(Long value1, Long value2) {
            addCriterion("CAT_CODE between", value1, value2, "catCode");
            return this;
        }

        public Criteria andCatCodeNotBetween(Long value1, Long value2) {
            addCriterion("CAT_CODE not between", value1, value2, "catCode");
            return this;
        }

        public Criteria andParentCatCodeIsNull() {
            addCriterion("PARENT_CAT_CODE is null");
            return this;
        }

        public Criteria andParentCatCodeIsNotNull() {
            addCriterion("PARENT_CAT_CODE is not null");
            return this;
        }

        public Criteria andParentCatCodeEqualTo(Long value) {
            addCriterion("PARENT_CAT_CODE =", value, "parentCatCode");
            return this;
        }

        public Criteria andParentCatCodeNotEqualTo(Long value) {
            addCriterion("PARENT_CAT_CODE <>", value, "parentCatCode");
            return this;
        }

        public Criteria andParentCatCodeGreaterThan(Long value) {
            addCriterion("PARENT_CAT_CODE >", value, "parentCatCode");
            return this;
        }

        public Criteria andParentCatCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("PARENT_CAT_CODE >=", value, "parentCatCode");
            return this;
        }

        public Criteria andParentCatCodeLessThan(Long value) {
            addCriterion("PARENT_CAT_CODE <", value, "parentCatCode");
            return this;
        }

        public Criteria andParentCatCodeLessThanOrEqualTo(Long value) {
            addCriterion("PARENT_CAT_CODE <=", value, "parentCatCode");
            return this;
        }

        public Criteria andParentCatCodeIn(List values) {
            addCriterion("PARENT_CAT_CODE in", values, "parentCatCode");
            return this;
        }

        public Criteria andParentCatCodeNotIn(List values) {
            addCriterion("PARENT_CAT_CODE not in", values, "parentCatCode");
            return this;
        }

        public Criteria andParentCatCodeBetween(Long value1, Long value2) {
            addCriterion("PARENT_CAT_CODE between", value1, value2, "parentCatCode");
            return this;
        }

        public Criteria andParentCatCodeNotBetween(Long value1, Long value2) {
            addCriterion("PARENT_CAT_CODE not between", value1, value2, "parentCatCode");
            return this;
        }

        public Criteria andCatLevelIsNull() {
            addCriterion("CAT_LEVEL is null");
            return this;
        }

        public Criteria andCatLevelIsNotNull() {
            addCriterion("CAT_LEVEL is not null");
            return this;
        }

        public Criteria andCatLevelEqualTo(Integer value) {
            addCriterion("CAT_LEVEL =", value, "catLevel");
            return this;
        }

        public Criteria andCatLevelNotEqualTo(Integer value) {
            addCriterion("CAT_LEVEL <>", value, "catLevel");
            return this;
        }

        public Criteria andCatLevelGreaterThan(Integer value) {
            addCriterion("CAT_LEVEL >", value, "catLevel");
            return this;
        }

        public Criteria andCatLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("CAT_LEVEL >=", value, "catLevel");
            return this;
        }

        public Criteria andCatLevelLessThan(Integer value) {
            addCriterion("CAT_LEVEL <", value, "catLevel");
            return this;
        }

        public Criteria andCatLevelLessThanOrEqualTo(Integer value) {
            addCriterion("CAT_LEVEL <=", value, "catLevel");
            return this;
        }

        public Criteria andCatLevelIn(List values) {
            addCriterion("CAT_LEVEL in", values, "catLevel");
            return this;
        }

        public Criteria andCatLevelNotIn(List values) {
            addCriterion("CAT_LEVEL not in", values, "catLevel");
            return this;
        }

        public Criteria andCatLevelBetween(Integer value1, Integer value2) {
            addCriterion("CAT_LEVEL between", value1, value2, "catLevel");
            return this;
        }

        public Criteria andCatLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("CAT_LEVEL not between", value1, value2, "catLevel");
            return this;
        }

        public Criteria andCatNameEnIsNull() {
            addCriterion("CAT_NAME_EN is null");
            return this;
        }

        public Criteria andCatNameEnIsNotNull() {
            addCriterion("CAT_NAME_EN is not null");
            return this;
        }

        public Criteria andCatNameEnEqualTo(String value) {
            addCriterion("CAT_NAME_EN =", value, "catNameEn");
            return this;
        }

        public Criteria andCatNameEnNotEqualTo(String value) {
            addCriterion("CAT_NAME_EN <>", value, "catNameEn");
            return this;
        }

        public Criteria andCatNameEnGreaterThan(String value) {
            addCriterion("CAT_NAME_EN >", value, "catNameEn");
            return this;
        }

        public Criteria andCatNameEnGreaterThanOrEqualTo(String value) {
            addCriterion("CAT_NAME_EN >=", value, "catNameEn");
            return this;
        }

        public Criteria andCatNameEnLessThan(String value) {
            addCriterion("CAT_NAME_EN <", value, "catNameEn");
            return this;
        }

        public Criteria andCatNameEnLessThanOrEqualTo(String value) {
            addCriterion("CAT_NAME_EN <=", value, "catNameEn");
            return this;
        }

        public Criteria andCatNameEnLike(String value) {
            addCriterion("CAT_NAME_EN like", value, "catNameEn");
            return this;
        }

        public Criteria andCatNameEnNotLike(String value) {
            addCriterion("CAT_NAME_EN not like", value, "catNameEn");
            return this;
        }

        public Criteria andCatNameEnIn(List values) {
            addCriterion("CAT_NAME_EN in", values, "catNameEn");
            return this;
        }

        public Criteria andCatNameEnNotIn(List values) {
            addCriterion("CAT_NAME_EN not in", values, "catNameEn");
            return this;
        }

        public Criteria andCatNameEnBetween(String value1, String value2) {
            addCriterion("CAT_NAME_EN between", value1, value2, "catNameEn");
            return this;
        }

        public Criteria andCatNameEnNotBetween(String value1, String value2) {
            addCriterion("CAT_NAME_EN not between", value1, value2, "catNameEn");
            return this;
        }

        public Criteria andCatNameCnIsNull() {
            addCriterion("CAT_NAME_CN is null");
            return this;
        }

        public Criteria andCatNameCnIsNotNull() {
            addCriterion("CAT_NAME_CN is not null");
            return this;
        }

        public Criteria andCatNameCnEqualTo(String value) {
            addCriterion("CAT_NAME_CN =", value, "catNameCn");
            return this;
        }

        public Criteria andCatNameCnNotEqualTo(String value) {
            addCriterion("CAT_NAME_CN <>", value, "catNameCn");
            return this;
        }

        public Criteria andCatNameCnGreaterThan(String value) {
            addCriterion("CAT_NAME_CN >", value, "catNameCn");
            return this;
        }

        public Criteria andCatNameCnGreaterThanOrEqualTo(String value) {
            addCriterion("CAT_NAME_CN >=", value, "catNameCn");
            return this;
        }

        public Criteria andCatNameCnLessThan(String value) {
            addCriterion("CAT_NAME_CN <", value, "catNameCn");
            return this;
        }

        public Criteria andCatNameCnLessThanOrEqualTo(String value) {
            addCriterion("CAT_NAME_CN <=", value, "catNameCn");
            return this;
        }

        public Criteria andCatNameCnLike(String value) {
            addCriterion("CAT_NAME_CN like", value, "catNameCn");
            return this;
        }

        public Criteria andCatNameCnNotLike(String value) {
            addCriterion("CAT_NAME_CN not like", value, "catNameCn");
            return this;
        }

        public Criteria andCatNameCnIn(List values) {
            addCriterion("CAT_NAME_CN in", values, "catNameCn");
            return this;
        }

        public Criteria andCatNameCnNotIn(List values) {
            addCriterion("CAT_NAME_CN not in", values, "catNameCn");
            return this;
        }

        public Criteria andCatNameCnBetween(String value1, String value2) {
            addCriterion("CAT_NAME_CN between", value1, value2, "catNameCn");
            return this;
        }

        public Criteria andCatNameCnNotBetween(String value1, String value2) {
            addCriterion("CAT_NAME_CN not between", value1, value2, "catNameCn");
            return this;
        }

        public Criteria andCatTypeIsNull() {
            addCriterion("CAT_TYPE is null");
            return this;
        }

        public Criteria andCatTypeIsNotNull() {
            addCriterion("CAT_TYPE is not null");
            return this;
        }

        public Criteria andCatTypeEqualTo(String value) {
            addCriterion("CAT_TYPE =", value, "catType");
            return this;
        }

        public Criteria andCatTypeNotEqualTo(String value) {
            addCriterion("CAT_TYPE <>", value, "catType");
            return this;
        }

        public Criteria andCatTypeGreaterThan(String value) {
            addCriterion("CAT_TYPE >", value, "catType");
            return this;
        }

        public Criteria andCatTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CAT_TYPE >=", value, "catType");
            return this;
        }

        public Criteria andCatTypeLessThan(String value) {
            addCriterion("CAT_TYPE <", value, "catType");
            return this;
        }

        public Criteria andCatTypeLessThanOrEqualTo(String value) {
            addCriterion("CAT_TYPE <=", value, "catType");
            return this;
        }

        public Criteria andCatTypeLike(String value) {
            addCriterion("CAT_TYPE like", value, "catType");
            return this;
        }

        public Criteria andCatTypeNotLike(String value) {
            addCriterion("CAT_TYPE not like", value, "catType");
            return this;
        }

        public Criteria andCatTypeIn(List values) {
            addCriterion("CAT_TYPE in", values, "catType");
            return this;
        }

        public Criteria andCatTypeNotIn(List values) {
            addCriterion("CAT_TYPE not in", values, "catType");
            return this;
        }

        public Criteria andCatTypeBetween(String value1, String value2) {
            addCriterion("CAT_TYPE between", value1, value2, "catType");
            return this;
        }

        public Criteria andCatTypeNotBetween(String value1, String value2) {
            addCriterion("CAT_TYPE not between", value1, value2, "catType");
            return this;
        }

        public Criteria andLinkCatCodeIsNull() {
            addCriterion("LINK_CAT_CODE is null");
            return this;
        }

        public Criteria andLinkCatCodeIsNotNull() {
            addCriterion("LINK_CAT_CODE is not null");
            return this;
        }

        public Criteria andLinkCatCodeEqualTo(Long value) {
            addCriterion("LINK_CAT_CODE =", value, "linkCatCode");
            return this;
        }

        public Criteria andLinkCatCodeNotEqualTo(Long value) {
            addCriterion("LINK_CAT_CODE <>", value, "linkCatCode");
            return this;
        }

        public Criteria andLinkCatCodeGreaterThan(Long value) {
            addCriterion("LINK_CAT_CODE >", value, "linkCatCode");
            return this;
        }

        public Criteria andLinkCatCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("LINK_CAT_CODE >=", value, "linkCatCode");
            return this;
        }

        public Criteria andLinkCatCodeLessThan(Long value) {
            addCriterion("LINK_CAT_CODE <", value, "linkCatCode");
            return this;
        }

        public Criteria andLinkCatCodeLessThanOrEqualTo(Long value) {
            addCriterion("LINK_CAT_CODE <=", value, "linkCatCode");
            return this;
        }

        public Criteria andLinkCatCodeIn(List values) {
            addCriterion("LINK_CAT_CODE in", values, "linkCatCode");
            return this;
        }

        public Criteria andLinkCatCodeNotIn(List values) {
            addCriterion("LINK_CAT_CODE not in", values, "linkCatCode");
            return this;
        }

        public Criteria andLinkCatCodeBetween(Long value1, Long value2) {
            addCriterion("LINK_CAT_CODE between", value1, value2, "linkCatCode");
            return this;
        }

        public Criteria andLinkCatCodeNotBetween(Long value1, Long value2) {
            addCriterion("LINK_CAT_CODE not between", value1, value2, "linkCatCode");
            return this;
        }

        public Criteria andOldCatCodeIsNull() {
            addCriterion("OLD_CAT_CODE is null");
            return this;
        }

        public Criteria andOldCatCodeIsNotNull() {
            addCriterion("OLD_CAT_CODE is not null");
            return this;
        }

        public Criteria andOldCatCodeEqualTo(String value) {
            addCriterion("OLD_CAT_CODE =", value, "oldCatCode");
            return this;
        }

        public Criteria andOldCatCodeNotEqualTo(String value) {
            addCriterion("OLD_CAT_CODE <>", value, "oldCatCode");
            return this;
        }

        public Criteria andOldCatCodeGreaterThan(String value) {
            addCriterion("OLD_CAT_CODE >", value, "oldCatCode");
            return this;
        }

        public Criteria andOldCatCodeGreaterThanOrEqualTo(String value) {
            addCriterion("OLD_CAT_CODE >=", value, "oldCatCode");
            return this;
        }

        public Criteria andOldCatCodeLessThan(String value) {
            addCriterion("OLD_CAT_CODE <", value, "oldCatCode");
            return this;
        }

        public Criteria andOldCatCodeLessThanOrEqualTo(String value) {
            addCriterion("OLD_CAT_CODE <=", value, "oldCatCode");
            return this;
        }

        public Criteria andOldCatCodeLike(String value) {
            addCriterion("OLD_CAT_CODE like", value, "oldCatCode");
            return this;
        }

        public Criteria andOldCatCodeNotLike(String value) {
            addCriterion("OLD_CAT_CODE not like", value, "oldCatCode");
            return this;
        }

        public Criteria andOldCatCodeIn(List values) {
            addCriterion("OLD_CAT_CODE in", values, "oldCatCode");
            return this;
        }

        public Criteria andOldCatCodeNotIn(List values) {
            addCriterion("OLD_CAT_CODE not in", values, "oldCatCode");
            return this;
        }

        public Criteria andOldCatCodeBetween(String value1, String value2) {
            addCriterion("OLD_CAT_CODE between", value1, value2, "oldCatCode");
            return this;
        }

        public Criteria andOldCatCodeNotBetween(String value1, String value2) {
            addCriterion("OLD_CAT_CODE not between", value1, value2, "oldCatCode");
            return this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("LAST_UPDATE_TIME is null");
            return this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("LAST_UPDATE_TIME is not null");
            return this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("LAST_UPDATE_TIME =", value, "lastUpdateTime");
            return this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("LAST_UPDATE_TIME <>", value, "lastUpdateTime");
            return this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("LAST_UPDATE_TIME >", value, "lastUpdateTime");
            return this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_TIME >=", value, "lastUpdateTime");
            return this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("LAST_UPDATE_TIME <", value, "lastUpdateTime");
            return this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_TIME <=", value, "lastUpdateTime");
            return this;
        }

        public Criteria andLastUpdateTimeIn(List values) {
            addCriterion("LAST_UPDATE_TIME in", values, "lastUpdateTime");
            return this;
        }

        public Criteria andLastUpdateTimeNotIn(List values) {
            addCriterion("LAST_UPDATE_TIME not in", values, "lastUpdateTime");
            return this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_TIME between", value1, value2, "lastUpdateTime");
            return this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_TIME not between", value1, value2, "lastUpdateTime");
            return this;
        }

        public Criteria andLastUpdaterNoIsNull() {
            addCriterion("LAST_UPDATER_NO is null");
            return this;
        }

        public Criteria andLastUpdaterNoIsNotNull() {
            addCriterion("LAST_UPDATER_NO is not null");
            return this;
        }

        public Criteria andLastUpdaterNoEqualTo(Integer value) {
            addCriterion("LAST_UPDATER_NO =", value, "lastUpdaterNo");
            return this;
        }

        public Criteria andLastUpdaterNoNotEqualTo(Integer value) {
            addCriterion("LAST_UPDATER_NO <>", value, "lastUpdaterNo");
            return this;
        }

        public Criteria andLastUpdaterNoGreaterThan(Integer value) {
            addCriterion("LAST_UPDATER_NO >", value, "lastUpdaterNo");
            return this;
        }

        public Criteria andLastUpdaterNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("LAST_UPDATER_NO >=", value, "lastUpdaterNo");
            return this;
        }

        public Criteria andLastUpdaterNoLessThan(Integer value) {
            addCriterion("LAST_UPDATER_NO <", value, "lastUpdaterNo");
            return this;
        }

        public Criteria andLastUpdaterNoLessThanOrEqualTo(Integer value) {
            addCriterion("LAST_UPDATER_NO <=", value, "lastUpdaterNo");
            return this;
        }

        public Criteria andLastUpdaterNoIn(List values) {
            addCriterion("LAST_UPDATER_NO in", values, "lastUpdaterNo");
            return this;
        }

        public Criteria andLastUpdaterNoNotIn(List values) {
            addCriterion("LAST_UPDATER_NO not in", values, "lastUpdaterNo");
            return this;
        }

        public Criteria andLastUpdaterNoBetween(Integer value1, Integer value2) {
            addCriterion("LAST_UPDATER_NO between", value1, value2, "lastUpdaterNo");
            return this;
        }

        public Criteria andLastUpdaterNoNotBetween(Integer value1, Integer value2) {
            addCriterion("LAST_UPDATER_NO not between", value1, value2, "lastUpdaterNo");
            return this;
        }

        public Criteria andLastUpdaterNameIsNull() {
            addCriterion("LAST_UPDATER_NAME is null");
            return this;
        }

        public Criteria andLastUpdaterNameIsNotNull() {
            addCriterion("LAST_UPDATER_NAME is not null");
            return this;
        }

        public Criteria andLastUpdaterNameEqualTo(String value) {
            addCriterion("LAST_UPDATER_NAME =", value, "lastUpdaterName");
            return this;
        }

        public Criteria andLastUpdaterNameNotEqualTo(String value) {
            addCriterion("LAST_UPDATER_NAME <>", value, "lastUpdaterName");
            return this;
        }

        public Criteria andLastUpdaterNameGreaterThan(String value) {
            addCriterion("LAST_UPDATER_NAME >", value, "lastUpdaterName");
            return this;
        }

        public Criteria andLastUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UPDATER_NAME >=", value, "lastUpdaterName");
            return this;
        }

        public Criteria andLastUpdaterNameLessThan(String value) {
            addCriterion("LAST_UPDATER_NAME <", value, "lastUpdaterName");
            return this;
        }

        public Criteria andLastUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("LAST_UPDATER_NAME <=", value, "lastUpdaterName");
            return this;
        }

        public Criteria andLastUpdaterNameLike(String value) {
            addCriterion("LAST_UPDATER_NAME like", value, "lastUpdaterName");
            return this;
        }

        public Criteria andLastUpdaterNameNotLike(String value) {
            addCriterion("LAST_UPDATER_NAME not like", value, "lastUpdaterName");
            return this;
        }

        public Criteria andLastUpdaterNameIn(List values) {
            addCriterion("LAST_UPDATER_NAME in", values, "lastUpdaterName");
            return this;
        }

        public Criteria andLastUpdaterNameNotIn(List values) {
            addCriterion("LAST_UPDATER_NAME not in", values, "lastUpdaterName");
            return this;
        }

        public Criteria andLastUpdaterNameBetween(String value1, String value2) {
            addCriterion("LAST_UPDATER_NAME between", value1, value2, "lastUpdaterName");
            return this;
        }

        public Criteria andLastUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("LAST_UPDATER_NAME not between", value1, value2, "lastUpdaterName");
            return this;
        }

        public Criteria andCatStatusIsNull() {
            addCriterion("CAT_STATUS is null");
            return this;
        }

        public Criteria andCatStatusIsNotNull() {
            addCriterion("CAT_STATUS is not null");
            return this;
        }

        public Criteria andCatStatusEqualTo(String value) {
            addCriterion("CAT_STATUS =", value, "catStatus");
            return this;
        }

        public Criteria andCatStatusNotEqualTo(String value) {
            addCriterion("CAT_STATUS <>", value, "catStatus");
            return this;
        }

        public Criteria andCatStatusGreaterThan(String value) {
            addCriterion("CAT_STATUS >", value, "catStatus");
            return this;
        }

        public Criteria andCatStatusGreaterThanOrEqualTo(String value) {
            addCriterion("CAT_STATUS >=", value, "catStatus");
            return this;
        }

        public Criteria andCatStatusLessThan(String value) {
            addCriterion("CAT_STATUS <", value, "catStatus");
            return this;
        }

        public Criteria andCatStatusLessThanOrEqualTo(String value) {
            addCriterion("CAT_STATUS <=", value, "catStatus");
            return this;
        }

        public Criteria andCatStatusLike(String value) {
            addCriterion("CAT_STATUS like", value, "catStatus");
            return this;
        }

        public Criteria andCatStatusNotLike(String value) {
            addCriterion("CAT_STATUS not like", value, "catStatus");
            return this;
        }

        public Criteria andCatStatusIn(List values) {
            addCriterion("CAT_STATUS in", values, "catStatus");
            return this;
        }

        public Criteria andCatStatusNotIn(List values) {
            addCriterion("CAT_STATUS not in", values, "catStatus");
            return this;
        }

        public Criteria andCatStatusBetween(String value1, String value2) {
            addCriterion("CAT_STATUS between", value1, value2, "catStatus");
            return this;
        }

        public Criteria andCatStatusNotBetween(String value1, String value2) {
            addCriterion("CAT_STATUS not between", value1, value2, "catStatus");
            return this;
        }

        public Criteria andAimCatCodeIsNull() {
            addCriterion("AIM_CAT_CODE is null");
            return this;
        }

        public Criteria andAimCatCodeIsNotNull() {
            addCriterion("AIM_CAT_CODE is not null");
            return this;
        }

        public Criteria andAimCatCodeEqualTo(Long value) {
            addCriterion("AIM_CAT_CODE =", value, "aimCatCode");
            return this;
        }

        public Criteria andAimCatCodeNotEqualTo(Long value) {
            addCriterion("AIM_CAT_CODE <>", value, "aimCatCode");
            return this;
        }

        public Criteria andAimCatCodeGreaterThan(Long value) {
            addCriterion("AIM_CAT_CODE >", value, "aimCatCode");
            return this;
        }

        public Criteria andAimCatCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("AIM_CAT_CODE >=", value, "aimCatCode");
            return this;
        }

        public Criteria andAimCatCodeLessThan(Long value) {
            addCriterion("AIM_CAT_CODE <", value, "aimCatCode");
            return this;
        }

        public Criteria andAimCatCodeLessThanOrEqualTo(Long value) {
            addCriterion("AIM_CAT_CODE <=", value, "aimCatCode");
            return this;
        }

        public Criteria andAimCatCodeIn(List values) {
            addCriterion("AIM_CAT_CODE in", values, "aimCatCode");
            return this;
        }

        public Criteria andAimCatCodeNotIn(List values) {
            addCriterion("AIM_CAT_CODE not in", values, "aimCatCode");
            return this;
        }

        public Criteria andAimCatCodeBetween(Long value1, Long value2) {
            addCriterion("AIM_CAT_CODE between", value1, value2, "aimCatCode");
            return this;
        }

        public Criteria andAimCatCodeNotBetween(Long value1, Long value2) {
            addCriterion("AIM_CAT_CODE not between", value1, value2, "aimCatCode");
            return this;
        }

        public Criteria andCatPropertyIsNull() {
            addCriterion("CAT_PROPERTY is null");
            return this;
        }

        public Criteria andCatPropertyIsNotNull() {
            addCriterion("CAT_PROPERTY is not null");
            return this;
        }

        public Criteria andCatPropertyEqualTo(String value) {
            addCriterion("CAT_PROPERTY =", value, "catProperty");
            return this;
        }

        public Criteria andCatPropertyNotEqualTo(String value) {
            addCriterion("CAT_PROPERTY <>", value, "catProperty");
            return this;
        }

        public Criteria andCatPropertyGreaterThan(String value) {
            addCriterion("CAT_PROPERTY >", value, "catProperty");
            return this;
        }

        public Criteria andCatPropertyGreaterThanOrEqualTo(String value) {
            addCriterion("CAT_PROPERTY >=", value, "catProperty");
            return this;
        }

        public Criteria andCatPropertyLessThan(String value) {
            addCriterion("CAT_PROPERTY <", value, "catProperty");
            return this;
        }

        public Criteria andCatPropertyLessThanOrEqualTo(String value) {
            addCriterion("CAT_PROPERTY <=", value, "catProperty");
            return this;
        }

        public Criteria andCatPropertyLike(String value) {
            addCriterion("CAT_PROPERTY like", value, "catProperty");
            return this;
        }

        public Criteria andCatPropertyNotLike(String value) {
            addCriterion("CAT_PROPERTY not like", value, "catProperty");
            return this;
        }

        public Criteria andCatPropertyIn(List values) {
            addCriterion("CAT_PROPERTY in", values, "catProperty");
            return this;
        }

        public Criteria andCatPropertyNotIn(List values) {
            addCriterion("CAT_PROPERTY not in", values, "catProperty");
            return this;
        }

        public Criteria andCatPropertyBetween(String value1, String value2) {
            addCriterion("CAT_PROPERTY between", value1, value2, "catProperty");
            return this;
        }

        public Criteria andCatPropertyNotBetween(String value1, String value2) {
            addCriterion("CAT_PROPERTY not between", value1, value2, "catProperty");
            return this;
        }

        public Criteria andCatDescriptionIsNull() {
            addCriterion("CAT_DESCRIPTION is null");
            return this;
        }

        public Criteria andCatDescriptionIsNotNull() {
            addCriterion("CAT_DESCRIPTION is not null");
            return this;
        }

        public Criteria andCatDescriptionEqualTo(String value) {
            addCriterion("CAT_DESCRIPTION =", value, "catDescription");
            return this;
        }

        public Criteria andCatDescriptionNotEqualTo(String value) {
            addCriterion("CAT_DESCRIPTION <>", value, "catDescription");
            return this;
        }

        public Criteria andCatDescriptionGreaterThan(String value) {
            addCriterion("CAT_DESCRIPTION >", value, "catDescription");
            return this;
        }

        public Criteria andCatDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("CAT_DESCRIPTION >=", value, "catDescription");
            return this;
        }

        public Criteria andCatDescriptionLessThan(String value) {
            addCriterion("CAT_DESCRIPTION <", value, "catDescription");
            return this;
        }

        public Criteria andCatDescriptionLessThanOrEqualTo(String value) {
            addCriterion("CAT_DESCRIPTION <=", value, "catDescription");
            return this;
        }

        public Criteria andCatDescriptionLike(String value) {
            addCriterion("CAT_DESCRIPTION like", value, "catDescription");
            return this;
        }

        public Criteria andCatDescriptionNotLike(String value) {
            addCriterion("CAT_DESCRIPTION not like", value, "catDescription");
            return this;
        }

        public Criteria andCatDescriptionIn(List values) {
            addCriterion("CAT_DESCRIPTION in", values, "catDescription");
            return this;
        }

        public Criteria andCatDescriptionNotIn(List values) {
            addCriterion("CAT_DESCRIPTION not in", values, "catDescription");
            return this;
        }

        public Criteria andCatDescriptionBetween(String value1, String value2) {
            addCriterion("CAT_DESCRIPTION between", value1, value2, "catDescription");
            return this;
        }

        public Criteria andCatDescriptionNotBetween(String value1, String value2) {
            addCriterion("CAT_DESCRIPTION not between", value1, value2, "catDescription");
            return this;
        }

        public Criteria andRepTimeIsNull() {
            addCriterion("REP_TIME is null");
            return this;
        }

        public Criteria andRepTimeIsNotNull() {
            addCriterion("REP_TIME is not null");
            return this;
        }

        public Criteria andRepTimeEqualTo(Date value) {
            addCriterion("REP_TIME =", value, "repTime");
            return this;
        }

        public Criteria andRepTimeNotEqualTo(Date value) {
            addCriterion("REP_TIME <>", value, "repTime");
            return this;
        }

        public Criteria andRepTimeGreaterThan(Date value) {
            addCriterion("REP_TIME >", value, "repTime");
            return this;
        }

        public Criteria andRepTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REP_TIME >=", value, "repTime");
            return this;
        }

        public Criteria andRepTimeLessThan(Date value) {
            addCriterion("REP_TIME <", value, "repTime");
            return this;
        }

        public Criteria andRepTimeLessThanOrEqualTo(Date value) {
            addCriterion("REP_TIME <=", value, "repTime");
            return this;
        }

        public Criteria andRepTimeIn(List values) {
            addCriterion("REP_TIME in", values, "repTime");
            return this;
        }

        public Criteria andRepTimeNotIn(List values) {
            addCriterion("REP_TIME not in", values, "repTime");
            return this;
        }

        public Criteria andRepTimeBetween(Date value1, Date value2) {
            addCriterion("REP_TIME between", value1, value2, "repTime");
            return this;
        }

        public Criteria andRepTimeNotBetween(Date value1, Date value2) {
            addCriterion("REP_TIME not between", value1, value2, "repTime");
            return this;
        }
    }
}