package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "fnt_favorite", Class = FntFavorite.class)
public class FntFavorite<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_favorite.SN
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_favorite.TARGET_ID
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    @Column
    private Long targetId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_favorite.TARGET_TYPE
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    @Column
    private Integer targetType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_favorite.USER_ID
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    @Column
    private Long userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_favorite.ADDER_SN
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_favorite.ADDER_NAME
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_favorite.ADD_TIME
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_favorite.UPDATER_SN
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_favorite.UPDATER_NAME
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_favorite.UPDATE_TIME
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_favorite.SN
     *
     * @return the value of fnt_favorite.SN
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_favorite.SN
     *
     * @param sn the value for fnt_favorite.SN
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_favorite.TARGET_ID
     *
     * @return the value of fnt_favorite.TARGET_ID
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_favorite.TARGET_ID
     *
     * @param targetId the value for fnt_favorite.TARGET_ID
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_favorite.TARGET_TYPE
     *
     * @return the value of fnt_favorite.TARGET_TYPE
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public Integer getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_favorite.TARGET_TYPE
     *
     * @param targetType the value for fnt_favorite.TARGET_TYPE
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_favorite.USER_ID
     *
     * @return the value of fnt_favorite.USER_ID
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_favorite.USER_ID
     *
     * @param userId the value for fnt_favorite.USER_ID
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_favorite.ADDER_SN
     *
     * @return the value of fnt_favorite.ADDER_SN
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_favorite.ADDER_SN
     *
     * @param adderSn the value for fnt_favorite.ADDER_SN
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_favorite.ADDER_NAME
     *
     * @return the value of fnt_favorite.ADDER_NAME
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_favorite.ADDER_NAME
     *
     * @param adderName the value for fnt_favorite.ADDER_NAME
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_favorite.ADD_TIME
     *
     * @return the value of fnt_favorite.ADD_TIME
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_favorite.ADD_TIME
     *
     * @param addTime the value for fnt_favorite.ADD_TIME
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_favorite.UPDATER_SN
     *
     * @return the value of fnt_favorite.UPDATER_SN
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_favorite.UPDATER_SN
     *
     * @param updaterSn the value for fnt_favorite.UPDATER_SN
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_favorite.UPDATER_NAME
     *
     * @return the value of fnt_favorite.UPDATER_NAME
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_favorite.UPDATER_NAME
     *
     * @param updaterName the value for fnt_favorite.UPDATER_NAME
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_favorite.UPDATE_TIME
     *
     * @return the value of fnt_favorite.UPDATE_TIME
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_favorite.UPDATE_TIME
     *
     * @param updateTime the value for fnt_favorite.UPDATE_TIME
     *
     * @ibatorgenerated Mon Oct 10 15:50:08 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}