package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "fnt_house_upload", Class = FntHouseUpload.class)
public class FntHouseUploadCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public FntHouseUploadCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public FntHouseUploadCriteria(FntHouseUploadCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public FntHouseUploadCriteria(Object record, FntHouseUploadCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table fnt_house_upload
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSnIsNull() {
            addCriterion("SN is null");
            return this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("SN is not null");
            return this;
        }

        public Criteria andSnEqualTo(Long value) {
            addCriterion("SN =", value, "sn");
            return this;
        }

        public Criteria andSnNotEqualTo(Long value) {
            addCriterion("SN <>", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThan(Long value) {
            addCriterion("SN >", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SN >=", value, "sn");
            return this;
        }

        public Criteria andSnLessThan(Long value) {
            addCriterion("SN <", value, "sn");
            return this;
        }

        public Criteria andSnLessThanOrEqualTo(Long value) {
            addCriterion("SN <=", value, "sn");
            return this;
        }

        public Criteria andSnIn(List values) {
            addCriterion("SN in", values, "sn");
            return this;
        }

        public Criteria andSnNotIn(List values) {
            addCriterion("SN not in", values, "sn");
            return this;
        }

        public Criteria andSnBetween(Long value1, Long value2) {
            addCriterion("SN between", value1, value2, "sn");
            return this;
        }

        public Criteria andSnNotBetween(Long value1, Long value2) {
            addCriterion("SN not between", value1, value2, "sn");
            return this;
        }

        public Criteria andHouseNameIsNull() {
            addCriterion("HOUSE_NAME is null");
            return this;
        }

        public Criteria andHouseNameIsNotNull() {
            addCriterion("HOUSE_NAME is not null");
            return this;
        }

        public Criteria andHouseNameEqualTo(String value) {
            addCriterion("HOUSE_NAME =", value, "houseName");
            return this;
        }

        public Criteria andHouseNameNotEqualTo(String value) {
            addCriterion("HOUSE_NAME <>", value, "houseName");
            return this;
        }

        public Criteria andHouseNameGreaterThan(String value) {
            addCriterion("HOUSE_NAME >", value, "houseName");
            return this;
        }

        public Criteria andHouseNameGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSE_NAME >=", value, "houseName");
            return this;
        }

        public Criteria andHouseNameLessThan(String value) {
            addCriterion("HOUSE_NAME <", value, "houseName");
            return this;
        }

        public Criteria andHouseNameLessThanOrEqualTo(String value) {
            addCriterion("HOUSE_NAME <=", value, "houseName");
            return this;
        }

        public Criteria andHouseNameLike(String value) {
            addCriterion("HOUSE_NAME like", value, "houseName");
            return this;
        }

        public Criteria andHouseNameNotLike(String value) {
            addCriterion("HOUSE_NAME not like", value, "houseName");
            return this;
        }

        public Criteria andHouseNameIn(List values) {
            addCriterion("HOUSE_NAME in", values, "houseName");
            return this;
        }

        public Criteria andHouseNameNotIn(List values) {
            addCriterion("HOUSE_NAME not in", values, "houseName");
            return this;
        }

        public Criteria andHouseNameBetween(String value1, String value2) {
            addCriterion("HOUSE_NAME between", value1, value2, "houseName");
            return this;
        }

        public Criteria andHouseNameNotBetween(String value1, String value2) {
            addCriterion("HOUSE_NAME not between", value1, value2, "houseName");
            return this;
        }

        public Criteria andHouseFileSnIsNull() {
            addCriterion("HOUSE_FILE_SN is null");
            return this;
        }

        public Criteria andHouseFileSnIsNotNull() {
            addCriterion("HOUSE_FILE_SN is not null");
            return this;
        }

        public Criteria andHouseFileSnEqualTo(Long value) {
            addCriterion("HOUSE_FILE_SN =", value, "houseFileSn");
            return this;
        }

        public Criteria andHouseFileSnNotEqualTo(Long value) {
            addCriterion("HOUSE_FILE_SN <>", value, "houseFileSn");
            return this;
        }

        public Criteria andHouseFileSnGreaterThan(Long value) {
            addCriterion("HOUSE_FILE_SN >", value, "houseFileSn");
            return this;
        }

        public Criteria andHouseFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("HOUSE_FILE_SN >=", value, "houseFileSn");
            return this;
        }

        public Criteria andHouseFileSnLessThan(Long value) {
            addCriterion("HOUSE_FILE_SN <", value, "houseFileSn");
            return this;
        }

        public Criteria andHouseFileSnLessThanOrEqualTo(Long value) {
            addCriterion("HOUSE_FILE_SN <=", value, "houseFileSn");
            return this;
        }

        public Criteria andHouseFileSnIn(List values) {
            addCriterion("HOUSE_FILE_SN in", values, "houseFileSn");
            return this;
        }

        public Criteria andHouseFileSnNotIn(List values) {
            addCriterion("HOUSE_FILE_SN not in", values, "houseFileSn");
            return this;
        }

        public Criteria andHouseFileSnBetween(Long value1, Long value2) {
            addCriterion("HOUSE_FILE_SN between", value1, value2, "houseFileSn");
            return this;
        }

        public Criteria andHouseFileSnNotBetween(Long value1, Long value2) {
            addCriterion("HOUSE_FILE_SN not between", value1, value2, "houseFileSn");
            return this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("USER_ID =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("USER_ID <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("USER_ID >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("USER_ID >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("USER_ID <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("USER_ID <=", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List values) {
            addCriterion("USER_ID in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List values) {
            addCriterion("USER_ID not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("TYPE =", value, "type");
            return this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("TYPE <>", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("TYPE >", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("TYPE >=", value, "type");
            return this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("TYPE <", value, "type");
            return this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("TYPE <=", value, "type");
            return this;
        }

        public Criteria andTypeIn(List values) {
            addCriterion("TYPE in", values, "type");
            return this;
        }

        public Criteria andTypeNotIn(List values) {
            addCriterion("TYPE not in", values, "type");
            return this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("AREA is null");
            return this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("AREA is not null");
            return this;
        }

        public Criteria andAreaEqualTo(BigDecimal value) {
            addCriterion("AREA =", value, "area");
            return this;
        }

        public Criteria andAreaNotEqualTo(BigDecimal value) {
            addCriterion("AREA <>", value, "area");
            return this;
        }

        public Criteria andAreaGreaterThan(BigDecimal value) {
            addCriterion("AREA >", value, "area");
            return this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AREA >=", value, "area");
            return this;
        }

        public Criteria andAreaLessThan(BigDecimal value) {
            addCriterion("AREA <", value, "area");
            return this;
        }

        public Criteria andAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AREA <=", value, "area");
            return this;
        }

        public Criteria andAreaIn(List values) {
            addCriterion("AREA in", values, "area");
            return this;
        }

        public Criteria andAreaNotIn(List values) {
            addCriterion("AREA not in", values, "area");
            return this;
        }

        public Criteria andAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AREA between", value1, value2, "area");
            return this;
        }

        public Criteria andAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AREA not between", value1, value2, "area");
            return this;
        }

        public Criteria andPicFileSnIsNull() {
            addCriterion("PIC_FILE_SN is null");
            return this;
        }

        public Criteria andPicFileSnIsNotNull() {
            addCriterion("PIC_FILE_SN is not null");
            return this;
        }

        public Criteria andPicFileSnEqualTo(Long value) {
            addCriterion("PIC_FILE_SN =", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnNotEqualTo(Long value) {
            addCriterion("PIC_FILE_SN <>", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnGreaterThan(Long value) {
            addCriterion("PIC_FILE_SN >", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("PIC_FILE_SN >=", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnLessThan(Long value) {
            addCriterion("PIC_FILE_SN <", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnLessThanOrEqualTo(Long value) {
            addCriterion("PIC_FILE_SN <=", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnIn(List values) {
            addCriterion("PIC_FILE_SN in", values, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnNotIn(List values) {
            addCriterion("PIC_FILE_SN not in", values, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnBetween(Long value1, Long value2) {
            addCriterion("PIC_FILE_SN between", value1, value2, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnNotBetween(Long value1, Long value2) {
            addCriterion("PIC_FILE_SN not between", value1, value2, "picFileSn");
            return this;
        }

        public Criteria andRoomNumIsNull() {
            addCriterion("ROOM_NUM is null");
            return this;
        }

        public Criteria andRoomNumIsNotNull() {
            addCriterion("ROOM_NUM is not null");
            return this;
        }

        public Criteria andRoomNumEqualTo(Integer value) {
            addCriterion("ROOM_NUM =", value, "roomNum");
            return this;
        }

        public Criteria andRoomNumNotEqualTo(Integer value) {
            addCriterion("ROOM_NUM <>", value, "roomNum");
            return this;
        }

        public Criteria andRoomNumGreaterThan(Integer value) {
            addCriterion("ROOM_NUM >", value, "roomNum");
            return this;
        }

        public Criteria andRoomNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ROOM_NUM >=", value, "roomNum");
            return this;
        }

        public Criteria andRoomNumLessThan(Integer value) {
            addCriterion("ROOM_NUM <", value, "roomNum");
            return this;
        }

        public Criteria andRoomNumLessThanOrEqualTo(Integer value) {
            addCriterion("ROOM_NUM <=", value, "roomNum");
            return this;
        }

        public Criteria andRoomNumIn(List values) {
            addCriterion("ROOM_NUM in", values, "roomNum");
            return this;
        }

        public Criteria andRoomNumNotIn(List values) {
            addCriterion("ROOM_NUM not in", values, "roomNum");
            return this;
        }

        public Criteria andRoomNumBetween(Integer value1, Integer value2) {
            addCriterion("ROOM_NUM between", value1, value2, "roomNum");
            return this;
        }

        public Criteria andRoomNumNotBetween(Integer value1, Integer value2) {
            addCriterion("ROOM_NUM not between", value1, value2, "roomNum");
            return this;
        }

        public Criteria andLivingRoomNumIsNull() {
            addCriterion("LIVING_ROOM_NUM is null");
            return this;
        }

        public Criteria andLivingRoomNumIsNotNull() {
            addCriterion("LIVING_ROOM_NUM is not null");
            return this;
        }

        public Criteria andLivingRoomNumEqualTo(Integer value) {
            addCriterion("LIVING_ROOM_NUM =", value, "livingRoomNum");
            return this;
        }

        public Criteria andLivingRoomNumNotEqualTo(Integer value) {
            addCriterion("LIVING_ROOM_NUM <>", value, "livingRoomNum");
            return this;
        }

        public Criteria andLivingRoomNumGreaterThan(Integer value) {
            addCriterion("LIVING_ROOM_NUM >", value, "livingRoomNum");
            return this;
        }

        public Criteria andLivingRoomNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("LIVING_ROOM_NUM >=", value, "livingRoomNum");
            return this;
        }

        public Criteria andLivingRoomNumLessThan(Integer value) {
            addCriterion("LIVING_ROOM_NUM <", value, "livingRoomNum");
            return this;
        }

        public Criteria andLivingRoomNumLessThanOrEqualTo(Integer value) {
            addCriterion("LIVING_ROOM_NUM <=", value, "livingRoomNum");
            return this;
        }

        public Criteria andLivingRoomNumIn(List values) {
            addCriterion("LIVING_ROOM_NUM in", values, "livingRoomNum");
            return this;
        }

        public Criteria andLivingRoomNumNotIn(List values) {
            addCriterion("LIVING_ROOM_NUM not in", values, "livingRoomNum");
            return this;
        }

        public Criteria andLivingRoomNumBetween(Integer value1, Integer value2) {
            addCriterion("LIVING_ROOM_NUM between", value1, value2, "livingRoomNum");
            return this;
        }

        public Criteria andLivingRoomNumNotBetween(Integer value1, Integer value2) {
            addCriterion("LIVING_ROOM_NUM not between", value1, value2, "livingRoomNum");
            return this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("PROVINCE is null");
            return this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("PROVINCE is not null");
            return this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("PROVINCE =", value, "province");
            return this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("PROVINCE <>", value, "province");
            return this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("PROVINCE >", value, "province");
            return this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("PROVINCE >=", value, "province");
            return this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("PROVINCE <", value, "province");
            return this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("PROVINCE <=", value, "province");
            return this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("PROVINCE like", value, "province");
            return this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("PROVINCE not like", value, "province");
            return this;
        }

        public Criteria andProvinceIn(List values) {
            addCriterion("PROVINCE in", values, "province");
            return this;
        }

        public Criteria andProvinceNotIn(List values) {
            addCriterion("PROVINCE not in", values, "province");
            return this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("PROVINCE between", value1, value2, "province");
            return this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("PROVINCE not between", value1, value2, "province");
            return this;
        }

        public Criteria andCityIsNull() {
            addCriterion("CITY is null");
            return this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("CITY is not null");
            return this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("CITY =", value, "city");
            return this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("CITY <>", value, "city");
            return this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("CITY >", value, "city");
            return this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("CITY >=", value, "city");
            return this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("CITY <", value, "city");
            return this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("CITY <=", value, "city");
            return this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("CITY like", value, "city");
            return this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("CITY not like", value, "city");
            return this;
        }

        public Criteria andCityIn(List values) {
            addCriterion("CITY in", values, "city");
            return this;
        }

        public Criteria andCityNotIn(List values) {
            addCriterion("CITY not in", values, "city");
            return this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("CITY between", value1, value2, "city");
            return this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("CITY not between", value1, value2, "city");
            return this;
        }

        public Criteria andStreetIsNull() {
            addCriterion("STREET is null");
            return this;
        }

        public Criteria andStreetIsNotNull() {
            addCriterion("STREET is not null");
            return this;
        }

        public Criteria andStreetEqualTo(String value) {
            addCriterion("STREET =", value, "street");
            return this;
        }

        public Criteria andStreetNotEqualTo(String value) {
            addCriterion("STREET <>", value, "street");
            return this;
        }

        public Criteria andStreetGreaterThan(String value) {
            addCriterion("STREET >", value, "street");
            return this;
        }

        public Criteria andStreetGreaterThanOrEqualTo(String value) {
            addCriterion("STREET >=", value, "street");
            return this;
        }

        public Criteria andStreetLessThan(String value) {
            addCriterion("STREET <", value, "street");
            return this;
        }

        public Criteria andStreetLessThanOrEqualTo(String value) {
            addCriterion("STREET <=", value, "street");
            return this;
        }

        public Criteria andStreetLike(String value) {
            addCriterion("STREET like", value, "street");
            return this;
        }

        public Criteria andStreetNotLike(String value) {
            addCriterion("STREET not like", value, "street");
            return this;
        }

        public Criteria andStreetIn(List values) {
            addCriterion("STREET in", values, "street");
            return this;
        }

        public Criteria andStreetNotIn(List values) {
            addCriterion("STREET not in", values, "street");
            return this;
        }

        public Criteria andStreetBetween(String value1, String value2) {
            addCriterion("STREET between", value1, value2, "street");
            return this;
        }

        public Criteria andStreetNotBetween(String value1, String value2) {
            addCriterion("STREET not between", value1, value2, "street");
            return this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("REGION is null");
            return this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("REGION is not null");
            return this;
        }

        public Criteria andRegionEqualTo(String value) {
            addCriterion("REGION =", value, "region");
            return this;
        }

        public Criteria andRegionNotEqualTo(String value) {
            addCriterion("REGION <>", value, "region");
            return this;
        }

        public Criteria andRegionGreaterThan(String value) {
            addCriterion("REGION >", value, "region");
            return this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(String value) {
            addCriterion("REGION >=", value, "region");
            return this;
        }

        public Criteria andRegionLessThan(String value) {
            addCriterion("REGION <", value, "region");
            return this;
        }

        public Criteria andRegionLessThanOrEqualTo(String value) {
            addCriterion("REGION <=", value, "region");
            return this;
        }

        public Criteria andRegionLike(String value) {
            addCriterion("REGION like", value, "region");
            return this;
        }

        public Criteria andRegionNotLike(String value) {
            addCriterion("REGION not like", value, "region");
            return this;
        }

        public Criteria andRegionIn(List values) {
            addCriterion("REGION in", values, "region");
            return this;
        }

        public Criteria andRegionNotIn(List values) {
            addCriterion("REGION not in", values, "region");
            return this;
        }

        public Criteria andRegionBetween(String value1, String value2) {
            addCriterion("REGION between", value1, value2, "region");
            return this;
        }

        public Criteria andRegionNotBetween(String value1, String value2) {
            addCriterion("REGION not between", value1, value2, "region");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("STATUS in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("STATUS not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return this;
        }

        public Criteria andBuildingNameIsNull() {
            addCriterion("BUILDING_NAME is null");
            return this;
        }

        public Criteria andBuildingNameIsNotNull() {
            addCriterion("BUILDING_NAME is not null");
            return this;
        }

        public Criteria andBuildingNameEqualTo(String value) {
            addCriterion("BUILDING_NAME =", value, "buildingName");
            return this;
        }

        public Criteria andBuildingNameNotEqualTo(String value) {
            addCriterion("BUILDING_NAME <>", value, "buildingName");
            return this;
        }

        public Criteria andBuildingNameGreaterThan(String value) {
            addCriterion("BUILDING_NAME >", value, "buildingName");
            return this;
        }

        public Criteria andBuildingNameGreaterThanOrEqualTo(String value) {
            addCriterion("BUILDING_NAME >=", value, "buildingName");
            return this;
        }

        public Criteria andBuildingNameLessThan(String value) {
            addCriterion("BUILDING_NAME <", value, "buildingName");
            return this;
        }

        public Criteria andBuildingNameLessThanOrEqualTo(String value) {
            addCriterion("BUILDING_NAME <=", value, "buildingName");
            return this;
        }

        public Criteria andBuildingNameLike(String value) {
            addCriterion("BUILDING_NAME like", value, "buildingName");
            return this;
        }

        public Criteria andBuildingNameNotLike(String value) {
            addCriterion("BUILDING_NAME not like", value, "buildingName");
            return this;
        }

        public Criteria andBuildingNameIn(List values) {
            addCriterion("BUILDING_NAME in", values, "buildingName");
            return this;
        }

        public Criteria andBuildingNameNotIn(List values) {
            addCriterion("BUILDING_NAME not in", values, "buildingName");
            return this;
        }

        public Criteria andBuildingNameBetween(String value1, String value2) {
            addCriterion("BUILDING_NAME between", value1, value2, "buildingName");
            return this;
        }

        public Criteria andBuildingNameNotBetween(String value1, String value2) {
            addCriterion("BUILDING_NAME not between", value1, value2, "buildingName");
            return this;
        }

        public Criteria andAdderSnIsNull() {
            addCriterion("ADDER_SN is null");
            return this;
        }

        public Criteria andAdderSnIsNotNull() {
            addCriterion("ADDER_SN is not null");
            return this;
        }

        public Criteria andAdderSnEqualTo(Long value) {
            addCriterion("ADDER_SN =", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotEqualTo(Long value) {
            addCriterion("ADDER_SN <>", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThan(Long value) {
            addCriterion("ADDER_SN >", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN >=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThan(Long value) {
            addCriterion("ADDER_SN <", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN <=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnIn(List values) {
            addCriterion("ADDER_SN in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotIn(List values) {
            addCriterion("ADDER_SN not in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN not between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderNameIsNull() {
            addCriterion("ADDER_NAME is null");
            return this;
        }

        public Criteria andAdderNameIsNotNull() {
            addCriterion("ADDER_NAME is not null");
            return this;
        }

        public Criteria andAdderNameEqualTo(String value) {
            addCriterion("ADDER_NAME =", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotEqualTo(String value) {
            addCriterion("ADDER_NAME <>", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThan(String value) {
            addCriterion("ADDER_NAME >", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME >=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThan(String value) {
            addCriterion("ADDER_NAME <", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME <=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLike(String value) {
            addCriterion("ADDER_NAME like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotLike(String value) {
            addCriterion("ADDER_NAME not like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameIn(List values) {
            addCriterion("ADDER_NAME in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameNotIn(List values) {
            addCriterion("ADDER_NAME not in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameBetween(String value1, String value2) {
            addCriterion("ADDER_NAME between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAdderNameNotBetween(String value1, String value2) {
            addCriterion("ADDER_NAME not between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeIn(List values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeNotIn(List values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return this;
        }

        public Criteria andUpdaterSnIsNull() {
            addCriterion("UPDATER_SN is null");
            return this;
        }

        public Criteria andUpdaterSnIsNotNull() {
            addCriterion("UPDATER_SN is not null");
            return this;
        }

        public Criteria andUpdaterSnEqualTo(Long value) {
            addCriterion("UPDATER_SN =", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotEqualTo(Long value) {
            addCriterion("UPDATER_SN <>", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThan(Long value) {
            addCriterion("UPDATER_SN >", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN >=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThan(Long value) {
            addCriterion("UPDATER_SN <", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN <=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnIn(List values) {
            addCriterion("UPDATER_SN in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotIn(List values) {
            addCriterion("UPDATER_SN not in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN not between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterNameIsNull() {
            addCriterion("UPDATER_NAME is null");
            return this;
        }

        public Criteria andUpdaterNameIsNotNull() {
            addCriterion("UPDATER_NAME is not null");
            return this;
        }

        public Criteria andUpdaterNameEqualTo(String value) {
            addCriterion("UPDATER_NAME =", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotEqualTo(String value) {
            addCriterion("UPDATER_NAME <>", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThan(String value) {
            addCriterion("UPDATER_NAME >", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME >=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThan(String value) {
            addCriterion("UPDATER_NAME <", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME <=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLike(String value) {
            addCriterion("UPDATER_NAME like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotLike(String value) {
            addCriterion("UPDATER_NAME not like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameIn(List values) {
            addCriterion("UPDATER_NAME in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotIn(List values) {
            addCriterion("UPDATER_NAME not in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME not between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }
    }
}