package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.math.BigDecimal;
import java.util.Date;

@Xss
@SqlMap(Name = "fnt_house_upload", Class = FntHouseUpload.class)
public class FntHouseUpload<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.HOUSE_NAME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private String houseName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.HOUSE_FILE_SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private Long houseFileSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.USER_ID
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private Long userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.TYPE
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private Integer type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.AREA
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private BigDecimal area;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.PIC_FILE_SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private Long picFileSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.ROOM_NUM
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private Integer roomNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.LIVING_ROOM_NUM
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private Integer livingRoomNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.PROVINCE
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private String province;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.CITY
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private String city;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.STREET
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private String street;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.REGION
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private String region;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.STATUS
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.BUILDING_NAME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private String buildingName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.ADDER_SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.ADDER_NAME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.ADD_TIME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.UPDATER_SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.UPDATER_NAME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.UPDATE_TIME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.encryptSn
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.SN
     *
     * @return the value of fnt_house_upload.SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.SN
     *
     * @param sn the value for fnt_house_upload.SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.HOUSE_NAME
     *
     * @return the value of fnt_house_upload.HOUSE_NAME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public String getHouseName() {
        return houseName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.HOUSE_NAME
     *
     * @param houseName the value for fnt_house_upload.HOUSE_NAME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setHouseName(String houseName) {
        this.houseName = houseName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.HOUSE_FILE_SN
     *
     * @return the value of fnt_house_upload.HOUSE_FILE_SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public Long getHouseFileSn() {
        return houseFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.HOUSE_FILE_SN
     *
     * @param houseFileSn the value for fnt_house_upload.HOUSE_FILE_SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setHouseFileSn(Long houseFileSn) {
        this.houseFileSn = houseFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.USER_ID
     *
     * @return the value of fnt_house_upload.USER_ID
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.USER_ID
     *
     * @param userId the value for fnt_house_upload.USER_ID
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.TYPE
     *
     * @return the value of fnt_house_upload.TYPE
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.TYPE
     *
     * @param type the value for fnt_house_upload.TYPE
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.AREA
     *
     * @return the value of fnt_house_upload.AREA
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public BigDecimal getArea() {
        return area;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.AREA
     *
     * @param area the value for fnt_house_upload.AREA
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setArea(BigDecimal area) {
        this.area = area;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.PIC_FILE_SN
     *
     * @return the value of fnt_house_upload.PIC_FILE_SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public Long getPicFileSn() {
        return picFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.PIC_FILE_SN
     *
     * @param picFileSn the value for fnt_house_upload.PIC_FILE_SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setPicFileSn(Long picFileSn) {
        this.picFileSn = picFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.ROOM_NUM
     *
     * @return the value of fnt_house_upload.ROOM_NUM
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public Integer getRoomNum() {
        return roomNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.ROOM_NUM
     *
     * @param roomNum the value for fnt_house_upload.ROOM_NUM
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setRoomNum(Integer roomNum) {
        this.roomNum = roomNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.LIVING_ROOM_NUM
     *
     * @return the value of fnt_house_upload.LIVING_ROOM_NUM
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public Integer getLivingRoomNum() {
        return livingRoomNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.LIVING_ROOM_NUM
     *
     * @param livingRoomNum the value for fnt_house_upload.LIVING_ROOM_NUM
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setLivingRoomNum(Integer livingRoomNum) {
        this.livingRoomNum = livingRoomNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.PROVINCE
     *
     * @return the value of fnt_house_upload.PROVINCE
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.PROVINCE
     *
     * @param province the value for fnt_house_upload.PROVINCE
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.CITY
     *
     * @return the value of fnt_house_upload.CITY
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.CITY
     *
     * @param city the value for fnt_house_upload.CITY
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.STREET
     *
     * @return the value of fnt_house_upload.STREET
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.STREET
     *
     * @param street the value for fnt_house_upload.STREET
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.REGION
     *
     * @return the value of fnt_house_upload.REGION
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.REGION
     *
     * @param region the value for fnt_house_upload.REGION
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.STATUS
     *
     * @return the value of fnt_house_upload.STATUS
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.STATUS
     *
     * @param status the value for fnt_house_upload.STATUS
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.BUILDING_NAME
     *
     * @return the value of fnt_house_upload.BUILDING_NAME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.BUILDING_NAME
     *
     * @param buildingName the value for fnt_house_upload.BUILDING_NAME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.ADDER_SN
     *
     * @return the value of fnt_house_upload.ADDER_SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.ADDER_SN
     *
     * @param adderSn the value for fnt_house_upload.ADDER_SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.ADDER_NAME
     *
     * @return the value of fnt_house_upload.ADDER_NAME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.ADDER_NAME
     *
     * @param adderName the value for fnt_house_upload.ADDER_NAME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.ADD_TIME
     *
     * @return the value of fnt_house_upload.ADD_TIME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.ADD_TIME
     *
     * @param addTime the value for fnt_house_upload.ADD_TIME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.UPDATER_SN
     *
     * @return the value of fnt_house_upload.UPDATER_SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.UPDATER_SN
     *
     * @param updaterSn the value for fnt_house_upload.UPDATER_SN
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.UPDATER_NAME
     *
     * @return the value of fnt_house_upload.UPDATER_NAME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.UPDATER_NAME
     *
     * @param updaterName the value for fnt_house_upload.UPDATER_NAME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.UPDATE_TIME
     *
     * @return the value of fnt_house_upload.UPDATE_TIME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.UPDATE_TIME
     *
     * @param updateTime the value for fnt_house_upload.UPDATE_TIME
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.encryptSn
     *
     * @return the value of fnt_house_upload.encryptSn
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.encryptSn
     *
     * @param encryptSn the value for fnt_house_upload.encryptSn
     *
     * @ibatorgenerated Tue Dec 13 19:53:24 CST 2016
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}