package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.math.BigDecimal;
import java.util.Date;

@Xss
@SqlMap(Name = "fnt_product", Class = FntProduct.class)
public class FntProduct<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.BRAND
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String brand;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.PRICE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private BigDecimal price;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.MATERIA
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String materia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.COLOR
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String color;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.SPEC_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String specName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.SPEC_SIZE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String specSize;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.PARAMETER
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String parameter;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.GROSS_WEIGHT
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private BigDecimal grossWeight;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.PIC_FILE_SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private Long picFileSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.CATEGORY_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String categoryName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.CATEGORY_CODE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String categoryCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.STYLE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String style;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.MODEL_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String modelName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.MODEL_FILE_SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private Long modelFileSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.DESIGN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String design;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.IS_WITH_CORE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private Integer isWithCore;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.FILLER
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String filler;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.STATUS
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.SHELVES_TIME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private Date shelvesTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.REMARK
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.ADDER_SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.ADDER_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.ADD_TIME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.UPDATER_SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.UPDATER_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.UPDATE_TIME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.MODEL_FILE_VERSION
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private Integer modelFileVersion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.TYPE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private Integer type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_product.encryptSn
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.SN
     *
     * @return the value of fnt_product.SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.SN
     *
     * @param sn the value for fnt_product.SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.NAME
     *
     * @return the value of fnt_product.NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.NAME
     *
     * @param name the value for fnt_product.NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.BRAND
     *
     * @return the value of fnt_product.BRAND
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.BRAND
     *
     * @param brand the value for fnt_product.BRAND
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.PRICE
     *
     * @return the value of fnt_product.PRICE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.PRICE
     *
     * @param price the value for fnt_product.PRICE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.MATERIA
     *
     * @return the value of fnt_product.MATERIA
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getMateria() {
        return materia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.MATERIA
     *
     * @param materia the value for fnt_product.MATERIA
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setMateria(String materia) {
        this.materia = materia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.COLOR
     *
     * @return the value of fnt_product.COLOR
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.COLOR
     *
     * @param color the value for fnt_product.COLOR
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.SPEC_NAME
     *
     * @return the value of fnt_product.SPEC_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getSpecName() {
        return specName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.SPEC_NAME
     *
     * @param specName the value for fnt_product.SPEC_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setSpecName(String specName) {
        this.specName = specName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.SPEC_SIZE
     *
     * @return the value of fnt_product.SPEC_SIZE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getSpecSize() {
        return specSize;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.SPEC_SIZE
     *
     * @param specSize the value for fnt_product.SPEC_SIZE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setSpecSize(String specSize) {
        this.specSize = specSize;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.PARAMETER
     *
     * @return the value of fnt_product.PARAMETER
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getParameter() {
        return parameter;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.PARAMETER
     *
     * @param parameter the value for fnt_product.PARAMETER
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.GROSS_WEIGHT
     *
     * @return the value of fnt_product.GROSS_WEIGHT
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public BigDecimal getGrossWeight() {
        return grossWeight;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.GROSS_WEIGHT
     *
     * @param grossWeight the value for fnt_product.GROSS_WEIGHT
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setGrossWeight(BigDecimal grossWeight) {
        this.grossWeight = grossWeight;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.PIC_FILE_SN
     *
     * @return the value of fnt_product.PIC_FILE_SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public Long getPicFileSn() {
        return picFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.PIC_FILE_SN
     *
     * @param picFileSn the value for fnt_product.PIC_FILE_SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setPicFileSn(Long picFileSn) {
        this.picFileSn = picFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.CATEGORY_NAME
     *
     * @return the value of fnt_product.CATEGORY_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.CATEGORY_NAME
     *
     * @param categoryName the value for fnt_product.CATEGORY_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.CATEGORY_CODE
     *
     * @return the value of fnt_product.CATEGORY_CODE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.CATEGORY_CODE
     *
     * @param categoryCode the value for fnt_product.CATEGORY_CODE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.STYLE
     *
     * @return the value of fnt_product.STYLE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.STYLE
     *
     * @param style the value for fnt_product.STYLE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setStyle(String style) {
        this.style = style;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.MODEL_NAME
     *
     * @return the value of fnt_product.MODEL_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.MODEL_NAME
     *
     * @param modelName the value for fnt_product.MODEL_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.MODEL_FILE_SN
     *
     * @return the value of fnt_product.MODEL_FILE_SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public Long getModelFileSn() {
        return modelFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.MODEL_FILE_SN
     *
     * @param modelFileSn the value for fnt_product.MODEL_FILE_SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setModelFileSn(Long modelFileSn) {
        this.modelFileSn = modelFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.DESIGN
     *
     * @return the value of fnt_product.DESIGN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getDesign() {
        return design;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.DESIGN
     *
     * @param design the value for fnt_product.DESIGN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setDesign(String design) {
        this.design = design;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.IS_WITH_CORE
     *
     * @return the value of fnt_product.IS_WITH_CORE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public Integer getIsWithCore() {
        return isWithCore;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.IS_WITH_CORE
     *
     * @param isWithCore the value for fnt_product.IS_WITH_CORE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setIsWithCore(Integer isWithCore) {
        this.isWithCore = isWithCore;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.FILLER
     *
     * @return the value of fnt_product.FILLER
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getFiller() {
        return filler;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.FILLER
     *
     * @param filler the value for fnt_product.FILLER
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setFiller(String filler) {
        this.filler = filler;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.STATUS
     *
     * @return the value of fnt_product.STATUS
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.STATUS
     *
     * @param status the value for fnt_product.STATUS
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.SHELVES_TIME
     *
     * @return the value of fnt_product.SHELVES_TIME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public Date getShelvesTime() {
        return shelvesTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.SHELVES_TIME
     *
     * @param shelvesTime the value for fnt_product.SHELVES_TIME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setShelvesTime(Date shelvesTime) {
        this.shelvesTime = shelvesTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.REMARK
     *
     * @return the value of fnt_product.REMARK
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.REMARK
     *
     * @param remark the value for fnt_product.REMARK
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.ADDER_SN
     *
     * @return the value of fnt_product.ADDER_SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.ADDER_SN
     *
     * @param adderSn the value for fnt_product.ADDER_SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.ADDER_NAME
     *
     * @return the value of fnt_product.ADDER_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.ADDER_NAME
     *
     * @param adderName the value for fnt_product.ADDER_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.ADD_TIME
     *
     * @return the value of fnt_product.ADD_TIME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.ADD_TIME
     *
     * @param addTime the value for fnt_product.ADD_TIME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.UPDATER_SN
     *
     * @return the value of fnt_product.UPDATER_SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.UPDATER_SN
     *
     * @param updaterSn the value for fnt_product.UPDATER_SN
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.UPDATER_NAME
     *
     * @return the value of fnt_product.UPDATER_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.UPDATER_NAME
     *
     * @param updaterName the value for fnt_product.UPDATER_NAME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.UPDATE_TIME
     *
     * @return the value of fnt_product.UPDATE_TIME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.UPDATE_TIME
     *
     * @param updateTime the value for fnt_product.UPDATE_TIME
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.MODEL_FILE_VERSION
     *
     * @return the value of fnt_product.MODEL_FILE_VERSION
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public Integer getModelFileVersion() {
        return modelFileVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.MODEL_FILE_VERSION
     *
     * @param modelFileVersion the value for fnt_product.MODEL_FILE_VERSION
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setModelFileVersion(Integer modelFileVersion) {
        this.modelFileVersion = modelFileVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.TYPE
     *
     * @return the value of fnt_product.TYPE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.TYPE
     *
     * @param type the value for fnt_product.TYPE
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_product.encryptSn
     *
     * @return the value of fnt_product.encryptSn
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_product.encryptSn
     *
     * @param encryptSn the value for fnt_product.encryptSn
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}