package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "fnt_product", Class = FntProduct.class)
public class FntProductCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public FntProductCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public FntProductCriteria(FntProductCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public FntProductCriteria(Object record, FntProductCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table fnt_product
     *
     * @ibatorgenerated Mon Dec 12 10:15:56 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSnIsNull() {
            addCriterion("SN is null");
            return this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("SN is not null");
            return this;
        }

        public Criteria andSnEqualTo(Long value) {
            addCriterion("SN =", value, "sn");
            return this;
        }

        public Criteria andSnNotEqualTo(Long value) {
            addCriterion("SN <>", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThan(Long value) {
            addCriterion("SN >", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SN >=", value, "sn");
            return this;
        }

        public Criteria andSnLessThan(Long value) {
            addCriterion("SN <", value, "sn");
            return this;
        }

        public Criteria andSnLessThanOrEqualTo(Long value) {
            addCriterion("SN <=", value, "sn");
            return this;
        }

        public Criteria andSnIn(List values) {
            addCriterion("SN in", values, "sn");
            return this;
        }

        public Criteria andSnNotIn(List values) {
            addCriterion("SN not in", values, "sn");
            return this;
        }

        public Criteria andSnBetween(Long value1, Long value2) {
            addCriterion("SN between", value1, value2, "sn");
            return this;
        }

        public Criteria andSnNotBetween(Long value1, Long value2) {
            addCriterion("SN not between", value1, value2, "sn");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("NAME in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("NAME not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return this;
        }

        public Criteria andBrandIsNull() {
            addCriterion("BRAND is null");
            return this;
        }

        public Criteria andBrandIsNotNull() {
            addCriterion("BRAND is not null");
            return this;
        }

        public Criteria andBrandEqualTo(String value) {
            addCriterion("BRAND =", value, "brand");
            return this;
        }

        public Criteria andBrandNotEqualTo(String value) {
            addCriterion("BRAND <>", value, "brand");
            return this;
        }

        public Criteria andBrandGreaterThan(String value) {
            addCriterion("BRAND >", value, "brand");
            return this;
        }

        public Criteria andBrandGreaterThanOrEqualTo(String value) {
            addCriterion("BRAND >=", value, "brand");
            return this;
        }

        public Criteria andBrandLessThan(String value) {
            addCriterion("BRAND <", value, "brand");
            return this;
        }

        public Criteria andBrandLessThanOrEqualTo(String value) {
            addCriterion("BRAND <=", value, "brand");
            return this;
        }

        public Criteria andBrandLike(String value) {
            addCriterion("BRAND like", value, "brand");
            return this;
        }

        public Criteria andBrandNotLike(String value) {
            addCriterion("BRAND not like", value, "brand");
            return this;
        }

        public Criteria andBrandIn(List values) {
            addCriterion("BRAND in", values, "brand");
            return this;
        }

        public Criteria andBrandNotIn(List values) {
            addCriterion("BRAND not in", values, "brand");
            return this;
        }

        public Criteria andBrandBetween(String value1, String value2) {
            addCriterion("BRAND between", value1, value2, "brand");
            return this;
        }

        public Criteria andBrandNotBetween(String value1, String value2) {
            addCriterion("BRAND not between", value1, value2, "brand");
            return this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("PRICE is null");
            return this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("PRICE is not null");
            return this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("PRICE =", value, "price");
            return this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("PRICE <>", value, "price");
            return this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("PRICE >", value, "price");
            return this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PRICE >=", value, "price");
            return this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("PRICE <", value, "price");
            return this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PRICE <=", value, "price");
            return this;
        }

        public Criteria andPriceIn(List values) {
            addCriterion("PRICE in", values, "price");
            return this;
        }

        public Criteria andPriceNotIn(List values) {
            addCriterion("PRICE not in", values, "price");
            return this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRICE between", value1, value2, "price");
            return this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRICE not between", value1, value2, "price");
            return this;
        }

        public Criteria andMateriaIsNull() {
            addCriterion("MATERIA is null");
            return this;
        }

        public Criteria andMateriaIsNotNull() {
            addCriterion("MATERIA is not null");
            return this;
        }

        public Criteria andMateriaEqualTo(String value) {
            addCriterion("MATERIA =", value, "materia");
            return this;
        }

        public Criteria andMateriaNotEqualTo(String value) {
            addCriterion("MATERIA <>", value, "materia");
            return this;
        }

        public Criteria andMateriaGreaterThan(String value) {
            addCriterion("MATERIA >", value, "materia");
            return this;
        }

        public Criteria andMateriaGreaterThanOrEqualTo(String value) {
            addCriterion("MATERIA >=", value, "materia");
            return this;
        }

        public Criteria andMateriaLessThan(String value) {
            addCriterion("MATERIA <", value, "materia");
            return this;
        }

        public Criteria andMateriaLessThanOrEqualTo(String value) {
            addCriterion("MATERIA <=", value, "materia");
            return this;
        }

        public Criteria andMateriaLike(String value) {
            addCriterion("MATERIA like", value, "materia");
            return this;
        }

        public Criteria andMateriaNotLike(String value) {
            addCriterion("MATERIA not like", value, "materia");
            return this;
        }

        public Criteria andMateriaIn(List values) {
            addCriterion("MATERIA in", values, "materia");
            return this;
        }

        public Criteria andMateriaNotIn(List values) {
            addCriterion("MATERIA not in", values, "materia");
            return this;
        }

        public Criteria andMateriaBetween(String value1, String value2) {
            addCriterion("MATERIA between", value1, value2, "materia");
            return this;
        }

        public Criteria andMateriaNotBetween(String value1, String value2) {
            addCriterion("MATERIA not between", value1, value2, "materia");
            return this;
        }

        public Criteria andColorIsNull() {
            addCriterion("COLOR is null");
            return this;
        }

        public Criteria andColorIsNotNull() {
            addCriterion("COLOR is not null");
            return this;
        }

        public Criteria andColorEqualTo(String value) {
            addCriterion("COLOR =", value, "color");
            return this;
        }

        public Criteria andColorNotEqualTo(String value) {
            addCriterion("COLOR <>", value, "color");
            return this;
        }

        public Criteria andColorGreaterThan(String value) {
            addCriterion("COLOR >", value, "color");
            return this;
        }

        public Criteria andColorGreaterThanOrEqualTo(String value) {
            addCriterion("COLOR >=", value, "color");
            return this;
        }

        public Criteria andColorLessThan(String value) {
            addCriterion("COLOR <", value, "color");
            return this;
        }

        public Criteria andColorLessThanOrEqualTo(String value) {
            addCriterion("COLOR <=", value, "color");
            return this;
        }

        public Criteria andColorLike(String value) {
            addCriterion("COLOR like", value, "color");
            return this;
        }

        public Criteria andColorNotLike(String value) {
            addCriterion("COLOR not like", value, "color");
            return this;
        }

        public Criteria andColorIn(List values) {
            addCriterion("COLOR in", values, "color");
            return this;
        }

        public Criteria andColorNotIn(List values) {
            addCriterion("COLOR not in", values, "color");
            return this;
        }

        public Criteria andColorBetween(String value1, String value2) {
            addCriterion("COLOR between", value1, value2, "color");
            return this;
        }

        public Criteria andColorNotBetween(String value1, String value2) {
            addCriterion("COLOR not between", value1, value2, "color");
            return this;
        }

        public Criteria andSpecNameIsNull() {
            addCriterion("SPEC_NAME is null");
            return this;
        }

        public Criteria andSpecNameIsNotNull() {
            addCriterion("SPEC_NAME is not null");
            return this;
        }

        public Criteria andSpecNameEqualTo(String value) {
            addCriterion("SPEC_NAME =", value, "specName");
            return this;
        }

        public Criteria andSpecNameNotEqualTo(String value) {
            addCriterion("SPEC_NAME <>", value, "specName");
            return this;
        }

        public Criteria andSpecNameGreaterThan(String value) {
            addCriterion("SPEC_NAME >", value, "specName");
            return this;
        }

        public Criteria andSpecNameGreaterThanOrEqualTo(String value) {
            addCriterion("SPEC_NAME >=", value, "specName");
            return this;
        }

        public Criteria andSpecNameLessThan(String value) {
            addCriterion("SPEC_NAME <", value, "specName");
            return this;
        }

        public Criteria andSpecNameLessThanOrEqualTo(String value) {
            addCriterion("SPEC_NAME <=", value, "specName");
            return this;
        }

        public Criteria andSpecNameLike(String value) {
            addCriterion("SPEC_NAME like", value, "specName");
            return this;
        }

        public Criteria andSpecNameNotLike(String value) {
            addCriterion("SPEC_NAME not like", value, "specName");
            return this;
        }

        public Criteria andSpecNameIn(List values) {
            addCriterion("SPEC_NAME in", values, "specName");
            return this;
        }

        public Criteria andSpecNameNotIn(List values) {
            addCriterion("SPEC_NAME not in", values, "specName");
            return this;
        }

        public Criteria andSpecNameBetween(String value1, String value2) {
            addCriterion("SPEC_NAME between", value1, value2, "specName");
            return this;
        }

        public Criteria andSpecNameNotBetween(String value1, String value2) {
            addCriterion("SPEC_NAME not between", value1, value2, "specName");
            return this;
        }

        public Criteria andSpecSizeIsNull() {
            addCriterion("SPEC_SIZE is null");
            return this;
        }

        public Criteria andSpecSizeIsNotNull() {
            addCriterion("SPEC_SIZE is not null");
            return this;
        }

        public Criteria andSpecSizeEqualTo(String value) {
            addCriterion("SPEC_SIZE =", value, "specSize");
            return this;
        }

        public Criteria andSpecSizeNotEqualTo(String value) {
            addCriterion("SPEC_SIZE <>", value, "specSize");
            return this;
        }

        public Criteria andSpecSizeGreaterThan(String value) {
            addCriterion("SPEC_SIZE >", value, "specSize");
            return this;
        }

        public Criteria andSpecSizeGreaterThanOrEqualTo(String value) {
            addCriterion("SPEC_SIZE >=", value, "specSize");
            return this;
        }

        public Criteria andSpecSizeLessThan(String value) {
            addCriterion("SPEC_SIZE <", value, "specSize");
            return this;
        }

        public Criteria andSpecSizeLessThanOrEqualTo(String value) {
            addCriterion("SPEC_SIZE <=", value, "specSize");
            return this;
        }

        public Criteria andSpecSizeLike(String value) {
            addCriterion("SPEC_SIZE like", value, "specSize");
            return this;
        }

        public Criteria andSpecSizeNotLike(String value) {
            addCriterion("SPEC_SIZE not like", value, "specSize");
            return this;
        }

        public Criteria andSpecSizeIn(List values) {
            addCriterion("SPEC_SIZE in", values, "specSize");
            return this;
        }

        public Criteria andSpecSizeNotIn(List values) {
            addCriterion("SPEC_SIZE not in", values, "specSize");
            return this;
        }

        public Criteria andSpecSizeBetween(String value1, String value2) {
            addCriterion("SPEC_SIZE between", value1, value2, "specSize");
            return this;
        }

        public Criteria andSpecSizeNotBetween(String value1, String value2) {
            addCriterion("SPEC_SIZE not between", value1, value2, "specSize");
            return this;
        }

        public Criteria andParameterIsNull() {
            addCriterion("PARAMETER is null");
            return this;
        }

        public Criteria andParameterIsNotNull() {
            addCriterion("PARAMETER is not null");
            return this;
        }

        public Criteria andParameterEqualTo(String value) {
            addCriterion("PARAMETER =", value, "parameter");
            return this;
        }

        public Criteria andParameterNotEqualTo(String value) {
            addCriterion("PARAMETER <>", value, "parameter");
            return this;
        }

        public Criteria andParameterGreaterThan(String value) {
            addCriterion("PARAMETER >", value, "parameter");
            return this;
        }

        public Criteria andParameterGreaterThanOrEqualTo(String value) {
            addCriterion("PARAMETER >=", value, "parameter");
            return this;
        }

        public Criteria andParameterLessThan(String value) {
            addCriterion("PARAMETER <", value, "parameter");
            return this;
        }

        public Criteria andParameterLessThanOrEqualTo(String value) {
            addCriterion("PARAMETER <=", value, "parameter");
            return this;
        }

        public Criteria andParameterLike(String value) {
            addCriterion("PARAMETER like", value, "parameter");
            return this;
        }

        public Criteria andParameterNotLike(String value) {
            addCriterion("PARAMETER not like", value, "parameter");
            return this;
        }

        public Criteria andParameterIn(List values) {
            addCriterion("PARAMETER in", values, "parameter");
            return this;
        }

        public Criteria andParameterNotIn(List values) {
            addCriterion("PARAMETER not in", values, "parameter");
            return this;
        }

        public Criteria andParameterBetween(String value1, String value2) {
            addCriterion("PARAMETER between", value1, value2, "parameter");
            return this;
        }

        public Criteria andParameterNotBetween(String value1, String value2) {
            addCriterion("PARAMETER not between", value1, value2, "parameter");
            return this;
        }

        public Criteria andGrossWeightIsNull() {
            addCriterion("GROSS_WEIGHT is null");
            return this;
        }

        public Criteria andGrossWeightIsNotNull() {
            addCriterion("GROSS_WEIGHT is not null");
            return this;
        }

        public Criteria andGrossWeightEqualTo(BigDecimal value) {
            addCriterion("GROSS_WEIGHT =", value, "grossWeight");
            return this;
        }

        public Criteria andGrossWeightNotEqualTo(BigDecimal value) {
            addCriterion("GROSS_WEIGHT <>", value, "grossWeight");
            return this;
        }

        public Criteria andGrossWeightGreaterThan(BigDecimal value) {
            addCriterion("GROSS_WEIGHT >", value, "grossWeight");
            return this;
        }

        public Criteria andGrossWeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GROSS_WEIGHT >=", value, "grossWeight");
            return this;
        }

        public Criteria andGrossWeightLessThan(BigDecimal value) {
            addCriterion("GROSS_WEIGHT <", value, "grossWeight");
            return this;
        }

        public Criteria andGrossWeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("GROSS_WEIGHT <=", value, "grossWeight");
            return this;
        }

        public Criteria andGrossWeightIn(List values) {
            addCriterion("GROSS_WEIGHT in", values, "grossWeight");
            return this;
        }

        public Criteria andGrossWeightNotIn(List values) {
            addCriterion("GROSS_WEIGHT not in", values, "grossWeight");
            return this;
        }

        public Criteria andGrossWeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GROSS_WEIGHT between", value1, value2, "grossWeight");
            return this;
        }

        public Criteria andGrossWeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GROSS_WEIGHT not between", value1, value2, "grossWeight");
            return this;
        }

        public Criteria andPicFileSnIsNull() {
            addCriterion("PIC_FILE_SN is null");
            return this;
        }

        public Criteria andPicFileSnIsNotNull() {
            addCriterion("PIC_FILE_SN is not null");
            return this;
        }

        public Criteria andPicFileSnEqualTo(Long value) {
            addCriterion("PIC_FILE_SN =", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnNotEqualTo(Long value) {
            addCriterion("PIC_FILE_SN <>", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnGreaterThan(Long value) {
            addCriterion("PIC_FILE_SN >", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("PIC_FILE_SN >=", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnLessThan(Long value) {
            addCriterion("PIC_FILE_SN <", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnLessThanOrEqualTo(Long value) {
            addCriterion("PIC_FILE_SN <=", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnIn(List values) {
            addCriterion("PIC_FILE_SN in", values, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnNotIn(List values) {
            addCriterion("PIC_FILE_SN not in", values, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnBetween(Long value1, Long value2) {
            addCriterion("PIC_FILE_SN between", value1, value2, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnNotBetween(Long value1, Long value2) {
            addCriterion("PIC_FILE_SN not between", value1, value2, "picFileSn");
            return this;
        }

        public Criteria andCategoryNameIsNull() {
            addCriterion("CATEGORY_NAME is null");
            return this;
        }

        public Criteria andCategoryNameIsNotNull() {
            addCriterion("CATEGORY_NAME is not null");
            return this;
        }

        public Criteria andCategoryNameEqualTo(String value) {
            addCriterion("CATEGORY_NAME =", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameNotEqualTo(String value) {
            addCriterion("CATEGORY_NAME <>", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameGreaterThan(String value) {
            addCriterion("CATEGORY_NAME >", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NAME >=", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameLessThan(String value) {
            addCriterion("CATEGORY_NAME <", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NAME <=", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameLike(String value) {
            addCriterion("CATEGORY_NAME like", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameNotLike(String value) {
            addCriterion("CATEGORY_NAME not like", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameIn(List values) {
            addCriterion("CATEGORY_NAME in", values, "categoryName");
            return this;
        }

        public Criteria andCategoryNameNotIn(List values) {
            addCriterion("CATEGORY_NAME not in", values, "categoryName");
            return this;
        }

        public Criteria andCategoryNameBetween(String value1, String value2) {
            addCriterion("CATEGORY_NAME between", value1, value2, "categoryName");
            return this;
        }

        public Criteria andCategoryNameNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_NAME not between", value1, value2, "categoryName");
            return this;
        }

        public Criteria andCategoryCodeIsNull() {
            addCriterion("CATEGORY_CODE is null");
            return this;
        }

        public Criteria andCategoryCodeIsNotNull() {
            addCriterion("CATEGORY_CODE is not null");
            return this;
        }

        public Criteria andCategoryCodeEqualTo(String value) {
            addCriterion("CATEGORY_CODE =", value, "categoryCode");
            return this;
        }

        public Criteria andCategoryCodeNotEqualTo(String value) {
            addCriterion("CATEGORY_CODE <>", value, "categoryCode");
            return this;
        }

        public Criteria andCategoryCodeGreaterThan(String value) {
            addCriterion("CATEGORY_CODE >", value, "categoryCode");
            return this;
        }

        public Criteria andCategoryCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_CODE >=", value, "categoryCode");
            return this;
        }

        public Criteria andCategoryCodeLessThan(String value) {
            addCriterion("CATEGORY_CODE <", value, "categoryCode");
            return this;
        }

        public Criteria andCategoryCodeLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_CODE <=", value, "categoryCode");
            return this;
        }

        public Criteria andCategoryCodeLike(String value) {
            addCriterion("CATEGORY_CODE like", value, "categoryCode");
            return this;
        }

        public Criteria andCategoryCodeNotLike(String value) {
            addCriterion("CATEGORY_CODE not like", value, "categoryCode");
            return this;
        }

        public Criteria andCategoryCodeIn(List values) {
            addCriterion("CATEGORY_CODE in", values, "categoryCode");
            return this;
        }

        public Criteria andCategoryCodeNotIn(List values) {
            addCriterion("CATEGORY_CODE not in", values, "categoryCode");
            return this;
        }

        public Criteria andCategoryCodeBetween(String value1, String value2) {
            addCriterion("CATEGORY_CODE between", value1, value2, "categoryCode");
            return this;
        }

        public Criteria andCategoryCodeNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_CODE not between", value1, value2, "categoryCode");
            return this;
        }

        public Criteria andStyleIsNull() {
            addCriterion("STYLE is null");
            return this;
        }

        public Criteria andStyleIsNotNull() {
            addCriterion("STYLE is not null");
            return this;
        }

        public Criteria andStyleEqualTo(String value) {
            addCriterion("STYLE =", value, "style");
            return this;
        }

        public Criteria andStyleNotEqualTo(String value) {
            addCriterion("STYLE <>", value, "style");
            return this;
        }

        public Criteria andStyleGreaterThan(String value) {
            addCriterion("STYLE >", value, "style");
            return this;
        }

        public Criteria andStyleGreaterThanOrEqualTo(String value) {
            addCriterion("STYLE >=", value, "style");
            return this;
        }

        public Criteria andStyleLessThan(String value) {
            addCriterion("STYLE <", value, "style");
            return this;
        }

        public Criteria andStyleLessThanOrEqualTo(String value) {
            addCriterion("STYLE <=", value, "style");
            return this;
        }

        public Criteria andStyleLike(String value) {
            addCriterion("STYLE like", value, "style");
            return this;
        }

        public Criteria andStyleNotLike(String value) {
            addCriterion("STYLE not like", value, "style");
            return this;
        }

        public Criteria andStyleIn(List values) {
            addCriterion("STYLE in", values, "style");
            return this;
        }

        public Criteria andStyleNotIn(List values) {
            addCriterion("STYLE not in", values, "style");
            return this;
        }

        public Criteria andStyleBetween(String value1, String value2) {
            addCriterion("STYLE between", value1, value2, "style");
            return this;
        }

        public Criteria andStyleNotBetween(String value1, String value2) {
            addCriterion("STYLE not between", value1, value2, "style");
            return this;
        }

        public Criteria andModelNameIsNull() {
            addCriterion("MODEL_NAME is null");
            return this;
        }

        public Criteria andModelNameIsNotNull() {
            addCriterion("MODEL_NAME is not null");
            return this;
        }

        public Criteria andModelNameEqualTo(String value) {
            addCriterion("MODEL_NAME =", value, "modelName");
            return this;
        }

        public Criteria andModelNameNotEqualTo(String value) {
            addCriterion("MODEL_NAME <>", value, "modelName");
            return this;
        }

        public Criteria andModelNameGreaterThan(String value) {
            addCriterion("MODEL_NAME >", value, "modelName");
            return this;
        }

        public Criteria andModelNameGreaterThanOrEqualTo(String value) {
            addCriterion("MODEL_NAME >=", value, "modelName");
            return this;
        }

        public Criteria andModelNameLessThan(String value) {
            addCriterion("MODEL_NAME <", value, "modelName");
            return this;
        }

        public Criteria andModelNameLessThanOrEqualTo(String value) {
            addCriterion("MODEL_NAME <=", value, "modelName");
            return this;
        }

        public Criteria andModelNameLike(String value) {
            addCriterion("MODEL_NAME like", value, "modelName");
            return this;
        }

        public Criteria andModelNameNotLike(String value) {
            addCriterion("MODEL_NAME not like", value, "modelName");
            return this;
        }

        public Criteria andModelNameIn(List values) {
            addCriterion("MODEL_NAME in", values, "modelName");
            return this;
        }

        public Criteria andModelNameNotIn(List values) {
            addCriterion("MODEL_NAME not in", values, "modelName");
            return this;
        }

        public Criteria andModelNameBetween(String value1, String value2) {
            addCriterion("MODEL_NAME between", value1, value2, "modelName");
            return this;
        }

        public Criteria andModelNameNotBetween(String value1, String value2) {
            addCriterion("MODEL_NAME not between", value1, value2, "modelName");
            return this;
        }

        public Criteria andModelFileSnIsNull() {
            addCriterion("MODEL_FILE_SN is null");
            return this;
        }

        public Criteria andModelFileSnIsNotNull() {
            addCriterion("MODEL_FILE_SN is not null");
            return this;
        }

        public Criteria andModelFileSnEqualTo(Long value) {
            addCriterion("MODEL_FILE_SN =", value, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnNotEqualTo(Long value) {
            addCriterion("MODEL_FILE_SN <>", value, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnGreaterThan(Long value) {
            addCriterion("MODEL_FILE_SN >", value, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("MODEL_FILE_SN >=", value, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnLessThan(Long value) {
            addCriterion("MODEL_FILE_SN <", value, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnLessThanOrEqualTo(Long value) {
            addCriterion("MODEL_FILE_SN <=", value, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnIn(List values) {
            addCriterion("MODEL_FILE_SN in", values, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnNotIn(List values) {
            addCriterion("MODEL_FILE_SN not in", values, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnBetween(Long value1, Long value2) {
            addCriterion("MODEL_FILE_SN between", value1, value2, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnNotBetween(Long value1, Long value2) {
            addCriterion("MODEL_FILE_SN not between", value1, value2, "modelFileSn");
            return this;
        }

        public Criteria andDesignIsNull() {
            addCriterion("DESIGN is null");
            return this;
        }

        public Criteria andDesignIsNotNull() {
            addCriterion("DESIGN is not null");
            return this;
        }

        public Criteria andDesignEqualTo(String value) {
            addCriterion("DESIGN =", value, "design");
            return this;
        }

        public Criteria andDesignNotEqualTo(String value) {
            addCriterion("DESIGN <>", value, "design");
            return this;
        }

        public Criteria andDesignGreaterThan(String value) {
            addCriterion("DESIGN >", value, "design");
            return this;
        }

        public Criteria andDesignGreaterThanOrEqualTo(String value) {
            addCriterion("DESIGN >=", value, "design");
            return this;
        }

        public Criteria andDesignLessThan(String value) {
            addCriterion("DESIGN <", value, "design");
            return this;
        }

        public Criteria andDesignLessThanOrEqualTo(String value) {
            addCriterion("DESIGN <=", value, "design");
            return this;
        }

        public Criteria andDesignLike(String value) {
            addCriterion("DESIGN like", value, "design");
            return this;
        }

        public Criteria andDesignNotLike(String value) {
            addCriterion("DESIGN not like", value, "design");
            return this;
        }

        public Criteria andDesignIn(List values) {
            addCriterion("DESIGN in", values, "design");
            return this;
        }

        public Criteria andDesignNotIn(List values) {
            addCriterion("DESIGN not in", values, "design");
            return this;
        }

        public Criteria andDesignBetween(String value1, String value2) {
            addCriterion("DESIGN between", value1, value2, "design");
            return this;
        }

        public Criteria andDesignNotBetween(String value1, String value2) {
            addCriterion("DESIGN not between", value1, value2, "design");
            return this;
        }

        public Criteria andIsWithCoreIsNull() {
            addCriterion("IS_WITH_CORE is null");
            return this;
        }

        public Criteria andIsWithCoreIsNotNull() {
            addCriterion("IS_WITH_CORE is not null");
            return this;
        }

        public Criteria andIsWithCoreEqualTo(Integer value) {
            addCriterion("IS_WITH_CORE =", value, "isWithCore");
            return this;
        }

        public Criteria andIsWithCoreNotEqualTo(Integer value) {
            addCriterion("IS_WITH_CORE <>", value, "isWithCore");
            return this;
        }

        public Criteria andIsWithCoreGreaterThan(Integer value) {
            addCriterion("IS_WITH_CORE >", value, "isWithCore");
            return this;
        }

        public Criteria andIsWithCoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_WITH_CORE >=", value, "isWithCore");
            return this;
        }

        public Criteria andIsWithCoreLessThan(Integer value) {
            addCriterion("IS_WITH_CORE <", value, "isWithCore");
            return this;
        }

        public Criteria andIsWithCoreLessThanOrEqualTo(Integer value) {
            addCriterion("IS_WITH_CORE <=", value, "isWithCore");
            return this;
        }

        public Criteria andIsWithCoreIn(List values) {
            addCriterion("IS_WITH_CORE in", values, "isWithCore");
            return this;
        }

        public Criteria andIsWithCoreNotIn(List values) {
            addCriterion("IS_WITH_CORE not in", values, "isWithCore");
            return this;
        }

        public Criteria andIsWithCoreBetween(Integer value1, Integer value2) {
            addCriterion("IS_WITH_CORE between", value1, value2, "isWithCore");
            return this;
        }

        public Criteria andIsWithCoreNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_WITH_CORE not between", value1, value2, "isWithCore");
            return this;
        }

        public Criteria andFillerIsNull() {
            addCriterion("FILLER is null");
            return this;
        }

        public Criteria andFillerIsNotNull() {
            addCriterion("FILLER is not null");
            return this;
        }

        public Criteria andFillerEqualTo(String value) {
            addCriterion("FILLER =", value, "filler");
            return this;
        }

        public Criteria andFillerNotEqualTo(String value) {
            addCriterion("FILLER <>", value, "filler");
            return this;
        }

        public Criteria andFillerGreaterThan(String value) {
            addCriterion("FILLER >", value, "filler");
            return this;
        }

        public Criteria andFillerGreaterThanOrEqualTo(String value) {
            addCriterion("FILLER >=", value, "filler");
            return this;
        }

        public Criteria andFillerLessThan(String value) {
            addCriterion("FILLER <", value, "filler");
            return this;
        }

        public Criteria andFillerLessThanOrEqualTo(String value) {
            addCriterion("FILLER <=", value, "filler");
            return this;
        }

        public Criteria andFillerLike(String value) {
            addCriterion("FILLER like", value, "filler");
            return this;
        }

        public Criteria andFillerNotLike(String value) {
            addCriterion("FILLER not like", value, "filler");
            return this;
        }

        public Criteria andFillerIn(List values) {
            addCriterion("FILLER in", values, "filler");
            return this;
        }

        public Criteria andFillerNotIn(List values) {
            addCriterion("FILLER not in", values, "filler");
            return this;
        }

        public Criteria andFillerBetween(String value1, String value2) {
            addCriterion("FILLER between", value1, value2, "filler");
            return this;
        }

        public Criteria andFillerNotBetween(String value1, String value2) {
            addCriterion("FILLER not between", value1, value2, "filler");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("STATUS in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("STATUS not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return this;
        }

        public Criteria andShelvesTimeIsNull() {
            addCriterion("SHELVES_TIME is null");
            return this;
        }

        public Criteria andShelvesTimeIsNotNull() {
            addCriterion("SHELVES_TIME is not null");
            return this;
        }

        public Criteria andShelvesTimeEqualTo(Date value) {
            addCriterion("SHELVES_TIME =", value, "shelvesTime");
            return this;
        }

        public Criteria andShelvesTimeNotEqualTo(Date value) {
            addCriterion("SHELVES_TIME <>", value, "shelvesTime");
            return this;
        }

        public Criteria andShelvesTimeGreaterThan(Date value) {
            addCriterion("SHELVES_TIME >", value, "shelvesTime");
            return this;
        }

        public Criteria andShelvesTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SHELVES_TIME >=", value, "shelvesTime");
            return this;
        }

        public Criteria andShelvesTimeLessThan(Date value) {
            addCriterion("SHELVES_TIME <", value, "shelvesTime");
            return this;
        }

        public Criteria andShelvesTimeLessThanOrEqualTo(Date value) {
            addCriterion("SHELVES_TIME <=", value, "shelvesTime");
            return this;
        }

        public Criteria andShelvesTimeIn(List values) {
            addCriterion("SHELVES_TIME in", values, "shelvesTime");
            return this;
        }

        public Criteria andShelvesTimeNotIn(List values) {
            addCriterion("SHELVES_TIME not in", values, "shelvesTime");
            return this;
        }

        public Criteria andShelvesTimeBetween(Date value1, Date value2) {
            addCriterion("SHELVES_TIME between", value1, value2, "shelvesTime");
            return this;
        }

        public Criteria andShelvesTimeNotBetween(Date value1, Date value2) {
            addCriterion("SHELVES_TIME not between", value1, value2, "shelvesTime");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(List values) {
            addCriterion("REMARK in", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List values) {
            addCriterion("REMARK not in", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return this;
        }

        public Criteria andAdderSnIsNull() {
            addCriterion("ADDER_SN is null");
            return this;
        }

        public Criteria andAdderSnIsNotNull() {
            addCriterion("ADDER_SN is not null");
            return this;
        }

        public Criteria andAdderSnEqualTo(Long value) {
            addCriterion("ADDER_SN =", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotEqualTo(Long value) {
            addCriterion("ADDER_SN <>", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThan(Long value) {
            addCriterion("ADDER_SN >", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN >=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThan(Long value) {
            addCriterion("ADDER_SN <", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN <=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnIn(List values) {
            addCriterion("ADDER_SN in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotIn(List values) {
            addCriterion("ADDER_SN not in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN not between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderNameIsNull() {
            addCriterion("ADDER_NAME is null");
            return this;
        }

        public Criteria andAdderNameIsNotNull() {
            addCriterion("ADDER_NAME is not null");
            return this;
        }

        public Criteria andAdderNameEqualTo(String value) {
            addCriterion("ADDER_NAME =", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotEqualTo(String value) {
            addCriterion("ADDER_NAME <>", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThan(String value) {
            addCriterion("ADDER_NAME >", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME >=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThan(String value) {
            addCriterion("ADDER_NAME <", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME <=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLike(String value) {
            addCriterion("ADDER_NAME like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotLike(String value) {
            addCriterion("ADDER_NAME not like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameIn(List values) {
            addCriterion("ADDER_NAME in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameNotIn(List values) {
            addCriterion("ADDER_NAME not in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameBetween(String value1, String value2) {
            addCriterion("ADDER_NAME between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAdderNameNotBetween(String value1, String value2) {
            addCriterion("ADDER_NAME not between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeIn(List values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeNotIn(List values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return this;
        }

        public Criteria andUpdaterSnIsNull() {
            addCriterion("UPDATER_SN is null");
            return this;
        }

        public Criteria andUpdaterSnIsNotNull() {
            addCriterion("UPDATER_SN is not null");
            return this;
        }

        public Criteria andUpdaterSnEqualTo(Long value) {
            addCriterion("UPDATER_SN =", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotEqualTo(Long value) {
            addCriterion("UPDATER_SN <>", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThan(Long value) {
            addCriterion("UPDATER_SN >", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN >=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThan(Long value) {
            addCriterion("UPDATER_SN <", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN <=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnIn(List values) {
            addCriterion("UPDATER_SN in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotIn(List values) {
            addCriterion("UPDATER_SN not in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN not between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterNameIsNull() {
            addCriterion("UPDATER_NAME is null");
            return this;
        }

        public Criteria andUpdaterNameIsNotNull() {
            addCriterion("UPDATER_NAME is not null");
            return this;
        }

        public Criteria andUpdaterNameEqualTo(String value) {
            addCriterion("UPDATER_NAME =", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotEqualTo(String value) {
            addCriterion("UPDATER_NAME <>", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThan(String value) {
            addCriterion("UPDATER_NAME >", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME >=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThan(String value) {
            addCriterion("UPDATER_NAME <", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME <=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLike(String value) {
            addCriterion("UPDATER_NAME like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotLike(String value) {
            addCriterion("UPDATER_NAME not like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameIn(List values) {
            addCriterion("UPDATER_NAME in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotIn(List values) {
            addCriterion("UPDATER_NAME not in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME not between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andModelFileVersionIsNull() {
            addCriterion("MODEL_FILE_VERSION is null");
            return this;
        }

        public Criteria andModelFileVersionIsNotNull() {
            addCriterion("MODEL_FILE_VERSION is not null");
            return this;
        }

        public Criteria andModelFileVersionEqualTo(Integer value) {
            addCriterion("MODEL_FILE_VERSION =", value, "modelFileVersion");
            return this;
        }

        public Criteria andModelFileVersionNotEqualTo(Integer value) {
            addCriterion("MODEL_FILE_VERSION <>", value, "modelFileVersion");
            return this;
        }

        public Criteria andModelFileVersionGreaterThan(Integer value) {
            addCriterion("MODEL_FILE_VERSION >", value, "modelFileVersion");
            return this;
        }

        public Criteria andModelFileVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("MODEL_FILE_VERSION >=", value, "modelFileVersion");
            return this;
        }

        public Criteria andModelFileVersionLessThan(Integer value) {
            addCriterion("MODEL_FILE_VERSION <", value, "modelFileVersion");
            return this;
        }

        public Criteria andModelFileVersionLessThanOrEqualTo(Integer value) {
            addCriterion("MODEL_FILE_VERSION <=", value, "modelFileVersion");
            return this;
        }

        public Criteria andModelFileVersionIn(List values) {
            addCriterion("MODEL_FILE_VERSION in", values, "modelFileVersion");
            return this;
        }

        public Criteria andModelFileVersionNotIn(List values) {
            addCriterion("MODEL_FILE_VERSION not in", values, "modelFileVersion");
            return this;
        }

        public Criteria andModelFileVersionBetween(Integer value1, Integer value2) {
            addCriterion("MODEL_FILE_VERSION between", value1, value2, "modelFileVersion");
            return this;
        }

        public Criteria andModelFileVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("MODEL_FILE_VERSION not between", value1, value2, "modelFileVersion");
            return this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("TYPE =", value, "type");
            return this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("TYPE <>", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("TYPE >", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("TYPE >=", value, "type");
            return this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("TYPE <", value, "type");
            return this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("TYPE <=", value, "type");
            return this;
        }

        public Criteria andTypeIn(List values) {
            addCriterion("TYPE in", values, "type");
            return this;
        }

        public Criteria andTypeNotIn(List values) {
            addCriterion("TYPE not in", values, "type");
            return this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return this;
        }
    }
}