package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "fnt_shopping_cart", Class = FntShoppingCart.class)
public class FntShoppingCart<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_shopping_cart.SN
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_shopping_cart.FURNITURE_ID
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    @Column
    private Long furnitureId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_shopping_cart.USER_ID
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    @Column
    private Long userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_shopping_cart.NUM
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    @Column
    private Integer num;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_shopping_cart.ADDER_SN
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_shopping_cart.ADDER_NAME
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_shopping_cart.ADD_TIME
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_shopping_cart.UPDATER_SN
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_shopping_cart.UPDATER_NAME
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_shopping_cart.UPDATE_TIME
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_shopping_cart.encryptSn
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_shopping_cart.SN
     *
     * @return the value of fnt_shopping_cart.SN
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_shopping_cart.SN
     *
     * @param sn the value for fnt_shopping_cart.SN
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_shopping_cart.FURNITURE_ID
     *
     * @return the value of fnt_shopping_cart.FURNITURE_ID
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public Long getFurnitureId() {
        return furnitureId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_shopping_cart.FURNITURE_ID
     *
     * @param furnitureId the value for fnt_shopping_cart.FURNITURE_ID
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public void setFurnitureId(Long furnitureId) {
        this.furnitureId = furnitureId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_shopping_cart.USER_ID
     *
     * @return the value of fnt_shopping_cart.USER_ID
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_shopping_cart.USER_ID
     *
     * @param userId the value for fnt_shopping_cart.USER_ID
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_shopping_cart.NUM
     *
     * @return the value of fnt_shopping_cart.NUM
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_shopping_cart.NUM
     *
     * @param num the value for fnt_shopping_cart.NUM
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_shopping_cart.ADDER_SN
     *
     * @return the value of fnt_shopping_cart.ADDER_SN
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_shopping_cart.ADDER_SN
     *
     * @param adderSn the value for fnt_shopping_cart.ADDER_SN
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_shopping_cart.ADDER_NAME
     *
     * @return the value of fnt_shopping_cart.ADDER_NAME
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_shopping_cart.ADDER_NAME
     *
     * @param adderName the value for fnt_shopping_cart.ADDER_NAME
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_shopping_cart.ADD_TIME
     *
     * @return the value of fnt_shopping_cart.ADD_TIME
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_shopping_cart.ADD_TIME
     *
     * @param addTime the value for fnt_shopping_cart.ADD_TIME
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_shopping_cart.UPDATER_SN
     *
     * @return the value of fnt_shopping_cart.UPDATER_SN
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_shopping_cart.UPDATER_SN
     *
     * @param updaterSn the value for fnt_shopping_cart.UPDATER_SN
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_shopping_cart.UPDATER_NAME
     *
     * @return the value of fnt_shopping_cart.UPDATER_NAME
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_shopping_cart.UPDATER_NAME
     *
     * @param updaterName the value for fnt_shopping_cart.UPDATER_NAME
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_shopping_cart.UPDATE_TIME
     *
     * @return the value of fnt_shopping_cart.UPDATE_TIME
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_shopping_cart.UPDATE_TIME
     *
     * @param updateTime the value for fnt_shopping_cart.UPDATE_TIME
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_shopping_cart.encryptSn
     *
     * @return the value of fnt_shopping_cart.encryptSn
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_shopping_cart.encryptSn
     *
     * @param encryptSn the value for fnt_shopping_cart.encryptSn
     *
     * @ibatorgenerated Mon Dec 12 11:18:45 CST 2016
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}