package com.focustech.focus3d.paint.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "paint_product", Class = PaintProduct.class)
public class PaintProductCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    public PaintProductCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    public PaintProductCriteria(PaintProductCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    public PaintProductCriteria(Object record, PaintProductCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table paint_product
     *
     * @ibatorgenerated Fri Dec 16 14:01:29 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSnIsNull() {
            addCriterion("SN is null");
            return this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("SN is not null");
            return this;
        }

        public Criteria andSnEqualTo(Long value) {
            addCriterion("SN =", value, "sn");
            return this;
        }

        public Criteria andSnNotEqualTo(Long value) {
            addCriterion("SN <>", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThan(Long value) {
            addCriterion("SN >", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SN >=", value, "sn");
            return this;
        }

        public Criteria andSnLessThan(Long value) {
            addCriterion("SN <", value, "sn");
            return this;
        }

        public Criteria andSnLessThanOrEqualTo(Long value) {
            addCriterion("SN <=", value, "sn");
            return this;
        }

        public Criteria andSnIn(List values) {
            addCriterion("SN in", values, "sn");
            return this;
        }

        public Criteria andSnNotIn(List values) {
            addCriterion("SN not in", values, "sn");
            return this;
        }

        public Criteria andSnBetween(Long value1, Long value2) {
            addCriterion("SN between", value1, value2, "sn");
            return this;
        }

        public Criteria andSnNotBetween(Long value1, Long value2) {
            addCriterion("SN not between", value1, value2, "sn");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("NAME in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("NAME not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return this;
        }

        public Criteria andColorNameIsNull() {
            addCriterion("COLOR_NAME is null");
            return this;
        }

        public Criteria andColorNameIsNotNull() {
            addCriterion("COLOR_NAME is not null");
            return this;
        }

        public Criteria andColorNameEqualTo(String value) {
            addCriterion("COLOR_NAME =", value, "colorName");
            return this;
        }

        public Criteria andColorNameNotEqualTo(String value) {
            addCriterion("COLOR_NAME <>", value, "colorName");
            return this;
        }

        public Criteria andColorNameGreaterThan(String value) {
            addCriterion("COLOR_NAME >", value, "colorName");
            return this;
        }

        public Criteria andColorNameGreaterThanOrEqualTo(String value) {
            addCriterion("COLOR_NAME >=", value, "colorName");
            return this;
        }

        public Criteria andColorNameLessThan(String value) {
            addCriterion("COLOR_NAME <", value, "colorName");
            return this;
        }

        public Criteria andColorNameLessThanOrEqualTo(String value) {
            addCriterion("COLOR_NAME <=", value, "colorName");
            return this;
        }

        public Criteria andColorNameLike(String value) {
            addCriterion("COLOR_NAME like", value, "colorName");
            return this;
        }

        public Criteria andColorNameNotLike(String value) {
            addCriterion("COLOR_NAME not like", value, "colorName");
            return this;
        }

        public Criteria andColorNameIn(List values) {
            addCriterion("COLOR_NAME in", values, "colorName");
            return this;
        }

        public Criteria andColorNameNotIn(List values) {
            addCriterion("COLOR_NAME not in", values, "colorName");
            return this;
        }

        public Criteria andColorNameBetween(String value1, String value2) {
            addCriterion("COLOR_NAME between", value1, value2, "colorName");
            return this;
        }

        public Criteria andColorNameNotBetween(String value1, String value2) {
            addCriterion("COLOR_NAME not between", value1, value2, "colorName");
            return this;
        }

        public Criteria andPicFileSnIsNull() {
            addCriterion("PIC_FILE_SN is null");
            return this;
        }

        public Criteria andPicFileSnIsNotNull() {
            addCriterion("PIC_FILE_SN is not null");
            return this;
        }

        public Criteria andPicFileSnEqualTo(Long value) {
            addCriterion("PIC_FILE_SN =", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnNotEqualTo(Long value) {
            addCriterion("PIC_FILE_SN <>", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnGreaterThan(Long value) {
            addCriterion("PIC_FILE_SN >", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("PIC_FILE_SN >=", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnLessThan(Long value) {
            addCriterion("PIC_FILE_SN <", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnLessThanOrEqualTo(Long value) {
            addCriterion("PIC_FILE_SN <=", value, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnIn(List values) {
            addCriterion("PIC_FILE_SN in", values, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnNotIn(List values) {
            addCriterion("PIC_FILE_SN not in", values, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnBetween(Long value1, Long value2) {
            addCriterion("PIC_FILE_SN between", value1, value2, "picFileSn");
            return this;
        }

        public Criteria andPicFileSnNotBetween(Long value1, Long value2) {
            addCriterion("PIC_FILE_SN not between", value1, value2, "picFileSn");
            return this;
        }

        public Criteria andModelFileSnIsNull() {
            addCriterion("MODEL_FILE_SN is null");
            return this;
        }

        public Criteria andModelFileSnIsNotNull() {
            addCriterion("MODEL_FILE_SN is not null");
            return this;
        }

        public Criteria andModelFileSnEqualTo(Long value) {
            addCriterion("MODEL_FILE_SN =", value, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnNotEqualTo(Long value) {
            addCriterion("MODEL_FILE_SN <>", value, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnGreaterThan(Long value) {
            addCriterion("MODEL_FILE_SN >", value, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("MODEL_FILE_SN >=", value, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnLessThan(Long value) {
            addCriterion("MODEL_FILE_SN <", value, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnLessThanOrEqualTo(Long value) {
            addCriterion("MODEL_FILE_SN <=", value, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnIn(List values) {
            addCriterion("MODEL_FILE_SN in", values, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnNotIn(List values) {
            addCriterion("MODEL_FILE_SN not in", values, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnBetween(Long value1, Long value2) {
            addCriterion("MODEL_FILE_SN between", value1, value2, "modelFileSn");
            return this;
        }

        public Criteria andModelFileSnNotBetween(Long value1, Long value2) {
            addCriterion("MODEL_FILE_SN not between", value1, value2, "modelFileSn");
            return this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("PRODUCT_ID is null");
            return this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("PRODUCT_ID is not null");
            return this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("PRODUCT_ID =", value, "productId");
            return this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("PRODUCT_ID <>", value, "productId");
            return this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("PRODUCT_ID >", value, "productId");
            return this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_ID >=", value, "productId");
            return this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("PRODUCT_ID <", value, "productId");
            return this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_ID <=", value, "productId");
            return this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("PRODUCT_ID like", value, "productId");
            return this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("PRODUCT_ID not like", value, "productId");
            return this;
        }

        public Criteria andProductIdIn(List values) {
            addCriterion("PRODUCT_ID in", values, "productId");
            return this;
        }

        public Criteria andProductIdNotIn(List values) {
            addCriterion("PRODUCT_ID not in", values, "productId");
            return this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("PRODUCT_ID between", value1, value2, "productId");
            return this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_ID not between", value1, value2, "productId");
            return this;
        }

        public Criteria andCateSnIsNull() {
            addCriterion("CATE_SN is null");
            return this;
        }

        public Criteria andCateSnIsNotNull() {
            addCriterion("CATE_SN is not null");
            return this;
        }

        public Criteria andCateSnEqualTo(Long value) {
            addCriterion("CATE_SN =", value, "cateSn");
            return this;
        }

        public Criteria andCateSnNotEqualTo(Long value) {
            addCriterion("CATE_SN <>", value, "cateSn");
            return this;
        }

        public Criteria andCateSnGreaterThan(Long value) {
            addCriterion("CATE_SN >", value, "cateSn");
            return this;
        }

        public Criteria andCateSnGreaterThanOrEqualTo(Long value) {
            addCriterion("CATE_SN >=", value, "cateSn");
            return this;
        }

        public Criteria andCateSnLessThan(Long value) {
            addCriterion("CATE_SN <", value, "cateSn");
            return this;
        }

        public Criteria andCateSnLessThanOrEqualTo(Long value) {
            addCriterion("CATE_SN <=", value, "cateSn");
            return this;
        }

        public Criteria andCateSnIn(List values) {
            addCriterion("CATE_SN in", values, "cateSn");
            return this;
        }

        public Criteria andCateSnNotIn(List values) {
            addCriterion("CATE_SN not in", values, "cateSn");
            return this;
        }

        public Criteria andCateSnBetween(Long value1, Long value2) {
            addCriterion("CATE_SN between", value1, value2, "cateSn");
            return this;
        }

        public Criteria andCateSnNotBetween(Long value1, Long value2) {
            addCriterion("CATE_SN not between", value1, value2, "cateSn");
            return this;
        }

        public Criteria andColorSnIsNull() {
            addCriterion("COLOR_SN is null");
            return this;
        }

        public Criteria andColorSnIsNotNull() {
            addCriterion("COLOR_SN is not null");
            return this;
        }

        public Criteria andColorSnEqualTo(Long value) {
            addCriterion("COLOR_SN =", value, "colorSn");
            return this;
        }

        public Criteria andColorSnNotEqualTo(Long value) {
            addCriterion("COLOR_SN <>", value, "colorSn");
            return this;
        }

        public Criteria andColorSnGreaterThan(Long value) {
            addCriterion("COLOR_SN >", value, "colorSn");
            return this;
        }

        public Criteria andColorSnGreaterThanOrEqualTo(Long value) {
            addCriterion("COLOR_SN >=", value, "colorSn");
            return this;
        }

        public Criteria andColorSnLessThan(Long value) {
            addCriterion("COLOR_SN <", value, "colorSn");
            return this;
        }

        public Criteria andColorSnLessThanOrEqualTo(Long value) {
            addCriterion("COLOR_SN <=", value, "colorSn");
            return this;
        }

        public Criteria andColorSnIn(List values) {
            addCriterion("COLOR_SN in", values, "colorSn");
            return this;
        }

        public Criteria andColorSnNotIn(List values) {
            addCriterion("COLOR_SN not in", values, "colorSn");
            return this;
        }

        public Criteria andColorSnBetween(Long value1, Long value2) {
            addCriterion("COLOR_SN between", value1, value2, "colorSn");
            return this;
        }

        public Criteria andColorSnNotBetween(Long value1, Long value2) {
            addCriterion("COLOR_SN not between", value1, value2, "colorSn");
            return this;
        }

        public Criteria andSizeIsNull() {
            addCriterion("SIZE is null");
            return this;
        }

        public Criteria andSizeIsNotNull() {
            addCriterion("SIZE is not null");
            return this;
        }

        public Criteria andSizeEqualTo(String value) {
            addCriterion("SIZE =", value, "size");
            return this;
        }

        public Criteria andSizeNotEqualTo(String value) {
            addCriterion("SIZE <>", value, "size");
            return this;
        }

        public Criteria andSizeGreaterThan(String value) {
            addCriterion("SIZE >", value, "size");
            return this;
        }

        public Criteria andSizeGreaterThanOrEqualTo(String value) {
            addCriterion("SIZE >=", value, "size");
            return this;
        }

        public Criteria andSizeLessThan(String value) {
            addCriterion("SIZE <", value, "size");
            return this;
        }

        public Criteria andSizeLessThanOrEqualTo(String value) {
            addCriterion("SIZE <=", value, "size");
            return this;
        }

        public Criteria andSizeLike(String value) {
            addCriterion("SIZE like", value, "size");
            return this;
        }

        public Criteria andSizeNotLike(String value) {
            addCriterion("SIZE not like", value, "size");
            return this;
        }

        public Criteria andSizeIn(List values) {
            addCriterion("SIZE in", values, "size");
            return this;
        }

        public Criteria andSizeNotIn(List values) {
            addCriterion("SIZE not in", values, "size");
            return this;
        }

        public Criteria andSizeBetween(String value1, String value2) {
            addCriterion("SIZE between", value1, value2, "size");
            return this;
        }

        public Criteria andSizeNotBetween(String value1, String value2) {
            addCriterion("SIZE not between", value1, value2, "size");
            return this;
        }

        public Criteria andDosageIsNull() {
            addCriterion("DOSAGE is null");
            return this;
        }

        public Criteria andDosageIsNotNull() {
            addCriterion("DOSAGE is not null");
            return this;
        }

        public Criteria andDosageEqualTo(String value) {
            addCriterion("DOSAGE =", value, "dosage");
            return this;
        }

        public Criteria andDosageNotEqualTo(String value) {
            addCriterion("DOSAGE <>", value, "dosage");
            return this;
        }

        public Criteria andDosageGreaterThan(String value) {
            addCriterion("DOSAGE >", value, "dosage");
            return this;
        }

        public Criteria andDosageGreaterThanOrEqualTo(String value) {
            addCriterion("DOSAGE >=", value, "dosage");
            return this;
        }

        public Criteria andDosageLessThan(String value) {
            addCriterion("DOSAGE <", value, "dosage");
            return this;
        }

        public Criteria andDosageLessThanOrEqualTo(String value) {
            addCriterion("DOSAGE <=", value, "dosage");
            return this;
        }

        public Criteria andDosageLike(String value) {
            addCriterion("DOSAGE like", value, "dosage");
            return this;
        }

        public Criteria andDosageNotLike(String value) {
            addCriterion("DOSAGE not like", value, "dosage");
            return this;
        }

        public Criteria andDosageIn(List values) {
            addCriterion("DOSAGE in", values, "dosage");
            return this;
        }

        public Criteria andDosageNotIn(List values) {
            addCriterion("DOSAGE not in", values, "dosage");
            return this;
        }

        public Criteria andDosageBetween(String value1, String value2) {
            addCriterion("DOSAGE between", value1, value2, "dosage");
            return this;
        }

        public Criteria andDosageNotBetween(String value1, String value2) {
            addCriterion("DOSAGE not between", value1, value2, "dosage");
            return this;
        }

        public Criteria andAdderSnIsNull() {
            addCriterion("ADDER_SN is null");
            return this;
        }

        public Criteria andAdderSnIsNotNull() {
            addCriterion("ADDER_SN is not null");
            return this;
        }

        public Criteria andAdderSnEqualTo(Long value) {
            addCriterion("ADDER_SN =", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotEqualTo(Long value) {
            addCriterion("ADDER_SN <>", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThan(Long value) {
            addCriterion("ADDER_SN >", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN >=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThan(Long value) {
            addCriterion("ADDER_SN <", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN <=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnIn(List values) {
            addCriterion("ADDER_SN in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotIn(List values) {
            addCriterion("ADDER_SN not in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN not between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderNameIsNull() {
            addCriterion("ADDER_NAME is null");
            return this;
        }

        public Criteria andAdderNameIsNotNull() {
            addCriterion("ADDER_NAME is not null");
            return this;
        }

        public Criteria andAdderNameEqualTo(String value) {
            addCriterion("ADDER_NAME =", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotEqualTo(String value) {
            addCriterion("ADDER_NAME <>", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThan(String value) {
            addCriterion("ADDER_NAME >", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME >=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThan(String value) {
            addCriterion("ADDER_NAME <", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME <=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLike(String value) {
            addCriterion("ADDER_NAME like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotLike(String value) {
            addCriterion("ADDER_NAME not like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameIn(List values) {
            addCriterion("ADDER_NAME in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameNotIn(List values) {
            addCriterion("ADDER_NAME not in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameBetween(String value1, String value2) {
            addCriterion("ADDER_NAME between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAdderNameNotBetween(String value1, String value2) {
            addCriterion("ADDER_NAME not between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeIn(List values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeNotIn(List values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return this;
        }

        public Criteria andUpdaterSnIsNull() {
            addCriterion("UPDATER_SN is null");
            return this;
        }

        public Criteria andUpdaterSnIsNotNull() {
            addCriterion("UPDATER_SN is not null");
            return this;
        }

        public Criteria andUpdaterSnEqualTo(Long value) {
            addCriterion("UPDATER_SN =", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotEqualTo(Long value) {
            addCriterion("UPDATER_SN <>", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThan(Long value) {
            addCriterion("UPDATER_SN >", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN >=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThan(Long value) {
            addCriterion("UPDATER_SN <", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN <=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnIn(List values) {
            addCriterion("UPDATER_SN in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotIn(List values) {
            addCriterion("UPDATER_SN not in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN not between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterNameIsNull() {
            addCriterion("UPDATER_NAME is null");
            return this;
        }

        public Criteria andUpdaterNameIsNotNull() {
            addCriterion("UPDATER_NAME is not null");
            return this;
        }

        public Criteria andUpdaterNameEqualTo(String value) {
            addCriterion("UPDATER_NAME =", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotEqualTo(String value) {
            addCriterion("UPDATER_NAME <>", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThan(String value) {
            addCriterion("UPDATER_NAME >", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME >=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThan(String value) {
            addCriterion("UPDATER_NAME <", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME <=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLike(String value) {
            addCriterion("UPDATER_NAME like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotLike(String value) {
            addCriterion("UPDATER_NAME not like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameIn(List values) {
            addCriterion("UPDATER_NAME in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotIn(List values) {
            addCriterion("UPDATER_NAME not in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME not between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }
    }
}