package com.focustech.focus3d.paint.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "paint_catgory", Class = PaintCatgory.class)
public class PaintCatgory<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_catgory.SN
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_catgory.NAME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    @Column
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_catgory.ADDER_SN
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_catgory.ADDER_NAME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_catgory.ADD_TIME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_catgory.UPDATER_SN
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_catgory.UPDATER_NAME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_catgory.UPDATE_TIME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_catgory.encryptSn
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_catgory.SN
     *
     * @return the value of paint_catgory.SN
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_catgory.SN
     *
     * @param sn the value for paint_catgory.SN
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_catgory.NAME
     *
     * @return the value of paint_catgory.NAME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_catgory.NAME
     *
     * @param name the value for paint_catgory.NAME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_catgory.ADDER_SN
     *
     * @return the value of paint_catgory.ADDER_SN
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_catgory.ADDER_SN
     *
     * @param adderSn the value for paint_catgory.ADDER_SN
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_catgory.ADDER_NAME
     *
     * @return the value of paint_catgory.ADDER_NAME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_catgory.ADDER_NAME
     *
     * @param adderName the value for paint_catgory.ADDER_NAME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_catgory.ADD_TIME
     *
     * @return the value of paint_catgory.ADD_TIME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_catgory.ADD_TIME
     *
     * @param addTime the value for paint_catgory.ADD_TIME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_catgory.UPDATER_SN
     *
     * @return the value of paint_catgory.UPDATER_SN
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_catgory.UPDATER_SN
     *
     * @param updaterSn the value for paint_catgory.UPDATER_SN
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_catgory.UPDATER_NAME
     *
     * @return the value of paint_catgory.UPDATER_NAME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_catgory.UPDATER_NAME
     *
     * @param updaterName the value for paint_catgory.UPDATER_NAME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_catgory.UPDATE_TIME
     *
     * @return the value of paint_catgory.UPDATE_TIME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_catgory.UPDATE_TIME
     *
     * @param updateTime the value for paint_catgory.UPDATE_TIME
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_catgory.encryptSn
     *
     * @return the value of paint_catgory.encryptSn
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_catgory.encryptSn
     *
     * @param encryptSn the value for paint_catgory.encryptSn
     *
     * @ibatorgenerated Fri Dec 16 13:50:08 CST 2016
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}