package com.focustech.focus3d.paint.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "paint_model", Class = PaintModel.class)
public class PaintModel<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.NAME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.PIC_FILE_SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private Long picFileSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.MODEL_FILE_SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private Long modelFileSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.USE_COUNT
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private Integer useCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.DOWNLOAD_COUNT
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private Long downloadCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.MODEL_TYPE
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private Integer modelType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.HOUSE_TYPE
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private Integer houseType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.ADDER_SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.ADDER_NAME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.ADD_TIME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.UPDATER_SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.UPDATER_NAME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.UPDATE_TIME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column paint_model.encryptSn
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.SN
     *
     * @return the value of paint_model.SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.SN
     *
     * @param sn the value for paint_model.SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.NAME
     *
     * @return the value of paint_model.NAME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.NAME
     *
     * @param name the value for paint_model.NAME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.PIC_FILE_SN
     *
     * @return the value of paint_model.PIC_FILE_SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public Long getPicFileSn() {
        return picFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.PIC_FILE_SN
     *
     * @param picFileSn the value for paint_model.PIC_FILE_SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setPicFileSn(Long picFileSn) {
        this.picFileSn = picFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.MODEL_FILE_SN
     *
     * @return the value of paint_model.MODEL_FILE_SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public Long getModelFileSn() {
        return modelFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.MODEL_FILE_SN
     *
     * @param modelFileSn the value for paint_model.MODEL_FILE_SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setModelFileSn(Long modelFileSn) {
        this.modelFileSn = modelFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.USE_COUNT
     *
     * @return the value of paint_model.USE_COUNT
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public Integer getUseCount() {
        return useCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.USE_COUNT
     *
     * @param useCount the value for paint_model.USE_COUNT
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setUseCount(Integer useCount) {
        this.useCount = useCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.DOWNLOAD_COUNT
     *
     * @return the value of paint_model.DOWNLOAD_COUNT
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public Long getDownloadCount() {
        return downloadCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.DOWNLOAD_COUNT
     *
     * @param downloadCount the value for paint_model.DOWNLOAD_COUNT
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setDownloadCount(Long downloadCount) {
        this.downloadCount = downloadCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.MODEL_TYPE
     *
     * @return the value of paint_model.MODEL_TYPE
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public Integer getModelType() {
        return modelType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.MODEL_TYPE
     *
     * @param modelType the value for paint_model.MODEL_TYPE
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setModelType(Integer modelType) {
        this.modelType = modelType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.HOUSE_TYPE
     *
     * @return the value of paint_model.HOUSE_TYPE
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public Integer getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.HOUSE_TYPE
     *
     * @param houseType the value for paint_model.HOUSE_TYPE
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setHouseType(Integer houseType) {
        this.houseType = houseType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.ADDER_SN
     *
     * @return the value of paint_model.ADDER_SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.ADDER_SN
     *
     * @param adderSn the value for paint_model.ADDER_SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.ADDER_NAME
     *
     * @return the value of paint_model.ADDER_NAME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.ADDER_NAME
     *
     * @param adderName the value for paint_model.ADDER_NAME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.ADD_TIME
     *
     * @return the value of paint_model.ADD_TIME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.ADD_TIME
     *
     * @param addTime the value for paint_model.ADD_TIME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.UPDATER_SN
     *
     * @return the value of paint_model.UPDATER_SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.UPDATER_SN
     *
     * @param updaterSn the value for paint_model.UPDATER_SN
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.UPDATER_NAME
     *
     * @return the value of paint_model.UPDATER_NAME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.UPDATER_NAME
     *
     * @param updaterName the value for paint_model.UPDATER_NAME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.UPDATE_TIME
     *
     * @return the value of paint_model.UPDATE_TIME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.UPDATE_TIME
     *
     * @param updateTime the value for paint_model.UPDATE_TIME
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column paint_model.encryptSn
     *
     * @return the value of paint_model.encryptSn
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column paint_model.encryptSn
     *
     * @param encryptSn the value for paint_model.encryptSn
     *
     * @ibatorgenerated Fri Dec 16 12:24:10 CST 2016
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}